### ISSUE TITLE
Increase PostgreSQL minimum version to 12 and default to 14 [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [SORMAS-Foundation/SORMAS-Project#10249]
### Problem Description
Postgres versions below 11 are no longer supported (https://www.postgresql.org/support/versioning/), but are still mentioned in the server setup instructions for SORMAS.
New versions are released every year and old versions no longer supported after 5 years, so we should also make sure the latest version of postgres is working with SORMAS and is the suggested postgres version when setting up a system.
Besides the security aspect this also blocks us from using new functionality (like the uuid-ossp module that would be very helpful for #7086).

### Proposed Change

Requires #10260.

- [x] Update postgres to version 14 for a sormas instance that was setup with a previous version and check whether it's working
- [x] Setup a new sormas instance with postgres 14 and see whether it's working
- [x] Add a "minimum version 12"-check to server-setup.sh and update the expected default postgres directory to the current version 14
- [x] Update server setup instructions: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_SETUP.md#postgres-database
- [x] Provide a PR for sormas docker to update to postgres 14
- [x] Mention in the [breaking changes section](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_UPDATE.md#breaking-updates) that at least Ubuntu LTS 20 (or 18 with postgres 12 from APT) is needed

### Implementation Details

- [ ] Refactor/Update currently used `ExtendedPostgreSQL94Dialect`.

### Additional Information

- This ticket aims to help #6024 which needs Postgres 12

**Comment by sergiupacurariu** [comment]
Steps to upgrade PostgrSQL server:
-	install new postgres server - it will be installed on C:\Program files\PostgreSQL\version; 2 major versions can coexist in the same time on the same computer as they will be installed on different folders; the installation is done automatically from the installer (check postgress resources)
-	remove temporal_tables from extensions; use "Drop cascade" (use pgAdmin)
-	for upgrade consistency check run: "C:\Program Files\PostgreSQL\14\bin\pg_upgrade.exe" --old-bindir "C:\Program Files\PostgreSQL\10\bin" --new-bindir "C:\Program Files\PostgreSQL\14\bin" --old-datadir "C:\Program Files\PostgreSQL\10\data" --new-datadir "C:\Program Files\PostgreSQL\14\data"  --link --check -U postgres
-	to perform the actual upgrade run: "C:\Program Files\PostgreSQL\14\bin\pg_upgrade.exe" --old-bindir "C:\Program Files\PostgreSQL\10\bin" --new-bindir "C:\Program Files\PostgreSQL\14\bin" --old-datadir "C:\Program Files\PostgreSQL\10\data" --new-datadir "C:\Program Files\PostgreSQL\14\data"  --link -U postgres”
-	the old server most likely is installed using port 5432 so the new server will be installed on 5433
o	go to: ….domains\sormas\config\domain.xml and change the port number for sormas_db to 5433 (in case is needed meaning the new db server has a new port)
