### ISSUE TITLE
Show full content of the text when hovering over the field

### ISSUE THREAD

**Issue by roxanamlendea** [SORMAS-Foundation/SORMAS-Project#10257]
### Problem Description
There are multiple fields in different Directories and Page Tabs which are cut off because the text is too long, but, on most of them, the full text is not shown when the user hovers over them. 
However, on some of the fields (eg. Contacts Directory -> 'Classification of the source case' field, the text is fully displayed on hover).

![image](https://user-images.githubusercontent.com/89522688/187843269-cefcc23d-93c0-4839-a0c6-4c683aaedef8.png)

### Proposed Change
The full content of the text should be displayed when the user hovers over the filed.
An example would be:  Contacts Directory -> 'Classification of the source case' field

![image](https://user-images.githubusercontent.com/89522688/187843185-11701c48-9277-417a-a518-ce812a8c39e2.png)

**Comment by richardbartha** [comment]
Tested on https://test-de1.sormas.netzlink.com/ version [1.96.0](https://github.com/sormas-foundation/SORMAS-Project/commits/da26401a15ea6393ca2a8d83f1e6e2ce60ea4ffb)
