### ISSUE TITLE
The synchronization of the mobile app is not successful when the db has an Event with a huge number of Event Participants

### ISSUE THREAD

**Issue by roxanamlendea** [SORMAS-Foundation/SORMAS-Project#10348]
The issue was discovered on 31 aug and I reported it as a comment in ticket #10231, because we thought it was the same issue causing the failing of the synchronization. 
The synchronization of the mobile app is not successful when the database has an Event with a huge number of Event Participants (over 17.000 EP). 
At that time, the status of the synchronization wasn't implemented yet, and we didn't know what problem was causing the timeout.

Note: 
The initial synchronization is working fine. 
Also, the synchronization of the Persons is working fine.

[logs from 13 sept.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9556566/logs.from.13.sept.txt)

Steps to reproduce:
1. Create an Event and import a file with a number of 17000 Event Participants.
2. Open the mobile app (wait for the initial sync to be completed);
3. Then trigger a synchronization

-> The synchronization is failing when it's trying to synchronize the Events. 

![image](https://user-images.githubusercontent.com/89522688/189888039-adf57dad-35fe-4506-8c3f-8dc0a0e099b5.png)

![image](https://user-images.githubusercontent.com/89522688/187675332-b20ee450-b9bc-4ee8-8569-8197d0044d9d.png)

I attach the logs for this sync error. 
[logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9461368/logs.txt) (from 31 aug)

_Originally posted by @roxanamlendea in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10231#issuecomment-1232855079_

**Comment by adinaflorea9** [comment]
Issue is reproducible on my local machine as well since importing over 10.000 persons (event participants and contacts with source cases) in the DB.

[timeout.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9556579/timeout.txt)
