### ISSUE TITLE
The Clinical Course tab from Case is visible even if the feature config VIEW_TAB_CASES_CLINICAL_COURSE is set false

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#10641]
### Bug Description
The Clinical Course tab from Case is visible even if the feature config VIEW_TAB_CASES_CLINICAL_COURSE is set false and the CLINICAL_MANAGEMENT set True

### Steps to Reproduce
1. Configure these 2 features VIEW_TAB_CASES_CLINICAL_COURSE = false and CLINICAL_MANAGEMENT = true
2. Login with a NationalUser
3. Go to Case directory
4. Edit a Case and look for the Clinical Course tab

### Actual Behavior
Clinical Course tab appears in the Case form

### Expected Behavior
Clinical Course tab should not appear as the setting for it is on false

### System Details

* Device:
* SORMAS version: 1.75.4; 1.76.0
* Android version/Browser:
* Server URL: Environment set with the features VIEW_TAB_CASES_CLINICAL_COURSE = false and CLINICAL_MANAGEMENT = true(ex: https://ga1.sormas-oegd.de/)
* User Role: NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (9faa29b);
The following bug small bug was also observed while testing, but this has already been logged: #10711.
