### ISSUE TITLE
Invalid automatic epi week selection in mSERS screen at the end of the year

### ISSUE THREAD

**Issue by SORMAS-ZohaibHassan** [SORMAS-Foundation/SORMAS-Project#11262]
### Bug Description

Whenever you try to sync from the mSERS module, the mobile app crashes

#### Steps to Reproduce

1. Go to mSERS module and tap on sync button

#### Screenshots

https://user-images.githubusercontent.com/8872102/209806203-b1798d2a-bc5c-4ef4-944f-72ae5327f03f.mp4

#### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.78.0
* Android version: 1.78.0
* Android Version: 11
* User Role: Contact and surveillance officer
* Server URL: release-international.sormas.netzlink.com

### Additional Information

To test this, set the date of the device to the last week of December, 2022.

Logs
[mSERS_Sync_Fail_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10313992/mSERS_Sync_Fail_log.txt)

**Comment by zohaibhassan122** [comment]
FYI: @bernardsilenou @MartinWahnschaffe @MateStrysewske

**Comment by adinaflorea9** [comment]
Discussed this morning with @sergiupacurariu and the issue that I found and logged in the comment above seems to not be related to this bug, but a different one. Will be documented in a separate bug issue. 

Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(b833199).

**Comment by MateStrysewske** [comment]
It's in fact not REALLY related to this bug here, but it's very related (=> doing a synchronization when no epi week is selected, just that in this case the user is responsible and not the app itself); so I'd actually like to fix it here anyway.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(5ee1eff).
