### ISSUE TITLE
Entities outside the user's 'disease jurisdiction' should not be editable for limited disease users

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11304]
### Problem Description

Entity pages of entities of all diseases are editable for users limited by a disease, as long as the responsible jurisdiction of the entities is within the user's jurisdiction. The behavior is reproducible for all entities, except immunizations. 

If the user has access to the URL link of wither one of the entities, or the person, they can now access all of the other associated entities as tickets #6052 and #6053 have added the possibility to navigate to all associated entities of a person either directly from the person page or from the entity person page (such as case person page, contact person page and so on).

#### Steps to Reproduce

1. Create a configured user (give them all rights from the configured user role page) but restrict them to a disease (eg. Cholera) and to a region and district (eg. Baden-Württemberg; LK Alb-Donau-Kreis);
2. With a regular Admin+NatUser create a person that has entities with the disease Covid associated in the region and district from step 1 (crate cases, contacts, travel entries and event+event participant);
3. Copy the URL of the person or of one of the entities from step 2;
4. Log in the app with the user from step 1 and paste the URL;
5. Observe the entity pages of all entities associated with the person from step 2.

Current behavior: The entities are editable even though they are of a different disease than the one to which the user is restricted by.

### Proposed Change

The entity pages of entities of other diseases than the disease that the logged in user is restricted by should not be editable for that user, as long as the logged in user is not the creator of the entities.

**Comment by bernardsilenou** [comment]
I think the limited disease user should not also have view rights,  through all views (case directory, general person form, contacts, events, etc), to entities of diseases that they are not assigned to.
