### ISSUE TITLE
Create automated test to check that Travel Entry tasks display the correct region and district in Task Management Directory

### ISSUE THREAD

**Issue by rdutu-vg** [SORMAS-Foundation/SORMAS-Project#11300]
Based on this fix:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/8199

Check that region and district in Task management results grid are taken from Travel Entry used to create a new task.

Steps:
1. Create new travel entry via API
2. Navigate to Task Management Directory
3. Filter by created travel entry
4. Validate Region and District are taken from created travel entry

**Comment by mk-sgent** [comment]
Github:
https://github.com/SORMAS-Foundation/SORMAS-Project/pull/13014
