### ISSUE TITLE
Create automated test to cover : User with 'View existing user roles' right can not open the 'User roles' tab

### ISSUE THREAD

**Issue by rdutu-vg** [SORMAS-Foundation/SORMAS-Project#11452]
Reference:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11396

Please use existing test to cover this step, if there's nothing in place proceed with a new automated test.

Please use all available users with defined role from configuration json file to make sure they all are able to see the roles tab.

**Comment by abrudanancuta** [comment]
New tests were added to the automation flow. Here are the test cases created:

- https://vitagroup-ag.atlassian.net/browse/SOR-4794
- https://vitagroup-ag.atlassian.net/browse/SOR-4793
