### ISSUE TITLE
[DEMIS - External messages] 'Meldedatum'/'Report Date' of external messages [1]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11454]
### Feature Description

Prefilling CaseDataDto.reportDate which should be mapped to „Meldedatum“ of the External Message as part of #11447.
Prefilling ContactDto.reportDate which should be mapped to „Meldedatum“ of the External Message as part of #11447.

### Proposed Change

- [ ] ~Add reportDate to ExternalMessage~
- [x] When creating a case/Contact via the processing of an external message (lab message or physician's report) the 'Date of report' of the case/Contact  should be prefilled from the external message's 'Meldedatum'/'Report date';
- [ ] ~Add 'Meldedatum'/ 'Report Date' section to the external message;~

### Acceptance Criteria

- the information from the 'Report date' of the external message is imported into the case/Contact  'Date of report';
- the current date validation for 'Date of report' of cases/Contacts are maintained;
- the 'Date of report' of the case/Contact  remains editable after it has been prefilled with the information from the external message.

**Comment by ChristopherRiedel** [comment]
We need to know wich date from the external message should be overtaken.

**Comment by ChristopherRiedel** [comment]
Report date should be prefilled with message date
