### ISSUE TITLE
Add bulk action progress window to all bulk actions except "Edit", "Archive" and "Delete" [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#11464]
### Problem Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/11597 has introduced a progress window for the "Edit" bulk actions. This window needs to be applied to other bulk actions as well to be consistent and because it's a lot more user-friendly.

### Proposed Change

Add the progress window to all bulk actions in all directories. The exceptions are the "Edit", "Archive, "Dearchive", "Delete" and "Restore" bulk actions because those are or have been handled in separate issues.

Also, the "Merge" bulk action in the person directory is excluded from this feature.

### Acceptance Criteria

- [x] All bulk actions (except the ones listed above) in all directories use the bulk action progress window introduced in #11597 when at least 40 entries are selected
- [x] The respective backend calls are done in batches of 20 entities when at least 40 entries are selected
- [x] The bulk action also works in the case detailed and contact detailed directories, which use different grids
- [x] Cancelling the action before it finishes leaves the selected entries that have not yet been processed still selected (as implemented in #11597)

### Additional Information

List of bulk actions that need to be changed (please double-check this when implementing the issue to make sure I haven't missed something):

~~- Cases: Create quarantine order documents~~
~~- Cases: Link to event~~
- Cases: Send to reporting tool
~~- Cases: Share~~
- Contacts: Cancel follow-up
- Contacts: Set to lost to follow-up
~~- Contacts: Create quarantine order documents~~
- Contacts: Link to event
~~- Contacts: Share~~
- Events: Group
~~- Events: Create quarantine order documents~~
- Events: Send to reporting tool
~~- EventParticipants: Create contacts~~
~~- EventParticipants: Create quarantine order documents~~
- Users: Enable
- Users: Disable

**Comment by leventegal-she** [comment]
The following bulk actions are not done yet and needs to be discussed:

* Cases: Create quarantine order documents
* Contacts: Create quarantine order documents
* Events: Create quarantine order documents
* EventParticipants: Create quarantine order documents

>These can be solved form a single place but there are 2 main problems:
> 1. Collecting document content for each batch and putting together at the end of the process
> 2. At the end of the process a zip file must be dowloaded automatically. The Vaadin file downloader does not support boulding the download data in a separate thread  and I didn't find a way to make the download automatic. Probably we'll need to display download a link  after the process is finished.

* Cases: Link to event
> It is done in two steps
> 1. handling already existing event participants -> it sets the resulting case but never saves - seems to be a bug.
> 2. creating event participants for the rest

> Do we do these steps for each sublist of cases? -> results in extra backend request for each batch.
> Do we do each step as a separate bulk process?


* Cases: Share
* Contacts: Share
> Implementing for this action it will produce multiple share requests, I don't know if we want this. Do the users really share so many entries at once?

* EventParticipants: Create contacts
> It displays a a form for each selected entry to set some values and some of them are required so I'm not sure users will ever use this action for more than 40 entries at once

**Comment by adinaflorea9** [comment]
Will move the ticket to waiting as parts of the comment above are unclear and need to be discussed before they can be logged in separate tickets or refined in this one.

**Comment by adinaflorea9** [comment]
To address the bug that @leventegal-she observed for cases ticket #12292  was created.

**Comment by adinaflorea9** [comment]
A follow-up ticket #12308 has been created to handle the introduction of the bulk progress bar window for the bulk action of 'Share' in the 'Cases' and  'Contacts' directories. 

The 'bulk progress bar window' will not be implemented for the bulk actions of:
- Create quarantine order documents (cases, contact, events, event participants);
- EventParticipants: Create contacts;
- Cases: Link to event.

**Comment by adinaflorea9** [comment]
I am reopening the ticket so that the following message that appears when the bulk process of Sending Cases to SurvNet is successful but some entities are skipped:
![Screenshot 2023-08-01 155346](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/f1c6c460-e38b-44b1-8c17-c40631bcb508)

Can be updated to be similar with the following:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/aa985150-9b85-494d-b87b-21ffaf06a5be)

**Comment by leventegal-she** [comment]
There is no skip functionality implemented there, it was just a mistake that I marked the failed batches as skipped.

I changed this behaviour to throw an error in case a batch fails.

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version - 1.87.0-SNAPSHOT(8090ceb). Exceptions that the bulk process runs into will be treated in a follow-up ticket - either #12257 or an issues linked to it.
