### ISSUE TITLE
Update the warning messages displayed when a user is not permitted to merge entities [2]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11517]
### Problem Description

Currently, the messages displayed in the grids for merging duplicate cases and contacts when the merge is stopped due to various reasons are not specific enough.

![image](https://user-images.githubusercontent.com/96909231/219964217-71ee1bb4-c886-4228-8c90-fc9b2005a4c4.png)

### Proposed Change

Introduce 'dynamic' messages that are displayed depending on the specific reasons why the merge of the entities is not possible in the grids for merging duplicate case and duplicate contacts.

### Acceptance Criteria

- [x] the messages should be displayed in the grid for merging duplicate cases and merging duplicate contacts; 

- [x] the messages should be 'dynamic' - different messages are displayed depending on the different reason why the merge is not possible;

- [ ] if there are more than 1 reason why the merge is not possible, all the messages should be displayed in the same pop-up;

- [x] when the user does not have the necessary user rights:
- 'The user does not have the necessary user rights to perform this action. Please reload the page to see the latest changes.'

- [x] when the user does not have the necessary responsible jurisdiction:
- 'The case outside the user's jurisdiction can not be edited. Please reload the page to see the latest changes'.
- 'The contact outside the user's jurisdiction can not be edited. Please reload the page to see the latest changes'.

- [x] when the entity is not editable anymore (i.e. the entity is archived, not editable, shared with ownership, other status that the entity can have that prohibits the editing);
- 'The case is not editable anymore. Please reload the page to see the latest changes.'
- 'The contact is not editable anymore. Please reload the page to see the latest changes.'

- [x] the messages are still displayed only after the user clicks 'Confirm' in the merge confirmation pop-up.

RestAPI - ticket #10251 improved the messages displayed in the API responses; when the two messages from above are displayed in the UI the error code that should appear in the API response should be:  '403: Forbidden: User does not have necessary user rights' (as from the list of responses this seems to fit best).

**Comment by carina29** [comment]
It was agreed with @MateStrysewske and @adinaflorea9 that the following acceptance criteria will not be necessary anymore:
-" if there are more than 1 reason why the merge is not possible, all the messages should be displayed in the same pop-up;"

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest changes from the development branch - 1.86.0-SNAPSHOT(7e35cd9). The translations are not yet available and once they exist in Crowdin they will also get updated.
