### ISSUE TITLE
Enable the cards on the person page for users that have view rights/edit rights [2]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11518]
### Problem Description

The cards on the person page are not enabled for users that have view rights, and in the case of the 'Samples' card, it is not enabled when the user has even edit rights over samples. Two scenarios can therefore be observed:

I: A user that has viewing rights over all entities in the app, and all of the rights associated with samples, the 'Samples' card on the person page is read only, as opposed to the sample cards on the other entities where the card is editable.

- on the person pages (from the 'Persons' directory): 
![image](https://user-images.githubusercontent.com/96909231/219965558-4348804c-de02-40a0-b860-b1ad8622a248.png)

- on the other entities (cases, contacts and event participants): 
![image](https://user-images.githubusercontent.com/96909231/219965592-27a4e226-7539-4f18-b329-5d1d799f0169.png)

II: A user that has only view rights over all entities in SORMAS, on the person pages, the buttons to 'See ... for this person' are not clickable.

### Proposed Change

I: The samples card should behave on the person page the same way it behaves on cases/contacts/event participants - it should be editable as long as the user has edit rights on the samples.

II: For a user that has view rights over the respective entities the buttons to 'See ... for this person' should be enabled.

### Added Value/Benefit
- easy navigation;
- users can action the rights they have from every flow that they have access to.

### Acceptance Criteria

I:
- [x] the user that has edit rights over an entity (ex: case, contact, event participant, samples, vaccination/immunization, travel entry) should see the card of the entity on the person page as editable ( pencil icon should also appear);
- [x] the button 'See samples for this person' should be clickable;

II:
- [x] if the user has view rights over the respective entity (such as 'View existing cases' + 'View existing persons') the buttons 'See ... for this person' should be enabled on the respective entity card;
- [x] when the respective entities are not within the user's jurisdiction the logic should remain as it currently is: the user can click the buttons, they are redirected to the respective grid filtered based on the person and based on whether the entities are owned or in the user's jurisdiction;
- [x] the buttons should also be enabled for persons whose associated entities are only 'To view' after sharing via S2S as long as the user has the view rights;
- [x] buttons to be covered are: 
- See cases for this person
- See contacts for this person
- See samples for this person
- See events for this person

**Comment by bernardsilenou** [comment]
@adinaflorea9 
- What is the reason that a user has edit rights to a sample but does not have the same rights to at lease one of the entities of the sample? Since samples are child entities, I suggest that we prevent this scenario.

**Comment by adinaflorea9** [comment]
@bernardsilenou the user that has edit rights over samples and no edit rights of the other entities was a configured one. In the past, before we had the option to configure users and user rights, there were users that had edit rights over samples and no edit rights over persons, cases etc, such as the 'External Lab Officer'. Therefore, I am not really in favour of preventing the scenario (thus not allowing a user to perform the actions that are correspondent to the rights that they have been given by an admin).

Moreover, the behavior for all the cards displayed should be consistent, therefore, since the 'Task' card is displayed for this user (over which the user has only view rights) then the Samples card should be displayed as well.  

Also, the user does have view rights for all entities, so they should be able to at least view them.

**Comment by bernardsilenou** [comment]
@adinaflorea9 
I forgot external lab users, this is a valid use case for this role.
Thanks

**Comment by carina29** [comment]
Note: @markusmann-vg , @MateStrysewske @adinaflorea9 
While I've worked on this task, I've found some inconsistencies.
We've agreed with @adinaflorea9 that I'll leave a comment here and if it will be considered, we can create a new story to solve these.

1)On Persons page and also on some other entity pages ( with side components) if the isEditAllowed value is coming as false for a specific uuid ( person, case, event and so on), some of the cards will be greyed out and some not.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/b1e9e5fb-df48-4635-982f-7986ccf4103c)

In case of Persons page I've checked the VaccinationList and TravelEntryList and these 2 entities also have an implementation which checks if the listEntry is active or not. If is not active, will be greyed out. 
This feature is missing from some of the other entities.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/e6022a92-4bfe-42d9-beb9-e4a7d2ac6c02)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/67123599-d786-4f26-b96f-a3841beb8157)

2) Another inconsistency is that the action button icon (eye) is not added for all the cards:
When the user has editing rights over a specific entity the pencil icon will appear in the card:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/6cf30cdf-5dda-4c20-8b0e-75d38757d955)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/3effe248-4b12-40fc-a0a1-10ad748f5aa9)

When the user does not have edit rights but have view rights, the eye icon should appear ( this feature was not implemented in the past for all the entities). 
From Person Page the eye is appearing only for Samples and Vaccinations:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/b36b6eb7-8600-41e1-ac26-a3425c3643fb)
![348378316_850819336462648_8976803137567710718_n](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/5b7047af-2622-4d41-91ce-0a86e5704bc4)

**Comment by MateStrysewske** [comment]
@carina29 Makes a lot of sense to create issues for these findings, yes!

**Comment by carina29** [comment]
@MateStrysewske @adinaflorea9 
I've created this ticket for the first finding from the above comment:  https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12054
I've also added the "needs -refinement" label because I've added a note to be discussed related to ( Case Person, Contact Person, Travel Entry Person cards' behaviour).

Please fill free to add new requirements or edit the ticket if you consider.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and on https://test-de2.sormas.netzlink.com/ using the latest version of SORMAS from the development branch - 1.85.0-SNAPSHOT(bd300c5).
