### ISSUE TITLE
Rename See samples for this person" to "See sample for this..." based on the associated entity [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11528]
### Problem Description

The button to 'See samples for...' on cases, contacts and event participants is currently displaying 'See samples for this person', even though the respective samples are associated with cases/contacts/event participants, and the filtering of the 'Samples' directory grid that is done when the button is clicked is based on either case/contact/event participant, and not the person as the button implies.

Additionally, when there are no samples associated with that entity, the descriptive text that is shown on the sample card is in accordance with the directory (i.e. in cases directory = 'There are no samples for this case').

### Proposed Change

For consistency reasons, rename See samples for this person" according to the directory page that it is displayed in:

Persons directory - should remain 'See samples for this person';

Cases directory - should be renamed 'See samples for this case';

Contacts directory - should be renamed 'See samples for this contact';

Events directory - should be renamed 'See samples for this event participant'.
### Acceptance Criteria

- the button 'See samples for this person' is renamed accordingly to the proposed change in each directory;

- the filtering of the samples grid done when the button is clicked should continue to behave the same - filter based on the entity associated with the sample.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(0799a1f).
