### ISSUE TITLE
Add a create/edit form for environments in the web app [5]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11535]
### Feature Description

After an Environment entity has been created in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11796 as part of epic https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11533, create and edit forms for this entity are now required for the web app.

### Added Value/Benefit
Users will be able to create and edit environment entities for further usage in the system.

### Acceptance Criteria

- [x] A creation form for environments has been added with the following fields:
  - Report date (required)
  - External ID
  - Environment name  (required)
  - Environment media (required)
  - Location form (region, district, gps lat and gps lon required; region and district pre-filled with the jurisdiction of the user if available)
  - Responsible user (contains a list of all users with the `ENVIRONMENT_EDIT` user right that are assigned to the district selected in the location form)
- [x] An edit form for environments has been added with all fields from the creation form and the following additional fields:
  - UUID (read only)
  - Reporting user (read only)
  - Investigation status (required)
  - Water type (if environment media == water)
  - Other water type (if water type == other)
  - Infrastructure details (if environment media == water)
  - Other infrastructure details (if infrastructure details == other)
  - A "Water use" heading (if environment media == water)
  - Checkboxes for all `WaterUse` enum values (if environment media == water); see the epidemiologicalEvidenceDetails checkboxes of events for reference
  - Other water use (if the checkbox for "Other" water use has been checked)
- [x] A "New Environment" button has been added to the environment directory created in #11534 that brings up the creation form
- [x] A column with an edit button has been added to the environment directory created in #11534 that takes the user to a dedicated page for the environment, displaying the edit form
- [x] The edit form contains functional buttons to delete and archive the environment if the user has the respective user rights
- [x] The location form includes the functionality to automatically pick the GPS coordinates based on the address details entered (already implemented; just verify that it's working)
- [x] The unsaved changes warning appears as expected for the edit form
- [x] The top navigation when inside the environment edit page contains a backlink that takes the user back to the environment directory

### Mockups
* creation form
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/12996724/ddef0eeb-8e77-45df-af61-ca9c0c7e3212)

* edit form
![env_editform](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/12996724/2fed5a4e-abcc-488e-82af-ce51a7637add)

### Additional Information

The tasks and samples on the right are not supposed to be implemented in this issue.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- Since Region, district, lat and log are required, Can we make the environment name non-required?  I have edited the mockup and also the specification.
- Would the change affect https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11796

**Comment by MateStrysewske** [comment]
@bernardsilenou I would advise against that because I think you need some sort of human readable representation of the entity that can be displayed e.g. in the directories. Otherwise you'll end up with pretty cryptical strings. Is there any necessity to drop the required constraint from the field?

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(19d39a6).

Ticket #12262 will treat the issues of users that have the edit rights over environmental entities but that have a jurisdiction higher than district or no jurisdiction, so that the users are included in the dropdowns of 'Responsible users' in the 'Environments' directory.

Two other issues will be linked that will treat the 'Reason for deletion' column being displayed in the 'Environments' directory grid for manually deleted entities, and one that will deal with the editability of environments based on the user's ownership over them and based on the regional jurisdiction.
