### ISSUE TITLE
Add an environment directory for the web app [5]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11534]
### Feature Description

After an Environment entity has been created in #11796 as part of epic #11533, a directory that lists those entities is now required for the web app.

### Added Value/Benefit
Users will be able to see and filter a list of the environment entities created in the system.

### Acceptance Criteria
- [x] A new main menu entry called "Environments" has been added with an appropriate icon (see the mockup below for inspiration); the entry has been placed directly below "Samples"
- [x] The entry is only visible when the feature added in #11572 is enabled and the user has the `ENVIRONMENT_VIEW` user right
- [x] The directory contains a grid showing EnvironmentIndexDtos with the following columns:
  - ID (= the UUID of the environment entity)
  - External ID
  - Name
  - Environment media
  - Region
  - District
  - Community
  - GPS lat
  - GPS lon
  - Postal code
  - City
  - Report date
  - Investigation status
- [x] Sorting has been added for all columns
- [x] A filter form has been added, containing the following filters and using the EnvironmentCriteria:
  - Free text filter that contains UUID, External ID, Name and Description
  - Region (hidden if user is on region level or below)
  - District (hidden if user is on district level or below; disabled if no region is selected)
  - Community (hidden if user is on community level or below; disabled if no district is selected)
  - Environment media
  - Responsible user
  - Report date range("from", "to" and a selection for "by date" or "by epi week" as in other directories)
  - GPS range ("lat from", "lat to", "lon from" and "lon to")
- [x] A relevance status filter has been added, aligned to the right as in other directories
- [x] Status buttons to filter by investigation status have been added (similar to the case directory)
- [x] A "New Environment" button has been added to the top right (non-functional for now)

### Additional Information

![image](https://user-images.githubusercontent.com/12996724/229363466-6f57e8f5-f967-4ed2-b9ec-b9621d1d154f.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(678c04b).

**Comment by MateStrysewske** [comment]
@adinaflorea9 @sergiupacurariu Submitted a pull request for this bug.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(19d39a6).
