### ISSUE TITLE
Consider source case region and district for contacts in detailed sample export

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11552]
### Problem Description

Currently, if a sample is associated with a contact that takes its jurisdiction from a source case, in the detailed export file of samples, that sample does not have a jurisdiction. In the main grid of the 'Samples' directory it is visible that the sample takes the district of the source case as that one is displayed in the grid, and based on that jurisdiction the sample can be searched/filtered for.

### Proposed Change

Fill the contact region, contact district and contact community columns in the detailed sample export file with the information from the responsible jurisdiction of the source case if the contact itself does not have a responsible region, district and community (if the contact has a region and district, but not a community, DON'T take over the case community).

**Comment by carina29** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - [1.96.0-SNAPSHOT(https://github.com/sormas-foundation/SORMAS-Project/commits/fe287e0cc8369723c3fa4f48b38e510078f3c0ab)
