### ISSUE TITLE
Add duplicate detection for environment import [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11569]
### Feature Description

This issue is part of the EPIC https://github.com/hzi-braunschweig/SORMAS-Project/issues/11533 on the environmental surveillance module. Add a duplicate detection for environments that triggers when environments are imported through a .csv file.

The following fields MUST be filled in in order for two environments being considered as duplicates:
- Environment media (must match)
- GPS lat (the two GPS lat coordinates must be within 0.02 digits from each other; i.e. 52.288 would be considered a potential duplicate for GPS lat values between 52.286 and 52.290; this is roughly 0.5 kilometers)
- GPS lon (same as GPS lat)

Additionally, if the following fields are specified in BOTH environments, they must match:
- Country
- Region
- District

If an external ID is specified for both environments, they MUST match and if they do, they overwrite all the other rules (i.e. two environments with the same external ID are considered as potential duplicates even if they're in different regions).

### Acceptance Criteria

- [x] The environment import window has been extended by a figure that lists the number of environments that have been skipped as duplicates (infrastructure import should already have something like this)
- [x] When importing environments, the environment is checked for potential duplicates in the database; please note that this has to happen in the database, without querying for all other environments first
- [x] If at least one potential duplicate has been found, the environment is not imported, but counted as a skip and written into the error log with the following info text in the first column: "Skipped as a potential duplicate"
- [x] An error log is produced and downloadable if at least one environment has been skipped, even if there were no other import errors
- [ ] The import guide has been extended with information about downloading the error log when duplicates have been detected (can be done by @MateStrysewske)

### Additional Information

Duplicate detection and merging (as we have it for cases) of Environments at Creation will be done in a later phase.
This duplicate detection is limited to import environments.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(f18d58e).
