### ISSUE TITLE
Add an environment sample grid to the web app [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11566]
### Feature Description

This issue is part of the EPIC https://github.com/hzi-braunschweig/SORMAS-Project/issues/11533 on the environmental surveillance module. Add a new environment sample grid to the existing samples directory. Users should be able to toggle between human samples and laboratory samples, similar to toggling between events and event groups in the events directory.

### Acceptance Criteria

- [x] A new toggle button has been added to the sample directory that allows switching between "Human" and "Environment". Selecting "Human" (default) brings up the existing samples grid, selecting "Environment" brings up the new grid vor environment samples
- [x] The toggle button is only shown when the user has view rights for both normal samples and environment samples and the respective feature is enabled; otherwise the list that the user has access to is always shown
- [x] The status of the toggle button is preserved, i.e. when the user has selected "Environment", this is still the case when they leave the samples directory and return to it
- [x] The following columns are shown:
  - Sample ID (= the UUID of the sample)
  - Field sample ID
  - Collection date (sampleDateTime)
  - Associated environment (caption of the reference dto)
  - Location (caption of the location of the environment)
  - District (of the location of the environment)
  - Dispatched
  - Dispatch date
  - Received
  - Laboratory
  - Sample material (or details if "Other")
  - Positive pathogen tests (has to be left empty for now because we don't have this information yet)
  - Latest pathogen test (has to be left empty for now because we don't have this information yet)
  - Number of tests (has to be left empty for now because we don't have this information yet)
  - Reason for deletion
- [x] The following filters are implemented:
  - Free text filter that filters by UUID, field sample ID, and the UUID and name of the environment
  - Region and district filters for the environment location
  - GPS lat and lon filters for the environment location (similar to the filters in the environment directory)
  - Laboratory
  - Tested pathogen (filled with all pathogens, but dysfunctional for now because not yet implemented for pathogen tests)
  - Date filters (already existing)
  - Active/archived/deleted status
  - Shipment status filters as for normal samples
- [x] The grid is properly pseudonymized, i.e. if the user does not have access to the personal/sensitive data (because of user rights or jurisdiction), "Confidential" is shown for pseudonymizable fields
- [x] A bulk mode for the "Delete" and "Restore" bulk actions has been added
- [x] The grid properly displays only entities that the user has access to based on the user filter

### Additional Information

![sample_directory](https://user-images.githubusercontent.com/12996724/229857229-1670469b-2264-496d-9318-2c89abb9e416.png)

**Comment by adinaflorea9** [comment]
Did not add the ready label as the mobile app part is not complete yet.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as when the user has rights only for environment samples they can not see the 'Samples' directory at all.

**Comment by MateStrysewske** [comment]
Reopening again because the values of the switch should be "Human" and "Environment"; currently it's "Sample" and "Environment"

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(a40591b).

**Comment by MateStrysewske** [comment]
Reopened due to the following change request: Change the caption of the directory to "Environment Sample Directory" if the environment sample grid is displayed
