### ISSUE TITLE
Add an import mechanism to the environment directory [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11571]
### Feature Description

Allow users to import environment entities through the environment directory. This issue is part of the EPIC https://github.com/hzi-braunschweig/SORMAS-Project/issues/11533 on the environmental surveillance module.

### Added Value/Benefit
Users can import environments from other sources or can batch-import a lot of environments without having to go through the creation form for each one of them.

### Acceptance Criteria

- [x] An "Import" button has been added to the environment directory to the left of the "New environment" button; only visible for users with the `ENVIRONMENT_IMPORT` user right
- [x] Clicking the button brings up the usual import window
- [x] An import guide adjusted to the environment import can be downloaded (use the .docx template to create one or ask @MateStrysewske for support)
- [x] An import template with all relevant environment fields can be downloaded
- [x] Environments can be successfully imported, and an error template can be downloaded if something goes wrong
- [x] A unit test that tests this functionality with an example .csv has been added

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(7be187a).
