### ISSUE TITLE
Add environment samples to sample status map [2]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11574]
### Feature Description

This issue is part of the EPIC #11533 on the environmental surveillance module. Display environment samples in the status map on the dashboard for users with access to them.

### Acceptance Criteria

- [x] A checkbox "Show environment samples" has been added to the "Layers" dropdown on the sample dashboard; only visible if the user has view access to environment samples
- [x] A symbol for environment samples has been introduced and added to the "Map key" dropdown; use a distinguishable shade of green as its color
- [x] Environment samples that are within the user's jurisdiction (or owned) are shown on the map if the filter is enabled
- [x] The samples are shown based on GPS coordinates; if a sample has GPS coordinates, use those, otherwise fall back to the environment
- [x] The info hint next to the "Sample Status Map" heading has been extended as follows for users with access to environment samples: "Samples are shown using the GPS coordinates of the person's home address. Environment samples are shown using the GPS coordinates of those samples or, if not available, their associated environment."

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the hint that appears for the 'Sample Status Map' does not appear extended as in the acceptance criteria but only displays 'Samples are shown using the GPS coordinates of the person's home address.' even when the only layer selected is Environment samples, or when all the layers are selected.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(eb73d9d).
