### ISSUE TITLE
Prevent the 'Undo deletion' of an event participant whose person is listed as active event participant within the same event

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11587]
### Problem Description

Currently, due to undo deletion, it is possible to have the same person listed multiple times as active event participant within the same event.

### Proposed Change

Prevent the undo deletion/Restore of an event participant if the same person is listed as an active/archived event participant within the same event.

This is needed as a person should not be allowed to have more than 1 entry as active or archived event participant within the same event.

### Acceptance Criteria

- [ ] Add a check, both in the frontend and backend so that the restore of an event participant is prohibited when the same person is already listed as active or archived event participant within that same event;
- [ ] when the user tries to restore (from the entity page or the bulk actions) such an event participant - display a warning message 'The person associated with the event participant is already listed as an active or archived event participant within the event'.

### Additional Information

Steps to reproduce the problem:
1. For Event 1, create Event participant 1 (make sure the person already has another entity associated such as a case or contact);
2. Soft delete Event participant 1;
3. Open the 'Create event participant' form and search for the person associated with Event participant 1;
4. Create the new event participant;
5. From the 'Deleted event participants' grid, undo the deletion of the event participant deleted at step 2.
Actual behavior:
The same person is now listed 2 times as event participant within the same event.

**Comment by richardbartha** [comment]
Tested on https://test-de1.sormas.netzlink.com/ version [1.96.0]https://github.com/sormas-foundation/SORMAS-Project/commits/da26401a15ea6393ca2a8d83f1e6e2ce60ea4ffb
