### ISSUE TITLE
Create automated test to cover User without 'Delete events from the system' rights

### ISSUE THREAD

**Issue by rdutu-vg** [SORMAS-Foundation/SORMAS-Project#11641]
Please follow steps from defect:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11638

Please create 2 tests to cover the following steps:

TEST - positive
1. Create/use user with delete rights
2. Navigate to Event
3. Open Event
4. Navigate to Event Actions tab
5. Create new action if doesn't exist
6. Edit action
7. Delete action
![image](https://user-images.githubusercontent.com/83643843/224939472-3b5c72f9-4dd3-472b-8178-7ecaa4d3e67e.png)

TEST - positive
1. Create/use user without delete rights
2. Navigate to Event
3. Open Event
4. Navigate to Event Actions tab
5. Create new action if doesn't exist
6. Edit action
7. Validate user cannot delete action

**Comment by mk-sgent** [comment]
Jira issue: https://netzlink-jira.atlassian.net/jira/software/c/projects/HSP/boards/1?selectedIssue=HSP-6576
Github: https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12950
