### ISSUE TITLE
Create a new Environment Sample entity [web + mobile] [8]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11721]
### Feature Description
As part of the environmental surveillance module (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11533), a new entity and DTO for samples taken off environments are needed. This issue is only about the backend/API part, while a UI issue will follow.

### Added Value/Benefit
For one health purposes, users need to be able to take samples of environments in order to analyze them.

### Acceptance Criteria
- [x] A new `EnvironmentSample` entity (extending DeletableAdo) has been added with the following fields (use the `text` datatype for all Strings except IDs; use 255 characters for those):
  - Environment `environment` (Environment) - required field
  - Date `sampleDateTime` (Date of sampling) - required field
  - EnvironmentSampleMaterial `sampleMaterial` (Sample material) - required field
  - String `otherSampleMaterial` (Specify sample material)
  - Float `sampleVolume` (Volume (in mL)) - validated at DTO level to be positive (`@Min` annotation)
  - String `fieldSampleId` (Field sample ID)
  - Integer `turbidity` (Turbidity (in NTU)) - validated at DTO level to be positive
  - Integer `phValue` (pH of sample) - validated at DTO level to be between 0 and 14
  - Integer `sampleTemperature` (Temperature (in °C))
  - Float `chlorineResiduals` (Total chlorine residuals (mg/L)) - validated at DTO level to be positive
  - Facility `laboratory` (Laboratory) - required field
  - String `laboratoryDetails` (Laboratory details)
  - Set<Pathogen> `requestedPathogenTests` (Requested pathogens to be tested) - #11840 is a pre-requisit for this
  - String `otherRequestedPathogenTests` (Other requested pathogens to be tested)
  - Map<WeatherCondition, Boolean> `weatherConditions` (Weather conditions at time of sampling) - similar to waterUse in the Environment entity
  - YesNoUnknown `heavyRain` (Heavy rain in the past 24 hours before sampling?)
  - boolean `dispatched` (Sent/dispatched)
  - Date `dispatchDate` (Dispatchment date)
  - String `dispatchDetails` (Dispatchment details)
  - boolean `received` (Received)
  - Date `receivalDate` (Receival date)
  - String `labSampleId` (Lab sample ID)
  - SpecimenCondition `specimenCondition` (Specimen condition)
  - Location `location` (Location of sampling site)
  - String `generalComment` (General comment)
- [x] A corresponding DTO and ReferenceDto have been created, along with a facade (extending DeletableFacade) and service
- [x] An EnvironmentSampleCriteria class has been added, alongside a buildCriteriaFilter method in the service; no content needed for now
- [x] A new EnvironmentSampleMaterial enum has been added with the following values (trivial captions ommitted):
  - `WATER`
  - `SOIL`
  - `AIR`
  - `VECTORS`
  - `OTHER`
- [x] A new WeatherCondition enum has been added with the following values (trivial captions ommitted):
  - `SUNNY`
  - `CLOUDY`
  - `RAINING`
  - `WINDY`
- [x] i18n has been added for all new fields/enum values
- [x] Synchronization logic between the web and mobile app has been added
- [x] The createUserFilter method in the service has been implemented; users have access to environment samples based on their jurisdiction and whether or not they're the reporting user. For the jurisdiction, take the location of the environment sample if present, and the location of the associated environment otherwise.
- [x] New user rights related to environment samples have been added, including appropriate captions and descriptions; add them to the ENVIRONMENT user right group:
  - `ENVIRONMENT_SAMPLE_VIEW`
  - `ENVIRONMENT_SAMPLE_CREATE`
  - `ENVIRONMENT_SAMPLE_EDIT_DISPATCH`
  - `ENVIRONMENT_SAMPLE_EDIT_RECEIVAL`
  - `ENVIRONMENT_DELETE`
  - `ENVIRONMENT_IMPORT` (depends on create)
  - `ENVIRONMENT_EXPORT`
- [x] All new user rights are dependant on ENVIRONMENT_SAMPLE_VIEW (except import)
- [x] These new user rights have been added to the default user roles Admin (all rights), National User (all rights), Environment Surveillance User (all rights), Laboratory User (only edit and export rights), and National Observer (only view right)

**Comment by leventegal-she** [comment]
While implementing #11572 it was necessary to add SAMPLE_VIEW and SAMPLE_EDIT rights to the new "Environmental Surveillance User" default user role because it was required by pathogen test related rights.

In this ticket we must consider introducing an "either-or" dependency between user rights and also changing the rights of the above user role via database migration.
