### ISSUE TITLE
Create automated test to cover : Filtering event participants based on 'Final laboratory result' seemingly leads to a loop

### ISSUE THREAD

**Issue by rdutu-vg** [SORMAS-Foundation/SORMAS-Project#11737]
### Problem Description

Issue described here:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11699

### Proposed Solution

Create new automated test to cover steps provided in the above defect.
Please set timelimit for loading spinner, so if the issue will reproduce, to avoid having a test running too much.

**Comment by abrudanancuta** [comment]
Automated test was implemented
