### ISSUE TITLE
Create automated test to cover : Filter for 'Person samples' does not work in combination with 'All active and archived samples' and 'Deleted samples' filters

### ISSUE THREAD

**Issue by rdutu-vg** [SORMAS-Foundation/SORMAS-Project#11736]
### Problem Description

Defect described here:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11668

### Proposed Solution

Please create new automated test based on the steps and combinations provided in the raised defect.

**Comment by mk-sgent** [comment]
Github:
https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12912
