### ISSUE TITLE
Don't allow the saving of forms that have mandatory fields filled only with 'spaces' [3]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11817]
### Problem Description

Forms that contain mandatory fields can be saved if the user inputs spaces in the mandatory fields.

### Proposed Change

Do not allow the saving of forms when only spaces have been inputted in the mandatory firlds.

### Added Value/Benefit

As long as it's possible to only enter spaces, users can circumvent text fields being mandatory which results in missing information. This change will ensure that this is no longer possible.

### Acceptance Criteria

- [ ] The `@NotBlank` annotation is used instead of `@NotNull` or `@NotEmpty` for all String fields in DTOs that are currently using the `@NotNull` or `@NotEmpty` annotation:
  - DocumentDto.name
  - DocumentDto.mimeType
  - DocumentDto.relatedEntityUuid
  - EventDto.name
  - EventGroupDto.name
  - PersonDto.firstName
  - PersonDto.lastName
  - ExternalVisitDto.personUuid
  - SormasToSormasOptionsDto.comment
  - SormasToSormasOriginInfoDto.comment
- [ ] Forms that have text fields marked as mandatory can no longer be saved when only putting in blank spaces
- [ ] Instead, an error message appears that the field is a required field
- [ ] Additionally, `isBlank` is used instead of `isEmpty` when validating the dearchive reason field in `ArchivingController.dearchiveEntity`, and it is no longer possible to specify a dearchive reason consisting only of blank spaces
- [ ] Users with pseudonymized access to data (e.g. a person) can still save the respective form without getting an error (implementing the changes above will otherwise likely result in a validation error that, e.g. in a person form, first and last name are missing) AND the respective fields are unchanged afterwards (e.g. the person first name is still the same as before)

### Implementation Details

In order to fulfill the last acceptance criteria, there are two possible options that have to be tried out. In order of preference, those are:

1. Create a new interceptor that checks whether a PseudonymizableDto field is annotated with `@NotBlank` AND the Dto is `pseudonymized == true`, and if so, sets the value of this field to "CONFIDENTIAL".
2. Change the pseudonymizer to not replace String fields annotated with `@NotBlank` with an empty String, but use the String "CONFIDENTIAL" instead.

**Comment by MartinWahnschaffe** [comment]
The best way to solve this is to use the `@NotBlank` bean validation annotation.

If we use this for fields with pseudonymized data (e.g. person first or last name), we will run into problems when saving pseudonymized data, so we also have to solve this problem.

Options:

1. Use an interceptor to fill in pseudonymized data before the validation is done
2. Override the validation logic to handle the situation where a bean is pseudonymized
3. Use default values for pseudonymized fields that work with the validation (e.g. "Confidential" for strings).
4. Don't use the annotation for pseudonymized fields (strongly discouraged!)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.85.0-SNAPSHOT(304d541).
