### ISSUE TITLE
Add a new customizable enum called Pathogen [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#11840]
### Feature Description

Add a new customizable enum called "Pathogen" that can be used for pathogen tests related to environmental samples.

### Added Value/Benefit

Environmental samples are tested for pathogens that can and will differ from the diseases we have in the system. Since new pathogens can emerge, it has to be possible to create new ones on the fly without relying on developers to add them to the system. Adding pathogens as a customizable enum will therefore lay the basis of adding tested pathogens to pathogen tests, and it will make the feature future-proof.

### Acceptance Criteria

- [x] A new customizable enum type called `PATHOGEN` has been added alongside its respective class extending `CustomizableEnum`
- [x] The new customizable enum has a property called `hasDetails`
- [x] The new customizable enum has a default value `OTHER` for which hasDetails is true
- [x] Other default values (hasDetails is false for all of them):
  - Campylobacter jejuni
  - Escherichia coli
  - Salmonella spp.
  - Shigella spp.
  - Vibrio cholerae
  - Yersinia spp.
  - SARS-CoV-2
  - Adenovirus
  - Astrovirus
  - Coxsackie virus
  - Echovirus
  - Hepatitis A virus
  - Hepatitis E virus
  - Human calicivirus
  - Polio virus
  - Reovirus
  - Rotavirus
  - TT hepatitis
- [x] Default values are covered in enum.properties

### Additional Information

This issue is part of epic #11533.

**Comment by MateStrysewske** [comment]
@bernardsilenou Can you provide the default values for the Pathogen enum?

**Comment by bernardsilenou** [comment]
@MateStrysewske  We can use this list:
Campylobacter jejuni
Escherichia coli
Salmonella spp.
Shigella spp.
Vibrio cholerae
Yersinia spp.

SARS-CoV-2
Adenovirus
Astrovirus
Coxsackie virus
Echovirus
Hepatitis A virus
Hepatitis E virus
Human calicivirus
Polio virus
Reovirus
Rotavirus
TT hepatitis
Source https://doi.org/10.1016%2Fbs.aambs.2016.08.001
