### ISSUE TITLE
[Tasks] Deactivate task types for SORMAS

### ISSUE THREAD

**Issue by AliciaRaber** [SORMAS-Foundation/SORMAS-Project#11858]
### Problem Description

If you look for tasks types ins tasks there are many more tasks listed as necessary for processing Covid-Cases

### Proposed Change

Deactivate task types who are not relevant for Covid cases

### Added Value/Benefit

Task processing and search can be improved by deactivating the types in task management

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

**Comment by MateStrysewske** [comment]
@AliciaRaber Please add more details to this issue. Should these task types be deactivated by us? If so, which task types are affected? If not, is there a need to create a user interface that allows admins to decide which task types are relevant for which disease?

**Comment by AliciaRaber** [comment]
Issue can be closed.
