### ISSUE TITLE
Update SORMAS-Project GitHub links to the new URL within SORMAS-Foundation [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [SORMAS-Foundation/SORMAS-Project#11900]
### Problem Description

The SORMAS-Project repository wil be moved from the HZI-Braunschweig organization ot SORMAS-Foundation, effectively changing the URL from https://github.com/hzi-braunschweig/SORMAS-Project to https://github.com/sormas-foundation/SORMAS-Project.

### Proposed Change

Adjust all (~100) references within the repository to the new URL. The PR needs to be ready to be merged once the repository was moved.

- [ ] Update URL for links to the wiki
- [ ] ~~Use relative URL where possible (e.g. links from one readme file to another within the repository).~~
- [ ] Remove or replace gitter URLs in favour of GitHub discussions

### Added Value/Benefit

* No broken links

### Acceptance Criteria

* No more references to hzi-braunschweig n GitHub

### Implementation Details

- Search for` hzi-braunschweig` within all files of the repository
- Search for `gitter `within all files of the repository

**Comment by adinaflorea9** [comment]
Verified that the links included in https://github.com/sormas-foundation/SORMAS-Project work, and that the links associated with the backlog, epic board, investigation board, TEC team board and DEV board work.
