### ISSUE TITLE
Limited disease users should not be able to edit event groups that have at least one event of a different disease 

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11928]
### Problem Description

#11715 introduced changes so that users limited to a certain disease could no longer edit entities that they do not own of a different disease than the one they are limited by.

Event groups were not included in the respective ticket as more investigation needed to be done in order to specify the expected behavior. 

Currently. for a user limited by a certain disease, as long as one event of their disease is linked to an event group, the user can edit every aspect of that event group (archive it, de-archive it, delete and restore it, update the group name, link and unlink events). This is prohibited however if the user is restricted by a responsible jurisdiction instead of a disease one, so the behavior needs to be updated to be consistent.

### Proposed Change

The users that are limited by a disease should have similar restriction in what concerns event groups as users limited by responsible jurisdiction when they access an event group that has entities outside their jurisdiction.

### Added Value/Benefit

- consistency in what concerns behaviors related to user roles and rights in the event groups 

### Acceptance Criteria

- [x] in the 'Groups' grid the user should see the groups that have at least one event associated that has the same disease as the user's disease ~~(or at least one event owned by the user);~~
- [ ] ~~in the 'Groups' grid the user should see the groups owned by them (that they created);~~
- [x] on the event group page, if the event group does not contain any event of the disease of the user, ~~or any event owned by the user,~~ they should not be able to edit any aspect of the event group (archive, delete, update the name);
- [x] on the event group page, if the event group has at least one event of the user's disease and other events of different diseases the user should not be able to edit the event group information; they should be able to unlink only the event of their disease;
- [x] on the event group page. if the event group has only events of the same disease as the user's, then all action should be enabled (as long as the user has the respective user rights and the events are all within the user's responsible jurisdiction);
- [x] the user should still see all events related to the event group regardless of their responsible or disease jurisdiction (to be consistent with how the user sees for example entities associated with a person - on the person page, all associated entities are displayed regardless of their responsible or disease jurisdiction);
- [x] ~~unless owned by~~, the user should be forbidden from unlinking events that are outside their disease jurisdiction;
- [x] linking events to the event group should follow the same logic as is currently implemented (if the user has rights to link the event and the event is within their jurisdiction or owned by them then they should still be able to do so).

**Comment by carina29** [comment]
Tested on web local setup version 1.96.0-SNAPSHOT ([038fac](https://github.com/sormas-foundation/SORMAS-Project/commits/0383facaed6715ad0b4842e198756ab95d5e005b)).
