### ISSUE TITLE
Add bulk action progress window to "Delete" and "Restore" bulk actions [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#11931]
### Feature Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/11597 has introduced a progress window for the "Edit" bulk actions. This window needs to be applied to other bulk actions as well.

Add the progress window to the "Delete" and "Restore" bulk actions of all directories. In preparation, move all "deleteSelected" methods from the individual controllers to the DeleteRestoreController introduced in #11327.

- [x] Extract deleteAllSelectedItems method from CaseController to DeleteRestoreController and do the necessary in order to be similar with the restoreSelectedCases method from DeleteRestoreController

- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for ContactController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for EventController and do the necessary adjustments
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for SampleController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for EventParticipantController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for ImmunizationController
- [x] Create a new Controller for permanent deletion (PermanentDeleteController) and a new interface (PermanentlyDeletableFacade)
- [x] Reuse the deleteAllSelectedItems from PermanentDeleteController for VisitController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for TravelEntryController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for TaskController
- [x] Reuse the deleteAllSelectedItems from DeleteRestoreController for ExternalMessageController

### Added Value/Benefit

Consistency with the other bulk actions and increased usability because users will know how many entries have already been edited and still have to be edited, and can cancel the process at any time.

### Acceptance Criteria

- [x] All bulk methods used to delete multiple items at the same time have been moved from individual controllers to the DeleteRestoreController
- [x] All "Delete" and "Restore" bulk actions in all directories use the bulk action progress window introduced in #11597 when at least 40 entries are selected
- [x] The respective backend calls are done in batches of 20 entities when at least 40 entries are selected
- [x] The bulk action also works in the case detailed and contact detailed directories, which use different grids
- [x] Cancelling the action before it finishes leaves the selected entries that have not yet been processed still selected (as implemented in #11597)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and test-de2 using the latest version of SORMAS from the development branch - 1.87.0-SNAPSHOT(07845b7). Exceptions that are not handled in the current ticket that lead to the bulk progress bar being stuck will be treated in ticket #12257 .
