### ISSUE TITLE
Users can not link/unlink event groups to events owned by them

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11946]
### Bug Description

For a user restricted by responsible jurisdiction, if they own an event outside their jurisdiction they can not link/un-link any event group to it.

### Reproduction Steps

I:

1. With a user limited by a responsible jurisdiction, create a new event that has the responsible jurisdiction in another region and district;
2. From the 'Event groups' card on the event page, click on 'Link event group'.

Actual behavior: A red warning message appears informing the user that they can not edit the event as it is outside their jurisdiction.
![image](https://github.com/hzi-braunschweig/SORMAS-Project/assets/96909231/718cb0db-046d-4d97-a0f5-1405cfe859d7)

II:
1. With a user limited by a responsible jurisdiction create an event group;
2. With another users (Admin+NatUser) link multiple events to that event group (from different jurisdictions);
3. Log back with the user used at step 1, open the event group and click on the 'Link event' button;
4. From the list of events pick an event that is owned by the user, but that is outside their responsible jurisdiction.

Actual behavior:
An error appears and the user can not link the event.
![image](https://github.com/hzi-braunschweig/SORMAS-Project/assets/96909231/958b4f3d-c6ee-4519-a90d-f2f2627655b7)

Logs from the local machine that appear when executing scenario II:
[Event group error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11432227/Event.group.error.txt)

### Expected Behavior

The user should be able to link event groups to events owned by them.

### Affected Area(s)

Web app

### SORMAS Version

1.84.0; 1.82.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser; Configured user that is restricted by responsible jurisdiction

### Server URL

local machine; release-international

### Additional Information

If the actual behavior noted in the ticket is actually the expected one and was implemented this way on purpose, then at least the warning message that appears should be updated and changed from the red message that generally appears when an error is thrown or when a mandatory field is not filled, to a regular yellow informative note message.

**Comment by carina29** [comment]
@ChristopherRiedel We've talked with @adinaflorea9 about my findings discovered by testing the fix for this bug.
Still needs to be discussed with @MateStrysewske if the logic is meant to work with the same region but different district ( of the user and the event) or should be allowed also with different region and different district to link-unlink an eventgroup to an event and viceversa.

**Comment by adinaflorea9** [comment]
@carina29 @ChristopherRiedel I discussed with @MateStrysewske and clarified that it is ok to go ahead with the behavior requested in the ticket.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: the 'Unlink event' does not work from the event group page, it works only from the event page in the following scenario:

1. With a user restricted up to district (Region1, District1) create a couple of events that are outside the user's jurisdiction (Region2, District1) 
2. Then create an event group (the group can be created from one of the event pages);
4. From each event page, or from the event group page, link all the events from step 1 to the group from step2;
5. Then navigate to the event group page and try to unlink any of the events.
Actual behavior: The events can not be unlinked and an error appears.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/c31ee0df-93df-4936-a014-bfe049ec7fa9)
 
Expected behavior: As ling as the event group and the events are owned by the user (were created by them), the unlinking of events should be possible from the event group page, to be consistent with the fact that the unlink is successful for the same entities from the event page.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behaviors that were changed in the current implementation but worked as expected on the previously released versions:

I:
On event pages (events are outside the user's jurisdiction and not owned by them), when a user tries to unlink an event group, the message needs to be updated back to say:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/480fee06-17bd-438b-94d9-ed38b66fbcb6)

II:
On the event page  (events are outside the user's jurisdiction and not owned by them), the button to 'Link event group' is not displayed anymore. Previously, the button used to be displayed (as the user has the link event group right) and when clicked a warning message appeared:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/5edace4c-9b67-4cce-aa85-d6fcef4d4a64)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(19d39a6).

After the implementation of this ticket the button to 'Link event group' is no longer displayed on the event page when the user is not the owner of the event, and the event is outside the user's jurisdiction. This has not been specifically specified in the ticket but it was created by one of @ChristopherRiedel pull requests.

Together with @carina29  we tried multiple solutions but they would break the other flows, therefore, the ticket has been validated that instead of displaying the button and then showing a warning message in that flow (how it used to behave in previous versions) we would leave the button now shown only in that specific flow.

@markusmann-vg perhaps this could be included in the release notes so that users are aware.

**Comment by ChristopherRiedel** [comment]
@carina29 @adinaflorea9 Unfortunately, I forgot to document this in the ticket, but the fact that the button is not displayed was explicitly requested by @MateStrysewske, as this is more in line with the behavior in other places. Also, if we do display a message, we should display it as a Warning and not as an Error, since no error has occurred.

**Comment by carina29** [comment]
All the PRs were merged for this ticket, so I'll close this ticket.
