### ISSUE TITLE
Avoid packaged jars in apps [3]

### ISSUE THREAD

**Issue by StefanKock** [SORMAS-Foundation/SORMAS-Project#11963]
### Problem Description

Deploying SORMAS (or starting the Payara Domain with already deployed apps) takes often more than 90s.

#11902 showed that the deployment time of `sormas-ear.ear` can be improved by reducing the jars that are bundled in the the ear file.

### Proposed Change

Deploy as much dependencies as possible as serverlibs, don't use scope `compile` in `sormas-backend`, `sormas-ui` and `sormas-rest`

### Added Value/Benefit

Faster deployment time means less downtime when updating SORMAS and less waiting while developing SORMAS.

### Acceptance Criteria

- [x] Keep `sormas-api` as compile dependency.
- [x] All other compile dependencies are resolved as serverlib or was decided to stay as compile dependency.
- [x] Deployment time before and after is measured and documented.

### Implementation Details

1. Check that all current compile dependencies are really used.
    - List swagger dependencies only for `sormas-rest` (check that's not used by other active code).
2. Exclude dependencies that are already provided as glassfish/module. Examples:
    - javax.inject
    - jaxb-api ?
3. Keep Vaadin dependencies inside `sormas-ui`
4. Keep `sormas-api` as compile dependency.

### Additional Information

**Caution**: 
1. All developers need to update the libs in the Payara domain (Ant -> `sormas-base/build.xml`-> `deploy-serverlibs`)
2. After this ticket is merged, a standard hotfix procedure is maybe not an option due to a lot of POM changes that might result to pesky merge conflicts.

<details>
<summary>Benchmark</summary>

| Phase           | Run 1         | Run 6      | Run 7       | Comment     |
| ------------- | -----------:| ----------:| ----------:| ------------- |
| 1                  |            41s |            8s |          16s | No log entries |
| 2                  |            13s |          13s |          13s | First log entry until `WELD-000900` | 
| 3                  |            36s |          25s |          24s | End of phase 2 until `sormas-ear was successfully deployed` |
| Success time |            81s |           41s |         42s | Reported in `sormas-ear was successfully deployed` message  |
| Total time     |            90s |           46s |         53s | Total time of all phases   |
| Xmx             |       1024m |       1024m |  1024m |   |
| Deployment | exploded    | autodeploy, no ear libs | autodeploy, reduced ear libs   |  |
| Domain startup |      10s  |           18s | 22s  | More domain libs takes more domain startup time |

</details>

**Comment by StefanKock** [comment]
Increased estimation based on spent time and effort to fix problems.

**Comment by StefanKock** [comment]
Known Problem: Running deploy-serverlibs with Maven 3.8.6 (with Zulu 11) ran into such exception:
```
sormas-base\build.xml:53: Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'commons-io:commons-io:jar': Invalid JDK version in profile 'jdk9-compiler': Unbounded range: [9 for project org.apache.commons:commons-parent
```

**Comment by StefanKock** [comment]
Found Problem: Set all dependencies on `provided` scope in `sormas-api` now causes that transitive dependencies are not available in the classpath when using `sormas-api`. It's not desirable to replicate all dependencies for example in `sormas-backend`, if the dependencies are not used there directly. Idea: List all dependencies in `sormas-api` as `compile` to keep them in the classpath.

**Comment by leventegal-she** [comment]
Causes issue in the demis adapter #12215

**Comment by StefanKock** [comment]
> Causes issue in the demis adapter #12215

hapi-fhir-client was not part of the SORMAS deployment before, and is not now (checked in serverlibs, sormas-ui and sormas-ear).

**Comment by StefanKock** [comment]
See https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12215#issuecomment-1623211547 : Keep `hapi-fhir` as compile dependency.
