### ISSUE TITLE
Inconsistent display of samples with different associations in sample dashboard map

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12000]
### Bug Description

The map on the sample dashboard, by default, displays samples associated to cases, contacts, and event participants, and allows the user to deselect those associations as well to only display samples associated to one or two of them. On https://release-international.sormas.netzlink.com/sormas-ui/#!dashboard/samples, deselecting cases will suddenly bring up e.g. event participant samples in some places where case samples were shown before; this would probably and theoretically make sense because if multiple samples are shown in the same location, case samples should have prevalence, i.e. the bundled sample icon should be red. However, when clicking on the bundled icon with cases still selected, no event participant sample appears.

### Reproduction Steps

1. Open the sample dashboard on https://release-international.sormas.netzlink.com/sormas-ui/#!dashboard/samples
2. Filter by samples of the whole year (2023)
3. Zoom out a bit; keep the map e.g. a bit to the right of Göttingen
4. Deselect the cases association filter
5. Observe that most sample markers disappear, while some change colors
6. Select the cases association filter again and click on one of the red markers that appears in place of the yellow or blue markers
7. Observe that the sub markers appearing are all red

### Expected Behavior

The contact and event participant filters should still be shown when clicking the cluster marker.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.83.1

### Android version/Browser

Chrome

### User Role(s)

Admin & National User

### Server URL

https://release-international.sormas.netzlink.com/sormas-ui/#!dashboard/samples

### Additional Information

Screen capture of the issue: https://github.com/hzi-braunschweig/SORMAS-Project/assets/12996724/a09d9e85-a8d8-4a0a-8e46-1247e926bead

**Comment by leventegal-she** [comment]
This happens because the samples are linked to cases, contacts and event participants at the same time. By default those ones are shown as case sample. If the case layer is removed then the samples are displayed as contact or event participant depending on what other associated object they have.

**Comment by MateStrysewske** [comment]
Ah okay, then that's probably fine! Thanks for the clarification!
