### ISSUE TITLE
Do not display bulk actions associated with rights that the users do not have

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12015]
### Problem Description

Currently, the expected behavior in regards to the display of the bulk actions associated with rights that the logged in users do not have is met only for the 'Messages' directory - bulk action 'Delete', 'Upload quarantine documents' in each directory, and the 'Delete/restore', 'Archive/De-archive' in the 'Events' directory and 'Event participants' tabs where if the respective rights are missing the associated actions are not displayed in the 'Bulk actions' dropdowns.

There are 2 perspectives that need to be addressed:
1. where the actions associated with the missing rights are shown in the dropdown and the actions are successful:
**- Cases directory - edit bulk actions:** 
   If the user has UserRight.CASE_EDIT the bulk actions dropdown will contain the "Edit" functionality but the actions inside the bulk edit popup should be limited based on the specific case edit rights ( same logic as there is is place when editing a case in single mode). When the user does not have a specific edit right, the checkbox should be read only.
The following rights are necessary for the specific edit actions from "Edit cases" popup window:

- [x] "Change Disease" -> CASE_CHANGE_DISEASE
- [x] "Change case classification" -> CASE_CLASSIFY
- [x] "Change investigation status" -> CASE_INVESTIGATE
- [x] "Change case outcome" -> CASE_CLASSIFY
- [x] "Change facility" -> CASE_TRANSFER

**Note:**  There is no need to set the following checkboxes to readOnly based on rights:
 - "Change case surveillance officer"  (will depend on CASE_EDIT right) 
 - "Change share with reporting tool"
 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/fb66395b-3a11-439b-b1dc-8fdfd3a30dd5)

2. where the actions associated with the missing rights are shown and an error message stops the user from completing the action:
- Cases directory - bulk actions: edit (change surveillance officer or all edit actions if the full set of edit existing cases rights are missing), link event (link event requires EVENT_CREATE and EVENTPARTICIPANT_CREATE rights + EVENT_SURVEILLANCE feature configuration);
- Contacts directory -link to event (requires EVENT_CREATE and EVENTPARTICIPANT_CREATE rights + EVENT_SURVEILLANCE feature configuration);
- Event participants tab - bulk actions: create contacts (requires CONTACT_CREATE right);
- Samples directory - bulk actions: delete/restore (requires SAMPLE_DELETE right);

### Proposed Change

The bulk actions displayed for the user should all be consistently displayed based on the rights of the user logged in, as we currently do for part of the delete/restore, archive/de-archive, and upload documents actions that are not displayed in some bulk actions dropdowns when the respective rights are missing.

### Added Value/Benefit

Consistency in regards to the display based on the user's rights and the display of less error messages caused by displaying actions associated with missing rights.

### Acceptance Criteria

- [x] in the dropdown of 'Bulk actions' the actions displayed should be based on the rights of the user - i.e. if a certain right is missing the action associated with it should not be displayed;
- [x] for the edit actions that contain multiple 'sub-actions' - if only some if those sub-actions are missing, the 'Edit' action should still be displayed and contain only those sub-actions that the user has rights for ( when the user does not have the proper right, the checkboxes should be readonly in the "Edit cases" popup)

Directories to be covered:
- [x] cases
- [x] contacts
- [x] event participants
- [x] samples

### Additional Information

An extensive explanation on which actions are dependent on which rights was written and can be provided to help with the development of the issue.

The display of the bulk edit mode across directories where it is implemented will be addressed by #11881

**Comment by richardbartha** [comment]
Tested on local env version 1.95.1
