### ISSUE TITLE
Add an environment list for the mobile app [3]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12025]
### Feature Description

After an Environment entity has been created in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11796 as part of epic https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11533, a list that contains those entities is now required for the mobile app.

### Added Value/Benefit

Users will be able to see and filter a list of the environment entities created in the system.

### Acceptance Criteria

- [x] A new menu entry called "Environments" has been added with an appropriate icon (see the mockup below for inspiration); the entry has been placed directly below "Samples"
- [x] The entry is only visible when the feature added in #11572 is enabled and the user has the `ENVIRONMENT_VIEW` user right
- [x] The items in the list includes the following information:
  - ID (= the UUID of the environment entity)
  - External ID
  - Name
  - Environment media
  - GPS lat
  - GPS lon
- [x] The list is automatically sorted by change date
- [x] The user can use the hovering button in the bottom right to filter the list by investigation status

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest SORMAS version from the development branch - 1.87.0-SNAPSHOT(6946648).

**Comment by MateStrysewske** [comment]
@sergiupacurariu The update script you've written for the Android database does not run through because you didn't increase the DATABASE_VERSION at the top. 

I've fixed that locally, but the script also doesn't execute successfully and the app crashes:

```
java.lang.RuntimeException: Unable to instantiate application de.symeda.sormas.app.SormasApplication package de.symeda.sormas.app.debug: java.lang.RuntimeException: Database upgrade failed for version 345: Can't find a no-arg constructor for class de.symeda.sormas.app.backend.environment.EnvironmentDao
```

**Comment by sergiupacurariu** [comment]
@MateStrysewske database version committed to development

**Comment by MateStrysewske** [comment]
Script is not fixed

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.87.0-SNAPSHOT(8090ceb).
