### ISSUE TITLE
Add the disease variant to the edit forms of cases in Bulk action [1]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#12028]
### Problem Description

Currently in Bulk mode you are not able to select a number of cases and assign a disease variant to the selected ones. It's only possible to assign a disease or change other data

### Proposed Change

Add a dropdown to select a disease variant if there are any for the selected disease so it can be selected and changed in bulk mode.

### Added Value/Benefit

Saves time as you don't have to go into every case to add the variant.

### Acceptance Criteria

- [ ] The bulk edit form contains a checkbox "Change disease variant" with a disease variant field and a disease variant details field
- [ ] The disease variant field is shown when "Change disease" has been selected and a disease that has disease variants on the system has been selected
- [ ] The disease variant details field is shown when a disease variant with the "hasDetails" property set to true has been selected
- [ ] Saving the bulk data form updates the disease variant for all selected cases

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ and https://test-de1.sormas.netzlink.com/ using SORMAS version 1.87.0-SNAPSHOT(ebf4ca8).

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using the latest version of SORMAS 1.87.0-SNAPSHOT(a34096b).
