### ISSUE TITLE
Demis messages cannot be downloaded

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12040]
### Bug Description

As user when trying to download a message from Demis, from the Messages directory, an error appears and the file is not downloaded

### Reproduction Steps

1.
2.
...

### Affected Area(s)

Web app

### SORMAS Version

1.84.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

### Server URL

https://test1402.sormas.netzlink.com/

### Additional Information

[DemisDownloadError.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11652553/DemisDownloadError.txt)

**Comment by abrudanancuta** [comment]
@MartinWahnschaffe had a look about the issue:

sormas-demis-adapter is using jsoup-1.14.2 as compile dependency, which still has the missing function (deprecated though) https://github.com/jhy/jsoup/blob/jsoup-1.14.2/src/main/java/org/jsoup/Jsoup.java#L316
sormas-base is using jsoup-1.15.3 sind 1.84.0 (see #11032) which no longer has the method
https://github.com/jhy/jsoup/blob/jsoup-1.15.3/src/main/java/org/jsoup/Jsoup.java#L316

For some reason the demis adapter seems to be taking the jsoup version from payara instead of it's own compile dependency.

jsoup/Jsoup.java at jsoup-1.14.2 · jhy/jsoup

jsoup: the Java HTML parser, built for HTML editing, cleaning, scraping, and XSS safety. - jsoup/Jsoup.java at jsoup-1.14.2 · jhy/jsoup

I'd suggest to change jsoup in sormas-demis-adapter to provided and not overriding the version that is provided in sormas-api which is used in sormas-demis adapter. This of course also means that the deprecated method call has to be replaced.

**Comment by leventegal-she** [comment]
Closing this because it has nothing to do in SORMAS
