### ISSUE TITLE
Performance issues in merge views caused by filtering changes

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12061]
### Bug Description

#11872 has introduced changes to the filters of the queries that retrieve duplicate cases and contacts for the merge views. Those changes lead to significant performance issues because they've changed the way the queries have to be built.

### Reproduction Steps

On a system with a significant amount of cases/contacts in the database, enter the merge views and observe the performance.

### Expected Behavior

The changes to the filters have to be reverted; since this will lead to the bug fixed in #11872 reappearing, the solution is probably to get rid of the creation date filters that ensure that we don't have duplicate data in the results, and then remove the duplicates from the result manually.

### Affected Area(s)

Web app

### SORMAS Version

1.84.0-SNAPSHOT

### Android version/Browser

Chrome

### User Role(s)

Admin and National User

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.85.0-SNAPSHOT(a306455).
