### ISSUE TITLE
Improve duplicate removal from merge result list [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12068]
### Problem Description

#12061 removed the creation date filtering logic from the backend methods to retrieve duplicate cases and contacts because it lead to filtering not working on the second case/contact of a pair. However, this required the introduction of a mechanism to manually filter out duplicate pairs after the query has been performed (because that was the exact purpose of the creation date filtering logic before). The mechanism introduced should be further improved in terms of performance and consistency as it's a) not very performant and b) leads to the result list only being half as long as the maximum amount of results specified on the merge view.

### Proposed Change

Increase the performance of the logic that removes duplicate pairs from the result, and ensure that the method is capable of returning the amount of results specified on the merge view.

### Added Value/Benefit

Better performance and consistency with the user input.

### Acceptance Criteria

- [x] The current usage of `anyMatch` has been replaced with an additional HashSet<AbstractMap.SimpleImmutableEntry<Long,Long>> that is filled while filling the resultList and then checked for duplication with a contains call
- [x] It's ensured that the result list can have as many entries as specified by the limit in the merge view AFTER the duplicates have been removed; this can probably be achieved by doubling the limit that's put into the query
- [x] Reduce the result list to the actual limit size afterwards (because there are more results returned)

**Comment by MateStrysewske** [comment]
There are still significant performance issues because of the query changes. We'll have to sort out how to deal with those. Results will be documented here.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using SORMAS version 1.87.0-SNAPSHOT(6584f3d) and https://test-de2.sormas.netzlink.com/ using SORMAS version 1.87.0-SNAPSHOT(118d04a).
