### ISSUE TITLE
Replace Ant build scripts [3]

### ISSUE THREAD

**Issue by StefanKock** [SORMAS-Foundation/SORMAS-Project#12074]
### Problem Description

We currently use `Ant` with `maven-ant-tasks` to easily build SORMAS within the IDE and deploy changes to the DEV instance of SORMAS on the local system.

With #11963 we noticed very directly that the Ant tooling runs into incompatibilities with newer Maven versions and plugins or dependencies relying on newer JDKs.

Additionally, it is a bit odd for a developer to need to have a running Ant & Maven installed as command line tool, when the IDE provides also Maven.

### Proposed Solution

1. Replace the features of the Ant targets/functions with means directly with Maven, usable in IDEs Eclipse and IntelliJ. Recreate the build and copy actions in Ant with Maven and link it to the package phase.
2. Keep it as usable as possible for developers to maintain the DEV instance: Provide shell scripts in `sormas-base/dev` (or minimum a documentation [here](https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md)) of often used Maven commands so that every developer can create Run Configurations in the IDE.
3. Remove all Ant functionality and documentation, remove `sormas-base/build`.

### Acceptance criteria

- Keep the `collect-all` functionality since it's used within the CI pipeline. 
   - [x] Adjust jobs `sormas-Build` in Jenkins when the changes are merged.
   - [x] Adjust job `sormas-Release` in Jenkins before the release happens (don't change early to keep hotfix for 1.85.x working until then).

### Additional Information

Caution for developers: The localized `sormas-base/build.properties` needs to be replaced by `sormas-base/dev.env` with `GLASSFISH_DOMAIN_ROOT` parameter set. Details in the [IDE setup](https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md#step-5-install-and-configure-your-ide).

- Currently used: Ant and [maven-ant-tasks](https://maven.apache.org/ant-tasks/index.html)
- No drop-in replacement is [maven-resolver-ant-tasks](https://maven.apache.org/resolver-ant-tasks/). I already found out that the _dependencies_ feature lacks many of the parameters we currently use with our patched maven-ant-tasks.

**Comment by MartinWahnschaffe** [comment]
Current ant tasks in sormas-base and children that may need to be replaced.

### install-with-app
Includes sormas-app as a module in sormas-base. Is realised via a maven profile. 

* From my point of view we can simply drop the ant task. It can easily be controlled via the Maven tool window in IntelliJ or the command line.
![grafik](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/23217632/7ab80add-31fb-4945-9deb-59d83a227be9)

### generate-api-doc
From my understanding this only calls I18nConstantGenerator to generate java classes with constants for i18n constants.

* Simply drop the ant task. The guides that we have, ask the developer to manually execute the generator anyway (e.g. https://github.com/SORMAS-Foundation/SORMAS-Project/wiki/Adding-a-New-Field-to-an-Entity#adding-the-field-to-the-sormas-api)
* OR: Use the [exec-maven-plugin](https://www.baeldung.com/maven-java-main-method) and define an execution to run the generator. We could bind this to a phase, but this may negatively interact with CI environments when the files are not up to date. Manually calling it from the IDE in IntelliJ does not have a nice way of selecting the exection (see https://youtrack.jetbrains.com/issue/IDEA-181235/Support-maven-execution-id-when-selecting-a-plugin-to-run).
* OR: Provide a run configuration for intelliJ

### deploy-serverlibs
Collects and copies dependencies using maven via antlib.

* Use a maven execution to copy the files https://www.baeldung.com/maven-copy-files. Not sure how to provide the location for a local system.

### collect-all
Copies server setup scripts and configurations to a separate setup folder. Copies all deployable modules and serverlibs to a separate deploy folder. Copies openapi documentation to the deploy folder.

* Whatever solution is used for deploy-serverlibs probably also works for this task.

**Comment by StefanKock** [comment]
Configure and test integration with Jenkins

**Comment by StefanKock** [comment]
Changing the release job is still to do

**Comment by MartinWahnschaffe** [comment]
@StefanKock Two findings:
1. I have set my MVN_BIN to `"C:\\Program Files\\apache-maven-3.9.0\\bin\\mvn"`, but received the following error:
   > collect-serverlibs.sh: line 31: C:\Program: No such file or directory

   Changing `$MVN_BIN` to `"$MVN_BIN"` fixes this problem.
2. https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md#intellij says
   > Execute the dev/build.sh and dev/deploy-serverlibs.sh scripts

   * Running build.sh is not needed, as "Run mvn install on the sormas-base project" is part of the steps to be done before.
   * It should be mentioned to the sh file needs to be run with git bash and that a run configuration can be created, by setting the interpreter path to the git bash executable.
![grafik](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/23217632/79c4c508-d586-488b-aefb-c69cfd85a47f)

**Comment by StefanKock** [comment]
I updated now also the sormas-Release job since 1.85.0 was approved recently, and a hotfix one day before the release of 1.86.0 is now unlikely.

Previous config:
![grafik](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/24678567/545c0481-6485-4f6f-bab7-7236b2b32d83)
