### ISSUE TITLE
Add DELETE rights required for MERGE rights

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#12079]
### Problem Description

Currently merging cases and contacts without the DELETE right results in a case/contact merged but the other one not deleted because of the missing right. Also picking on is not working without that right

### Proposed Change

- [ ] add `*_DELETE` right as required for `*_MEREGE` rights in `UserRights`
- [ ] add `*_DELETE` to all existing roles that have `*_MEREGE` right

### Added Value/Benefit

Helps to avoid half done merges because of user right misconfiguration

### Acceptance Criteria

For both case and contact:
- [ ] All existing roles with MERGE right have also DELETE right
- [ ] DELETE right gets automatically checked when checking MERGE right 
- [ ] It's not possible to save a user role with MERGE right and no DELETE right checked

**Comment by leventegal-she** [comment]
Looks like I overlooked what happens. 
The delete case/contact after merge should be allowed with only MERGE right but the delete doesn't work if the case/contact is outside the user's jurisdiction so the merge ends with a merged case/contact and the duplicate kept.

The merge should be rolled back if deleting the other object is rejected.

**Comment by adinaflorea9** [comment]
Ticket #12103 will cover the issue and what @leventegal-she described in the comment above. Closing the current ticket as discarded.
