### ISSUE TITLE
"Null" text appears as additional information below Samples card on Persons Page

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12081]
### Bug Description

Is missing the additional information below the Samples card on Persons Page.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/d221c841-7b7f-467a-821d-3f65266fa464)

In case of other entities, a message corresponding to the specific entity will be displayed:
Creating a new sample will discard all unsaved changes made to this case/contact/event participant

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/20b228c6-d3d8-419e-9ce4-43e8faaceef3)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/a2ad4dfd-0ed1-4aa7-a957-14ae918b66e7)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/9be53dcd-6b92-4ac0-a777-35319a87759a)

### Reproduction Steps

1. Go to Persons directory and open a person
2. Check the Samples card and the text below
...

### Expected Behavior
It was agreed with @MateStrysewske that the creation of a new string for Persons does not make sense since the creation of samples is not possible from Persons Page ( only from cases, contacts or event participants).
In this scenario the hint will be hidden when the infoText remains null.

### Affected Area(s)

Web app

### SORMAS Version

1.84

### Android version/Browser

Chrome

### User Role(s)

National User

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.85.0-SNAPSHOT(a306455) - the test on the person page when opened from the 'Persons' directory is no longer displayed if no sample is associated with the person's entities.
