### ISSUE TITLE
S2S -Person fields are not read-only when is not owned by the Health department

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12088]
### Bug Description
The fields on the person page (when entered from the 'Persons' directory) are enabled even though the respective system has the person and the entities associated only 'To view', and the ownership belongs to another system.

### Reproduction Steps

1. As Admin + NatUser send a case without ownership to health department B
2. As Admin + NatUser accept case on Health department B
3. From the new accepted case get the UUID of the Person from the Case Person tab
4. Open Person directory and search by the UUID above
5. Open the person from the search
6. Look at the fields on the person page.

### Expected Behavior

The fields on the person page should be read-only because the case and person are not owned by Health department B. The cards on the person page should remain enabled.

### Affected Area(s)

Web app

### SORMAS Version

1.85.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de1.sormas.netzlink.com/ and https://test-de2.sormas.netzlink.com/ using SORMAS version 1.86.0-SNAPSHOT(d57db01).
