### ISSUE TITLE
Bulk action progress bar displays on multiple languages the messages

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12080]
### Bug Description

In this ticket https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11597 was introduced a progress bar for Bulk actions -> Edit.
The messages on the progress bar window are displayed simultaneously on multiple languages:

- When english is selected from user settings:  english and german messages are mixed in the modal window
- When french is selected: english, german and french languages are mixed in the modal window
- On german user settings, all the messages are displayed correctly in german
- other languages: were not tested

![before](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/fb04723a-9c1e-4de7-877b-cf01df7dea0c)
![BulkOperation_Edit_cases1](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/3db11d7e-cd24-4e02-9a34-77d320b566c7)
![case2](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/5505be6d-e268-464c-bd5f-a36fca1caa37)

![After](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/51a6d875-6bb2-4869-9dc8-ee4a62d40264)
![case3](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/444b690c-dcb4-4e68-9035-c01436e720ce)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/5f6909a5-815e-45cf-9b0b-002cbd4b3834)

**NOTE:** Some of the language changes appear after the first batch is processed ( Completed, Successful, Skipped labels will be changed for the german labels)

### Reproduction Steps

1. Go to the Cases screen and enter bulk edit mode
2.  Select at least 40 entities and click Edit from bulk actions dropdown
3.  Check the message and the language after the processing of the first batch
4.  Check the message from the end of the processing
5. Try another edit and stop the process - check the language of the message

For french language translations, strings_fr-FR.properties does not contain the french translations for infoBulkProcess, infoBulkProcessFinished, infoBulkProcessFinishedWithSkips, infoBulkProcessCancelled and infoBulkUnresponsiveWindowHint.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/2e0cb27e-8d30-4a15-9527-bf21f423cd32)

### Expected Behavior

All the messages should be on the language selected by the user from user settings.
It looks like is treating the german language as the default one ( country.locale is german) after the processing of the first batch ( 20 entities).

### Affected Area(s)

Web app

### SORMAS Version

1.85

### Android version/Browser

Chrome

### User Role(s)

Configured user

### Server URL

test-de1

### Additional Information

The problem is reproducible on local environment ( country.locale=de-DE and country.name = DE in sormas. properties) and on test-de1 too.
On other test instances it was not tested yet.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(a8aaac6).
