### ISSUE TITLE
False requirement field for Point of Entry 

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12084]
### Problem Description

The false requirement field message is poopup when in field POINT OF ENTRY "Voreingestellter Flughafen" or "Voreingestellter Hafen" are chosen. This behavior  occurs when new Case or a new Travel Entry are created. Below attached screenshots:

Error popup message:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/06871a9c-3411-415a-884f-18ef6cfa3ed7)

False required field:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/00527478-4b76-4057-8e02-6ae51e46f8e1)

### Reproduction Steps

1.Click on Cases on Navbar
2.Click on New Case Button
3.Chose POINT OF ENTRY in Case Origin
4.Check box "Place of stay of this case differs from its responsible jurisdiction" 
5.Fill all requirement fields
6.Chose  "Voreingestellter Hafen" or "Voreingestellter Flughafen" in POINT OF ENTRY combobox
7.Click in SAVE button
..

### Expected Behavior

1)No popup message about "Please check the input data" "Point of entry name & description is required" 
2)The new Case should be created.

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.85.0-SNAPSHOT (304d541)

### Android version/Browser

Chrome

### User Role(s)

National User

### Server URL

https://test-auto.sormas.netzlink.com

**Comment by ChristopherRiedel** [comment]
The problem is reproducible for me, but not traceable. I have tried and debugged a lot.
The last action in which the "required" status of the field is touched before saving is CaseCreateForm line 629. Here required = false is set. Nevertheless, the field is then "requried" again when evaluating before saving.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(19d39a6).
