### ISSUE TITLE
Avoid usage of commons-collections v3

### ISSUE THREAD

**Issue by StefanKock** [SORMAS-Foundation/SORMAS-Project#12095]
### Problem Description

`commons-collections` version 3 was replaced years ago by `commons-collections4`, but is still used by our code since it is in the classpath (needed as transitive dependency).

### Proposed Change

1. Switch all usage to `commons-collections4`.
2. Prevent usage with ArchUnit (`sormas-backend`, `sormas-rest`, `sormas-ui`).

Refine: How to deal with it in `sormas-app`?

### Added Value/Benefit

Use a dependency that is still maintained.

### Acceptance Criteria

- [x] `commons-collections` is not used by our code anymore (search for _"import org.apache.commons.collections."_)
- [x] `commons-collections` v3 is still remain in classpath as transitive dependency.

**Comment by richardbartha** [comment]
No end user testing possible, just checked committed changes in source code
