### ISSUE TITLE
The external message is not configured properly

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12096]
### Problem Description

When I click on fetch button in Messages directory I get this message:
"The external message adapter is not configured properly"

### Reproduction Steps

1.Click on Messages button from navbar
2.Click FETCH MESSAGES button
3.The message is popup "The external message adapter is not configured properly"

Screenshots:
<img width="212" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/58c58753-915d-4e79-83d8-5587fa9c16e9">

### Expected Behavior

After click on a FETCH MESSAGES button we should get information something like this "The no message to download"
instead of error message "The external message adapter is not configured properly"

### Affected Area(s)

Web app

### SORMAS Version

1.86.0-SNAPSHOT (cde54ba)

### Android version/Browser

Google Chrome

### User Role(s)

Admin

### Server URL

https://test-de2.sormas.netzlink.com/

**Comment by adinaflorea9** [comment]
@mk-sgent the dev team already made the new release for the external message adapter but this has not yet been properly installed on the testing environment. 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/4059e7f1-75e6-4e94-aa4e-8c62ab3f9ff6)

For this you would have to open a ticket directly with Netzlink to look into configuring this on the testing instances requested by you.

Closing the current ticket as it is not in scope of the dev team.
