### ISSUE TITLE
[Person merge] Merging or picking persons randomly leads to an error

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12218]
### Bug Description

When trying to merge or pick person with a regular Admin+NatUser the merge or pick sometimes results in an error. I could not determine what causes this as sometimes with similar persons the error is not reproducible and with other it is.

### Reproduction Steps

1. Logged in with an Adnim+NatUser enter the bulk edit mode in the 'Persons' directory;
2. Randomly select persons for the merge;
3. In the window 'Pick or merge persons' select one of the persons and click 'Pick' or 'Merge';
4. In the 'Pick or merge person confirmation' click 'Confirm'.
Actual behavior: an error appears.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/fc7adffe-3184-4414-a48c-f8cc8f83a3dc)

Logs from the local machine:
[merge persons error .txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11891634/merge.persons.error.txt)

### Expected Behavior

No error should appear and the merge or pick action should be successful.

### Affected Area(s)

Web app

### SORMAS Version

1.86.0-SNAPSHOT(8988ace)

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine

**Comment by MateStrysewske** [comment]
Fixed this by actually creating a new location entity when merging persons instead of just copying the location over to the lead person (because this leads to the same location being used twice). It's possible that this will still not work for existing persons that already have been merged with others (because in this case, locations might already be referred twice in the database).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(19d39a6).

An error still appears for 4 persons from my DB - this could not so far be reproduced with other persons or addresses associated with other persons and the investigation will be treated in a separate ticket.
