### ISSUE TITLE
Add an edit form for environment samples in web app [5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12235]
### Feature Description

#11721 has introduced a new environment sample entity. Create and edit forms are needed for users to be able to create new environment samples in the web app.

### Added Value/Benefit

Users can create environment samples required for one health surveillance.

### Acceptance Criteria

- [x] An edit form (also used for creation) for environment samples has been added with the following fields and headings:
  - Heading: "Laboratory sample"
    - UUID (read only; caption: Sample ID)
    - Environment name (read only)
    - Read-only label with the report date and reporting user (as already implemented for samples)
    - Date of sampling (required)
    - Sample material (required)
    - Specify sample material (if sample material == other, required in this case)
    - Field sample ID
  - Heading: Sample measurements
    - Volume (in mL)
    - Turbidity (in NTU)
    - Temperature (in °C) - pre-fill with values from -20 to +100 °C in steps of 0.1 (see symptoms for reference)
    - Total chlorine residue (mg/L)
    - pH value 
    - Weather condition at time of sampling - display each possible enum value as an individual checkbox
    - Heavy rain in the last 24 hours before sampling?
  - Heading: "Location of sampling site"
    - Location form (region, district, gps lat and gps lon required; location of the environment for which the sample is created is copied over and form is disabled by default)
    - Checkbox "Location differs from environment location" - if checked, clear and enable the location form; if unchecked, disable it and fill it with the environment location again; show this checkbox ABOVE the location form
  - Heading: "Sample management"
    - Laboratory - required
    - Laboratory details (if generic laboratory has been selected)
    - Subheading: "Requested pathogens to be tested"
    - Checkboxes for each pathogen in the system, similar to the requested pathogen tests for samples
    - Other requested pathogens to be tested
    - Checkbox "Sent/dispatched"
    - Dispatch date and dispatch details only if checkbox is checked
    - Checkbox "Received"
    - Receival date and lab sample ID only if checkbox is checked
    - Specimen condition
    - General comment
- [x] Environment sample entries in the directory can be opened and bring up the edit form
- [x] A button to create new environment samples has been added to the directory
- [x] Ensure that creating an environment sample with the location of an environment does not actually use the same location entity, but just copies over the values
- [x] Ensure that the form is properly read-only for users without the necessary jurisdiction and who are not the reporting users
- [x] Users with the `ENVIRONMENT_SAMPLE_EDIT_DISPATCH` user right can edit everything up until the "Received" checkbox; users with the `ENVIRONMENT_SAMPLE_EDIT_RECEIVAL` user right can only edit fields starting with the "Received" checkbox; The general comment field can be edited by everyone; users with both rights can edit everything
- [x] For creation forms, all users can edit everything up until the "Received" checkbox, but only users with the EDIT_RECEIVAL right can edit the receival information

### Mockups

![env_sample](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/12996724/d474c791-e88f-444e-85fd-55cd81a84ba0)

**Comment by leventegal-she** [comment]
> GPS coordinates need to be mandatory

The fields are mandatory

**Comment by MateStrysewske** [comment]
@leventegal-she Yeah, just realised that these are the wrong issues, they need to be mandatory for environments as well. Will open a new issue and work on it.

**Comment by adinaflorea9** [comment]
I am reopening the issue due to the following:
1. no date validations between the 'Date of sampling' and the 'Dispatchment date', 'Receival date' and the 'Report date' of the pathogen test.  We have these date validations for regular samples - the 'Sampling date' can not be after the 'Dispatchment date', 'Receival date' or the 'Report date' of the pathogen test.

2. Checkbox "Location differs from environment location" - if checked, clear and enable the location form; if unchecked, disable it and fill it with the environment location again; show this checkbox ABOVE the location form - checkbox is missing in the creation form of environment samples and in the edit form.

3. The heading in the creation form of new environment samples says 'Create new task' - it should say 'Create new environment sample'.

**Comment by leventegal-she** [comment]
> I am reopening the issue due to the following:
> 
> 1. no date validations between the 'Date of sampling' and the 'Dispatchment date', 'Receival date' and the 'Report date' of the pathogen test.  We have these date validations for regular samples - the 'Sampling date' can not be after the 'Dispatchment date', 'Receival date' or the 'Report date' of the pathogen test.

These validations were not specified by this issue so needs a new feature request to be refined and estimated

> 2. Checkbox "Location differs from environment location" - if checked, clear and enable the location form; if unchecked, disable it and fill it with the environment location again; show this checkbox ABOVE the location form - checkbox is missing in the creation form of environment samples and in the edit form.

There was a discussion about that checkbox and has decided to not implement the checkbox

> 3. The heading in the creation form of new environment samples says 'Create new task' - it should say 'Create new environment sample'.

Will be fixed soon

**Comment by adinaflorea9** [comment]
Thank you, @leventegal-she!

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(a0cc3be).
