### ISSUE TITLE
Handle the exceptions and messages for the bulk processes [5]

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12257]
### Problem Description

In https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11597 the bulk progress bar was introduced (for entities < 40 entities) for bulk editing.
For the following operations the happy flow and only some exceptions and error messages were handled:
- archive/dearchive (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11463)
- delete/restore (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11931) and bulk actions
- other bulk operation (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11464)

The following were handled:
For < 40 selected entities:
- if the user wants to delete an already shared entity (case/event) with Survnet but the call to Survnet fails in case of deleting the entity/entities.
 - an error notification (general exception in UI) will be shown if at least one from the selected entities was sent to Survnet and the Survnet communication is failing=> none of the selected entries will be deleted
- if in the selected list of External messages there is at least one in "PROCESSED" status:
the whole deletion will be aborted and a message will be displayed
- if ineligible events are selected for deletion, a message will appear and those events will be skipped from deletion

For > 40 selected entities:
- the ineligible entities( example events) will not be processed for delete/restore ( a message will be given if all the selected entities are ineligible or if some of the selected entities are ineligible) 

### Proposed Change

All the possible exceptions should be handled and proper messages should be displayed in the UI.
The handling should be done generically in BulkOperationHandler, for the missing scenarios.

### Added Value/Benefit

- filtering the not eligible elements before processing them
- handling all the exceptions and displaying meaningful messages(with the proper reason) for the users
- preserving all the old functionalities from past ( before the bulk progress bar was introduced)
- solving the "blocked progress bar problem" which happens when more than 40 entities are selected and not all of the entities can be processed succesfully

### Acceptance Criteria

Acceptance criteria:
**For < 40 entities:**

- [x] If multiple entries are selected for delete and some of the entries can not be deleted because of the communication with Survnet the following modal window should be displayed adapted to the entity ( case/event) and the eligible entities which do not need Survnet communication, should be deleted:

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/257b74aa-cc8a-45d3-9ec2-1d72f32fde63)

- [x]  the above mentioned modal window should appear also for archive/dearchive/sending to reporting tool if the communication is failing with Survnet

- [x]  if for any other bulk actions (except for delete) can happen that the items are ineligible, should be handled with a similar modal window with a proper message (the messages from DeleteRestoreMessages can be used as reference )

- [x]  if none of the entries are eligible, a message should be displayed ( in case of delete , there is already implemented)

- [x] If multiple problems can appear during a bulk action ( for example ineligible item and exception from Survnet) in the above given modal window should appear the list of ineligible items , a list of items which could not be sent to survnet, a list of items which had any other general exception which prevented the bulk action.

**For > 40 entities:**
- [x]  the above mentioned modal window should appear also for archive/dearchive/sending to reporting tool if the communication is failing with Survnet

- [x]  if for any other bulk actions (except for delete) can happen that the items are ineligible, should be handled with a similar modal window with a proper message (the messages from DeleteRestoreMessages can be used as reference )

-  [x]  if none of the entries are eligible, a message should be displayed ( in case of delete , there is already implemented)

-  [x] If multiple problems can appear during a bulk action ( for example ineligible item and exception from Survnet) in the above given modal window should appear the list of ineligible items , a list of items which could not be sent to survnet, a list of items which had any other general exception which prevented the bulk action.

- [x] if the user does not have the proper right for performing an action ( ex: archiving) the warning message will not appear and the progress bar will remain blocked. This problem should also be solved. ( in the future those bulk actions for which the user does not have right, will not appear at all in the dropdown)

Bulk operations which should be covered in this ticket ( only the operations for which the Progress bar was already introduced):

- [x]  Edit ( for all the entities with bulk edit in place)
- [x]  Delete ( for all the entities with bulk delete in place)
- [x]  Restore ( for all the entities with bulk restore in place)
- [x]  Archive ( for all the entities with bulk archive in place)
- [x] Dearchive ( for all the entities with bulk dearchive in place)
- [x] Cancel follow-up for Cases
- [x] Cancel follow-up for Contacts
- [x] Cases Set to Lost to Follow-up
- [x] Contacts Set to Lost to Follow-up
- [x] Link contacts to event
- [x] Link events to event group
- [x] Send cases to External Surveillance Tool
- [x] Send events to External Surveillance Tool
- [x] Enable users
- [x] Disable users

### Additional Information

Should be implemented after https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11931.

**Comment by carina29** [comment]
In this attached pdf can be found the scenarios for the bulk actions.
Some of the messages will be slightly changed after finishing the requested review changes.

[Handle the exceptions and messages.pdf](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12421917/Handle.the.exceptions.and.messages.pdf)

**Comment by carina29** [comment]
@MateStrysewske  I've created a new ticket for handling the archiving/dearchiving of the linked contacts as @leventegal-she suggested in the review comments. The ticket will need refinement: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12459

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: on test-de3 the counter for archiving and de-archiving cases does not count correctly how many entities have been processed successfully and how many were skipped.

The total of selected cases was 939, the counter says it successfully processed 1193 and skipped 254, which does not make sense. Additionally, once the user closes the pop-up, it is visible that all cases have been either archived or de-archived depending on the selection.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/34c0996c-099b-44a4-b9b2-42bc9654195a)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and test-de3 using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(612d9c0) and 1.89.0-SNAPSHOT(5ee1eff).
