### ISSUE TITLE
Allow region/nation level users to be selected as responsible user for environments [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12262]
### Problem Description

https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11535 has introduced create/edit forms for environments which include a responsible user field. In the issue, it was specified that this dropdown should contain all users with edit rights for environments that are assigned to the same district as the environment. Currently, this means that ONLY district-level users can be selected from the dropdown, which isn't correct.

### Proposed Change

Also include all users with edit rights for environments that are assigned to the region of the environment's district or to no jurisdiction at all (i.e. nation-level users).

### Added Value/Benefit

Proper implementation of the feature.

### Acceptance Criteria

- [x] The dropdown "Responsible user" contains all users that have the ENVIRONMENT_EDIT right and are either assigned to the environment's district, the region of that district, or to no jurisdiction at all

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.88.0-SNAPSHOT(46dbe1b).
