### ISSUE TITLE
Add functionality to Create/edit/delete disease variants via the UI

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12261]
### Feature Description

Users with the appropriate permissions should be able to add/edit/delete disease variants for any diseases via the UI

### Added Value/Benefit

A simplified administration and no server level interventions

### Acceptance Criteria

- [ ] Creation of the right to manage disease variants (CRUD)
- [ ] Creation of a new UI element in the admin menu to manage disease variants

### Mockups

in progress

### Additional Information

does the system need a restart for the changes to be adopted?

**Comment by adinaflorea9** [comment]
@markusmann-vg Mentioned that you (@SORMAS-ChristopherMeyer) might be able to provide a mock-up for this ticket. When you are able to add the mock-up to the ticket, would you please also tag me here in a comment so that I can then continue to refine the ticket?

**Comment by SORMAS-ChristopherMeyer** [comment]
sorry i am late on this i have so many other things to do. i will deliver the mockup by tomorrow evening. @adinaflorea9

**Comment by adinaflorea9** [comment]
> sorry i am late on this i have so many other things to do. i will deliver the mockup by tomorrow evening. @adinaflorea9

No worries! whenever you have time! Thank you :)

**Comment by kwa20** [comment]
@SORMAS-ChristopherMeyer I think you might be looking for something like this #6340 :)

**Comment by SORMAS-ChristopherMeyer** [comment]
Yes that is the optimal solution, I don't know how much of that we can implement within the current project.

@kwa20 
I did not know that you are still active here. Nice to have you on board. :-)

**Comment by markusmann-vg** [comment]
will be covered with #6340
