### ISSUE TITLE
Reshared entities to Survnet (cases and events) will not trigger a Survnet call when archiving/dearchiving

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12274]
### Bug Description

The entities (cases/events) which were shared with Survnet (in single or bulk mode), were soft-deleted, restored and then reshared with Survnet will not trigger a Survnet call when archiving/dearchiving which causes inconsistent data between Sormas entities and Survnet entities.

### Reproduction Steps

1. Share one or multiple entities with Survnet ( use Send to reporting tool for cases or events in single or in bulk mode)
2. Soft delete the shared entity/entities
3. Restore the entity/entities
4. Share again with Survnet the entity/entities
5. Try to archive/dearchive the entity/entities

The call to change the archive/dearchive flag in Survnet will not be made and therefore the report will not be downloaded in Survnet output folder.

### Expected Behavior

In the above mentioned scenario the call to Survnet in order to change the archive flag should be made and as an outcome the report should be downloaded.

The problem can be reproduced with any user with archive rights (Survnet project is needed to be installed).

### Affected Area(s)

Web app

### SORMAS Version

1.86

### Android version/Browser

Chrome

### User Role(s)

National user

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version: 1.87.0-SNAPSHOT (5f453b1)
