### ISSUE TITLE
Introduce the 'Reason for deletion' column in the 'Environments' grid

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12280]
### Problem Description

Similar to the 'Reason for deletion' columns that are displayed in the other directories of SORMAS, in the 'Environments' directory the column should also be introduced.

### Proposed Change

Introduce the 'Reason for deletion' column in the 'Deleted environments' grid of the 'Environments' directory.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/5de1b0a5-4b52-4bb4-868c-9a6529f4cbfc)

### Added Value/Benefit

Consistency between the directories; display of the mandatory deletion reason that the user has to fill when deleting an entity.

### Acceptance Criteria

- [x] the column should be displayed as the last one on the grid;
- [x] the column should contain the reason for deletion selected by the user when deleting the specific environment;
- [x] just as in the other directories the column to display the reason for deletion (combine enum + free text)
- [x] the column should be visible only to users that have 'Delete existing environments' right (the 'Deleted environments' full grid is not displayed when that right is missing - therefore that logic should not be changed as it will also prevent displaying the deletion reason);
- [x] sorting does not need to be implemented for the column (just as in the other directories).

**Comment by carina29** [comment]
Note: The requirement "The column should only be displayed in the 'Deleted environments' grid" will be handled in the following ticket: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13038

**Comment by richardbartha** [comment]
Tested on local env version 1.95.1
