### ISSUE TITLE
Do not allow the editing of environmental entities not owned outside the user's jurisdiction [1]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12285]
### Problem Description

Currently, for the environmental entities, as long as the users have the 'Edit existing environments' they can edit information on the entity page even when the entity is not owned by them and outside their jurisdiction.

### Proposed Change

No longer allow users to edit information on the environmental entity page if the entity is outside the user's jurisdiction and the entity is not owned by them.

### Added Value/Benefit

Consistency with the edit behavior on the other SORMAS entities.

### Acceptance Criteria

- [ ] make the environment entity page read only for users that do not own the entity, and the entity is outside the user's jurisdiction;
- [ ] when the user is the owner of the entity, and the entity is outside the user's jurisdiction keep allowing the editing;
- [ ] when the user is not the owner of the entity, and the entity is initially in their jurisdiction, but the user tries to change the jurisdiction of the entity show a warning pop-up upon saving (similar to the one we have for Events, for example); the pop-up should say: 
-The heading "Environment location update"; 
-Text of the pop-up "Changing the location of this environment could make you lose access to its details and/or disallow you to edit in the future. Are you sure you want to proceed?";
-Buttons: 'Yes' and 'No'.

**Comment by leventegal-she** [comment]
Android app part blocked by [Add a create/edit form for environments in the mobile app [5]#12030](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12030)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version for SORMAS from the development branch - 1.88.0-SNAPSHOT(b8e5a86).
