### ISSUE TITLE
[Link to event - bulk action] Cases and contacts can not be linked to an event if the person is already associated in any way with the event

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12292]
### Bug Description

There a three flows observed so far where cases and contcts can not successfully be linked to events via the bulk action 'Link to event'.

### Reproduction Steps

I: Link cases to events - person has 1 case and 1 event participant
1. Create a case;
2. Create an event;
3. Open the created event, click on 'Add participant' and using the person search choose the person that is associated with the case from step1;
-> at this point there is a person that has a case and an event participant; on the case page the event is not linked; in the event participant grid, the case is not linked to the event participant.
4. In the cases grid, enter bulk edit mode;
5. Select the case from step 1 and choose the bulk action 'Link to event';
6. From the list of events, select the event from step 2 and save;
Actual behavior: a pop-up appears stating that the case is already linked to the event. However, this is not shown on the case page.

II: Link cases to events - person has 1 case and 1 deleted event participant
1. Create a case;
2. Create an event;
3. From the case page, link the event from step 2 to the case;
4. From the event, open the event participant that got created as the result of step 2 and delete it;
-> at this point in the case page it is visible that the case is no longer linked to that event.
5. From the cases grid, enter bulk edit mode;
7. Select the case from step 1 and choose the bulk action 'Link to event';
8. From the list of events, select the event from step 2 and save.
Actual behavior: a pop-up appears stating that the case is already linked to the event. 

III: Link contacts to events - person has 1 contact and 1 deleted event participant
1. Create a contact;
2. Create an event;
3. From the contact page, link the event from step 2 to the contact;
4. From the event, open the event participant created as a result of step 3 and delete the event participant;
5. From the contacts grid enter bulk edit mode;
6. Select the contact from step 1 and choose the bulk action 'Link to event';
7. From the list of events choose the event from step 2 and save.
Actual behavior: a pop-up appears stating that the contact is already linked to the selected event.

### Expected Behavior

The cases and contacts should successfully be linked to the event selected via the bulk action 'Link to event'.

### Affected Area(s)

Web app

### SORMAS Version

1.86.0, 1.85.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine

**Comment by MateStrysewske** [comment]
#12257 does a major refactoring of bulk editing; we should wait until that issue is merged before we pick up this bug again.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(ba60878).
