### ISSUE TITLE
Error when logging in with an Admin+NatUser and trying to open SORMAS in the 'Dashboard'

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12336]
### Bug Description

An error appears when trying to open SORMAS directly on the Dashboard with an Admin+NatUser.

Logs from the local machine:
[logs log in dashboard.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12145086/logs.log.in.dashboard.txt)

### Reproduction Steps

1. Log in SORMAS with the Admin+NatUser default user;
2. Open the 'Dashboard'.

### Expected Behavior

No error should appear.

### Affected Area(s)

Web app

### SORMAS Version

1.87.0-SNAPSHOT(6e4fea8)

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine

**Comment by StefanKock** [comment]
It's not a bug, it's caused by not updating the serverlibs, relates to #12094

**Comment by adinaflorea9** [comment]
@StefanKock I did those updated at the time when the ticket was merged and everything was fine until earlier today. What could have changed in the menatime?
