### ISSUE TITLE
Deactivate the sliding synchronization feature in the mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#12333]
### Problem Description

* When a user slides their finger on the case director, the synch job is activated
*  Sliding down the screen is also used to scroll down the page
*  Synch job if often activated, with a pop-up progress infobox, causing users to wait until the end. Often happen when the user does not master the different sliding types (synch and scrolling)

### Proposed Change

* Deactivate synch by sliding n the tablet screen
* users will then need to open the ... icon and actively synch data
* 

### Added Value/Benefit

* users will not be blocked by mistakenly activating synch

### Acceptance Criteria

- [ ] Sliding down the screen will not activate synch

### Additional Information

* If we decide to implement this request, then we need to inform other users who have been using this feature.

**Comment by MateStrysewske** [comment]
@bernardsilenou If this is needed, we should implement it as an option that can be turned on/off in the settings for the individual user. I'm not a fan of turning it off for all users because it makes the synchronization more complicated for users who are able to use this feature.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
When users masters the mobile app, they will not longer need this issue. It was decided to drop it
