### ISSUE TITLE
[Immunizations] Archived immunizations can not be delete/restored if the user has 'Edit existing immunization' user right

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12346]
### Bug Description

For archived immunizations, if the user logged in has rights to edit, delete and archive the immunizations, the immunizations that were archived can no longer be deleted. This is not reproducible for the other major entities or when the user does not have edit right for the immunization.

### Reproduction Steps

1. Configure a user to have all the rights associated with immunizations;
2. Log in with the user from step 1 and open an existing active immunization;
3. Archive the immunization;
4. Observe the 'Delete' button at the bottom of the immunization page.
Actual behavior: The 'Delete' button is read only.

5. Remove the right to 'Edit existing immunizations' from the user;
6. Open the same immunization that was archived at step 3.
Actual behavior: Only now the 'Delete' button is clickable. 

### Expected Behavior

The 'Delete'/ 'Restore' buttons on archived immunizations pages should be enabled.

### Affected Area(s)

Web app

### SORMAS Version

1.87.0

### Android version/Browser

Chrome 

### User Role(s)

Admin+NatUser and a Configured user as per the 'Steps to reproduce'

### Server URL

local machine

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.89.0-SNAPSHOT (1432ae2)
