### ISSUE TITLE
App synchronization fails when syncing environments without view access

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12361]
### Bug Description

When trying to synchronize the mobile app as a user without access to environments, the synchronization fails when the mobile app is trying to sync them with an error message that the user does not have the needed permissions. 

### Reproduction Steps

1. Log into the mobile app with e.g. a Surveillance Officer or any other user role that does not have access to environments
2. Synchronize; observe that environments are listed in the sync dialog, and that the synchronization stops when the environment entity is reached

### Expected Behavior

Do not attempt to synchronize environments with a user that does not have access to them, and do not show them in the sync dialog in this case. Make sure that the counts are still correct for the remaining entities in the sync dialog afterwards.

### Affected Area(s)

Android app

### SORMAS Version

SORMAS 1.87.0-SNAPSHOT

### Android version/Browser

API 31

### User Role(s)

Surveillance Officer

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.87.0-SNAPSHOT(a34096b).
