### ISSUE TITLE
[Dashboard] Dashboards on test-de2 no longer show charts all charts

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12378]
### Bug Description

Dashboards for Surveillance, Contacts and Samples on the testing instance test-de2 no longer show the relevant information, but a sort of error message from the logs.

### Reproduction Steps

1. Open https://test-de2.sormas.netzlink.com/sormas with an Admin+NatUser;
2. Open the Dashboards and observe each of them.

Actual behavior:
Surveillance:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/74a03355-0461-4a0a-bce5-d2f9a251c67b)

Contacts:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/0863325c-553e-4b70-bfca-169b837e72d8)

Samples:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/b81db5fa-2389-4a44-aaf7-ac9037c23582)

### Expected Behavior

The relevant information and charts should be displayed.

### Affected Area(s)

Web app

### SORMAS Version

1.87.0-SNAPSHOT(118d04a)

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

https://test-de2.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
Works perfectly fine for me. Can you check it again?

**Comment by adinaflorea9** [comment]
@MateStrysewske yes, it works now on test-de2. I guess it might have been just a deploy issue or loading issue. It was strange that it was only on this test environment and on none of the others.

**Comment by adinaflorea9** [comment]
Issue is no longer reproducible on the existing testing instances. Discarding the ticket.
