### ISSUE TITLE
Dev mode generates data with invalid enum values for the server country

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12414]
### Bug Description

There are currently three scenarios that I observed regarding the failure of sending cases to SurvNet on the case page or in bulk edit mode.

### Reproduction Steps

I: Sending cases to SurvNet fails from bulk edit mode but is successful from the case page:
1. From the 'Configurations' directory, 'Developer' tab, generate 100 Covid-19 cases;
2. Navigate to the 'Cases' directory and enter bulk edit mode;
3. Select some of the cases generated (either under or over 40);
4. From 'Bulk actions' select 'Send to reporting tool';
Actual behavior: The bulk action fails and an error is displayed.
5. After the error appeared, open the first case in the list;
6. Click on 'Send to reporting tool'.
Actual behavior: the case is successfully sent.

II: Sending cases to SurvNet fails from bulk edit mode and from the case page: 
1. From the 'Configurations' directory, 'Developer' tab, generate 100 Covid-19 cases;
2. Navigate to the 'Cases' directory and enter bulk edit mode;
3. Select some of the cases generated (either under or over 40);
4. From 'Bulk actions' select 'Send to reporting tool';
Actual behavior: The bulk action fails and an error is displayed.
5. After the error appeared, open the first case in the list;
6. Click on 'Send to reporting tool'.
Actual behavior: Sending the case to reporting tool fails.

Server logs when sending cases to SurvNet fails from bulk edit mode:
[Under 40 entries selected error in bulk edit mode.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12312498/Under.40.entries.selected.error.in.bulk.edit.mode.txt)

[Over 40 entries selected error in bulk edit mode.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12312522/Over.40.entries.selected.error.in.bulk.edit.mode.txt)

Server logs when sending cases to SurvNet fails from the case page:
[Error when sending only 1 case to SurvNet.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12312545/Error.when.sending.only.1.case.to.SurvNet.txt)

### Expected Behavior

All cases that are not marked as 'Do not share with reporting tool' should be able to be successfully sent to SurvNet from the case page and bulk edit mode, regardless of whether under or over 40 entries are selected.

### Affected Area(s)

Web app

### SORMAS Version

1.87.0, 1.88.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

test-de3, test-de2, test1402

**Comment by carina29** [comment]
As we've discussed with @MateStrysewske besides the change in the Developer view (done in the attached PR) in order to prevent in the future the creation of enum values which should not be available for a country locale, also a migration script will be necessary which should be sent to Netzlink in order to set the CH related enum fields to "UNKNOWN".

Netzlink should run the script on the used test instances.

**Comment by MateStrysewske** [comment]
Script for NL to execute on test instances:

```
UPDATE cases SET quarantine = 'UNKNOWN' WHERE quarantine = 'HOSPITAL' OR quarantine = 'HOTEL' OR quarantine = 'ASYLUM_ACCOMMODATION';
UPDATE contact SET quarantine = 'UNKNOWN' WHERE quarantine = 'HOSPITAL' OR quarantine = 'HOTEL' OR quarantine = 'ASYLUM_ACCOMMODATION';
UPDATE travelentry SET quarantine = 'UNKNOWN' WHERE quarantine = 'HOSPITAL' OR quarantine = 'HOTEL' OR quarantine = 'ASYLUM_ACCOMMODATION';
```

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com using SORMAS version 1.90.0-SNAPSHOT(059fd45). All newly generated cases with Dev Mode were sent to SurvNet as long as they were not marked as 'Do not send'.
