### ISSUE TITLE
Enable the session-timeout in Vaadin

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#12448]
### Problem Description

Vaadin offers a "heartbeat" functionality, that prevents the session-timeout to be triggered.
However from Data Protection Perspective this should be enabled by default

https://stackoverflow.com/questions/48741820/vaadin-8-set-session-timeout

### Proposed Change

sormas-ui/src/main/webapp/WEB-INF/web.xml

<img width="453" alt="Bildschirmfoto 2023-08-23 um 13 22 36" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/62540178/a59238d0-5dc2-43e3-9a95-8b9ebe36568a">

 

Is probably interpreted by VaadinService.getUidlRequestTimeout

### Added Value/Benefit

Comply to German data security requirements

### Acceptance Criteria

- [ ] User is automatically logged out after 30 minutes of inactivity

**Comment by MateStrysewske** [comment]
Note: This only makes sense if the SSO Session Idle property in Keycloak is set to the same value, otherwise reloading will simply automatically log in the user again.

**Comment by adinaflorea9** [comment]
Verified ticket on test.sormas.netzlink.com, test-de2.sormas.netzlink.com using the latest version of SORMAS from the development branch - 1.88.0-SNAPSHOT(fcad275).
