### ISSUE TITLE
Display a history of sent external emails [3]

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12465]
### Feature Description

External emails that have already been sent successfully must be clearly presented to the user.

Linked to #12402 

### Added Value/Benefit

Traceability and clarity.

### Acceptance Criteria

- [x] The `ManualMessageLog` entity and DTO have been extended with new fields:
  - String `usedTemplate`
  - Set<String> `attachedDocuments`
  - String `emailAddress`
  - reference fields for caze, contact, event participant, and travel entry
- [x] When sending out an external email, a log entry of type `EMAIL` is added to the database, with all existing and new fields filled in (only one reference of course, the one of the entity from which the email has been sent); the `attachedDocuments` field contains the file names of all documents attached to the email, and the email address field contains the email address the email has been sent to
- [x] In the side component introduced in #12463, as soon as at least one mail has been sent to the person through the displayed entity, a list of log entries is displayed, listing all log entries of the type `EMAIL` for the respective person and the referenced entity where `usedTemplate` is not empty
- [x] The following fields are displayed in the side component for each log entry, underneath each other on the left side:
  - Date sent
  - Used template
  - Sending user
- [x] In addition, an info button is displayed on the right side (vertically centered); when clicked on, it brings up a pop-up that contains additional information about the sent email:
  - Email address the email has been sent to
  - Attached document names

### Additional Information

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.93.0-SNAPSHOT(805282f).
