### ISSUE TITLE
Attach documents to external emails [8]

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12464]
### Feature Description

Documents previously created from document templates or uploaded by the user should be attachable to external emails sent out to patients based on email templates.

In addition, each document should be password protected.  If the recipient in the system is in possession of a LUXID, the document(s) should be encrypted using their LUXID ([Structure of LUX ID](https://ccss.public.lu/dam-assets/seculine/ccss-structure-numero-identite-FR.pdf)). If the recipient in the system is not in possession of a LUXID, the document is encrypted using a random password (not provided by LUX) and this password sent (via SMS) to the primary mobile phone number listed in SORMAS.  If no telephone number exists in SORMAS to send an SMS to, an error is displayed and the document is not sent.

### Added Value/Benefit

Patients can be provided with information that would be out of scope for a text-only email, e.g. it will be possible to send quarantine orders to them.

### Acceptance Criteria

- [x] The popup to send emails to case/contact/event participant/travel entry persons has been extended by an "Attach documents" field that works as follows
  - [x] A dropdown contains all documents that have been uploaded for the respective case/contact/ep/travel entry; only include .pdf, .docx, .jpg, .jpeg, .gif and .png files (check if those are even supported by SORMAS; if one of them isn't supported by the document uploading feature, exclude it)
  - [x] Selecting a document adds it to a list of selected documents beneath the dropdown (see mockup), including a red cross icon to its left; clicking on the icon removes the document from the list
  - [x] If encryption is not possible, the component is disabled and a hint is displayed below the dropdown: "Attaching documents is disabled because encryption would not be possible. To encrypt documents, the person needs to have either a national health ID specified, or a primary mobile phone number set with SMS sending set up on this system."
    - Encryption is only possible if a) a proper national health ID is specified, or b) a primary mobile phone number is specified and the SMS authentication key and secret have been set up in the properties file
    - Determining whether the national health ID is valid is done by checking its structure according to the rules in this document: https://ccss.public.lu/dam-assets/seculine/ccss-structure-numero-identite-FR.pdf - this is only done on Luxembourg servers though, skip validation on all other servers
- [x] When the user sends the email with at least one document attached, non-pdf documents are converted to .pdf and the document is encrypted
  - [x] Documents that are not provided in .pdf format are converted to .pdf; see https://www.baeldung.com/pdf-conversions-java for inspirations of how to do this; only conversion functionality for the file formats specified above need to be provided
  - [x] After all non-pdf documents have been converted, all selected documents are encrypted and password-protected; using https://pdfbox.apache.org/index.html would be an option here (example: https://www.geeksforgeeks.org/encrypt-pdf-using-java/)
    - If the person has a valid national health ID, this is used as the password
    - Otherwise, a random password is generated (10 digits, using numbers excluding 1 and 0, uppercase and lowercase letters excluding lowercase L (l), uppercase i (I), and uppercase o (O))
- [x] After documents have been encrypted, the email is sent to the person, with all selected documents attached
- [x] If a random password has been generated, after sending the email, an SMS is sent to the person's primary mobile phone number, with the following text: "Please use this password to open the documents sent to you via email from SORMAS: {password}"

### Mockups

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/3a1f5836-1d6e-4e4e-945f-23d62089aa82)

### Additional Information

**Comment by leventegal-she** [comment]
For converting documents to pdf we could consider using https://gotenberg.dev/ as an external service in a docker image. It handles most of the "document" file types allowed to be uploaded in SORMAS but not images.

For password protecting https://pdfbox.apache.org/index.html seems to be a good library like the example here https://www.geeksforgeeks.org/encrypt-pdf-using-java/

**Comment by MateStrysewske** [comment]
@leventegal-she Using an external service that has to be provided in a Docker image is pretty much out of question I believe, because we can't assume that people using SORMAS will also be using Docker as long as we provide a Docker-free SORMAS in this repository. There are Java libraries that we can use to convert images and .docx files to .pdf files, and I think that would be enough.

**Comment by MateStrysewske** [comment]
"Attached documents" in the send email popup does not have a proper caption.

**Comment by adinaflorea9** [comment]
Email sent are duplicated in the Emails card:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/59e38384-2e4b-42da-81fd-3975af149dc7)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.93.0-SNAPSHOT(64fb33c).
