### ISSUE TITLE
Create new user rights to manage, send and attach documents to email templates [0.5]

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12466]
### Feature Description

For the email template feature (see #12402), new user rights to create, send and attach documents to email templates need to be introduced.

### Added Value/Benefit

Access to email template features can be granted to user roles.

### Acceptance Criteria

- [x] Add a new `EXTERNAL_EMAILS` user right group ("External emails") below `DOCUMENTS`
- [x] Add a new `EMAIL_TEMPLATE_MANAGEMENT` user right ("Manage email templates"); added only to the default Admin role
- [x] Add a new `EXTERNAL_EMAIL_SEND` user right ("Send external emails") 
- [x] Add a new `EXTERNAL_EMAIL_ATTACH_DOCUMENTS` user right ("Attach documents to external emails")
- [x] The send and attach user rights are granted to all default user roles who have the `DOCUMENT_UPLOAD` user right
- [x] The new user rights are displayed with captions in the user rights management screen

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(32ad230).
