### ISSUE TITLE
[Samples] Return to case after deleting a sample from the case [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12485]
### Discussed in https://github.com/SORMAS-Foundation/SORMAS-Project/discussions/12009

<div type='discussions-op-text'>

<sup>Originally posted by **AliciaRaber** April 17, 2023</sup>
### Problem Description

When you are in a case and click on the pen-button in the samples section the system change to samples and display the simple sample. In this overview it is possible to delete the sample. After deleting the sample the system remains in the sample directory

### Proposed Change

After deleting a sample from case view set trigger to return to the case from the deleted sample.

### Added Value/Benefit

For a better traceability and case management the user can work on the same case without have to search again for the case.

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

### Implementation Details
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/ea1127f0-4128-495f-b7fc-c7922e62c04e)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/8027ea45-9cfe-4ca1-b0bf-feca642267b0)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/138e88b5-ed50-4a6d-9b8f-0c4b028f37ea)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/0f9f5cb8-9182-4674-90b1-0f7fea038691)

### Additional Information

_No response_</div>

**Comment by carina29** [comment]
@MateStrysewske I've done the change for the redirecting from sample uuid page to the case uuid page ( when the sample has an associated case). 

For samples which have associated event participants ( redirecting should be done to the event participant's uuid page) or associated contacts ( redirecting should be done to the contact's uuid page) there is still in place the logic we've had before this ticket for cases: after deleting the sample, the system remains at the Sample directory.
But those scenarios mentioned by me were not requested in this ticket.

@MateStrysewske Do you think that would be useful to change the code for samples with associated event participants/samples with associated contacts too ( in this ticket or maybe in another follow-up ticket)? 
Thank you :)

**Comment by MateStrysewske** [comment]
@carina29 If it's not much effort, I'd vote for doing it in this issue as well. Otherwise, a follow-up ticket would make sense, yes!

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(32ad230).
