### ISSUE TITLE
Add report date to environment samples [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12501]
### Feature Description

Add a report date field to environment samples in the web and mobile app.

### Added Value/Benefit

Report dates are essential for the bureaucratic part of epidemiological surveillance.

### Acceptance Criteria

- [ ] Report date has been added to the entity and DTO in the web app
- [ ] Report date has been added to the entity in the mobile app

**Comment by adinaflorea9** [comment]
As environments samples are not yet editable (the edit form has not yet been implemented) I verified the ticket by checking whether the mandatory report date was added in the DB for samples - and a new environment sample can not be saved in the DB if it does not have a valid report date. 

Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-NSAPSHOT(2966ed2).
