### ISSUE TITLE
Data synchronization problem

### ISSUE THREAD

**Issue by Tommymbk** [SORMAS-Foundation/SORMAS-Project#12529]
### Bug Description

After launching the SORMAS application on the tablet, when starting synchronization there is a message Unable to connect to the server, try again later
[Log_Musangu_Tsy.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12605054/Log_Musangu_Tsy.txt)

### Reproduction Steps

1. Launch the application, enter the PIN code
2. While on the case or mSERS list by sliding your finger from top to bottom to synchronize the data or by clicking on the synchronization icon.
3. Synchronization starts but does not finish
4. A dialog box appears at the top in RED saying Unable to connect to server, try again later
![Screenshot_Synchronisation Impossible](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/109162021/d4f93e2d-d6a4-47cb-8dc2-ace97aa3984c)

### Expected Behavior

We should get the message Synchronization successful.
![Screenshot_Synchronisation réussie](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/109162021/f7972ad4-a03c-4eec-b040-54308e822100)
 

### Affected Area(s)

Android app

### SORMAS Version

SORMAS 1.84.1

### Android version/Browser

Version Android 11

### User Role(s)

Hospital Informant

### Server URL

https://congo-stable.sormas.netzlink.com/sormas-rest/

### Additional Information

@bernardsilenou for assistance

**Comment by MateStrysewske** [comment]
Hey @Tommymbk, the logs don't contain anything suspicious, e.g. an exception that hints at a specific issue. Could you please also provide server logs from the timestamp of the attempted synchronization? Also, when I try to open the URL you provided, I get a 500 Internal Server Error; seems like the server is down, in which case the mobile app of course can't communicate with it. Please make sure that the server is up and running (i.e. get in touch with Netzlink) and then try again as soon as it's back up and running.

**Comment by bernardsilenou** [comment]
@MateStrysewske @Tommymbk 
- The provided URL was for the mobile app :) the server is reachable
- A new version was manually installed in the mobile app, thus no option to reproduce the log. Other mobile apps pointing to the server work well. 
- With this? I will close the issue
