### ISSUE TITLE
Skip the "Pick or create entry" window when processing external messages if only one of the features is applicable [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12548]
### Problem Description

When only one of the features case surveillance, contact tracing, and event surveillance is enabled, or the user only has the user right to create entities for one of those, the external message processing workflow still prompts the user to select which kind of entity they want to create.

### Proposed Change

Hide all options that are not eligible to be used based on the features that are enabled on the server and the create rights of the user. Furthermore, prevent the processing of external messages if the user is not allowed to create either cases, contacts, or event participants.

### Added Value/Benefit

The workflow will be simplified for systems that only use one of the feature types (e.g. Luxembourg), and it will no longer be possible to create entities that aren't supported in the first place.

### Acceptance Criteria

- [x] The "Pick or create entry" window only shows radio buttons for the entities that are enabled on the server AND that the user has the create right for
- [x] If the user can only create entries for one of the entities (case, contact, event participant) based on the criteria above, skip this window completely UNLESS there is a potential duplicate found
- [x] If there is a potential duplicate found, the window is still shown, but only the "Create new" radio button for the entity that the user has access to is shown besides the "Select" radio button for the same entity
- [x] Additionally, disable the "Process" button if the user does not have the "create and edit" user rights for either cases, contacts, or event participants, or if none of the features is enabled on the server

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following - when the 'Create cases' right is missing, the user can still click to process a 'Physician's report' that can only be processed into cases - the 'Create new case' form that they are prompted to is read only so they should not be able to click on 'Process' to begin with if the right to create cases is missing. 

The same applies if all edit rights over cases are missing too.

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com/ using SORMAS version 1.90.0-SNAPSHOT(60df41).
