### ISSUE TITLE
Add an option to hide the jurisdiction fields from cases and use default values [5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12550]
### Feature Description

For epidemiological surveillance right now, Luxembourg does not divide the country into several jurisdictions like e.g. Nigeria or Germany do. Because of that, the case jurisdiction fields are redundant and actually would be more of a hassle to be used by the users there. Therefore, a feature configuration is to be added to the system that hides the jurisdiction fields from cases (and other entities that are directly connected to cases and that aren't a separate feature) and automatically fills them with a default option.

Please note that it's not necessary to implement most of this in the mobile app, except for adding the new field to the infrastructure entities and the database for consistency reasons.

### Added Value/Benefit

Users in countries that don't divide the country/area in which SORMAS is used into several jurisdictions won't have to bother with the jurisdiction fields, easing and speeding up their workflow.

### Acceptance Criteria

- [x] A feature type property `HIDE_JURISDICTION_FIELDS` has been added to the `CASE_SURVEILANCE` feature, disabled by default
- [x] The `InfrastructureAdo` and `InfrastructureDto` classes, and all infrastructure tables in the database have been extended with a boolean `default` field, `false` by default; this also needs to be applied to the mobile app
- [x] All infrastructure create/edit forms in the UI have been extended with a checkbox for the new field (caption: "Default jurisdiction"); only show this field when the new feature type property is enabled
- [x] Upon saving an infrastructure with the checkbox checked, there's a backend validation that ensures that there is not already another default jurisdiction of the same type in the database; if there is, a ValidationRuntimeException with the text "There already is another default {entity name} in the database. Only one default {entity name} is allowed." is thrown
- [x] Add a `private DTO defaultInfrastructure` field to `AbstractInfrastructureFacadeEjb`, and a method called `getDefaultInfrastructure` that checks whether the field is already filled; if yes, return its value, otherwise query the database for the first entry of the ADO type with `default == true`; make sure that this method doesn't fail if there are no or multiple default entries; basically, this field should work like a cache so that we only have to query for default jurisdictions once and not every time a user requests those
- [x] If the new feature property is enabled:
  - [x] In the case creation and edit forms, hide all jurisdiction fields (and related fields, e.g. the "Place of stay differs from responsible jursidiction" checkbox) up to facility and automatically fill the region, district, and community fields with the respective default options by using the new `getDefaultInfrastructure` method; health facility fields will remain visible
  - [x] In the location form, hide the region, district, and community fields and automatically fill them with the respective default options

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- Will this change not affect most of the management processes and rights that we have in the system?  OR if future management rules based on the default administrative units are added to the system, then how will Lixemburg benefit?
- Since Lux has cantons as Administrative unit 0, and  Communities as Administrative unit 1, what about adding a mapping rule + translations to map cartoons to regions and communities to districts? when country server is Lux?

**Comment by MateStrysewske** [comment]
@bernardsilenou Possibly, this feature is kind of experimental, but I don't see any country except Luxembourg using it, and Luxembourg will only use case surveillance for now, no contact tracing, immunization management, event surveillance, etc. I don't really see a reason to invent complex mapping rules in favour of this.

**Comment by abrudanancuta** [comment]
Validated on local machine with the version 1.91.0-SNAPSHOT (a0c405b)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(1c5762c).
