### ISSUE TITLE
Add "automaticProcessingPossible" field to external messages [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12571]
### Feature Description

External messages from eSanté are supposed to be, under the right circumstances, automatically processed. However, this is only applicable if all information from the CDA message could be parsed correctly. The main part of this will be done in the eSanté adapter; for SORMAS, we simply need to know whether the automatic processing can be done or not.

### Added Value/Benefit

This is one part of the logic that will allow us to automatically process unambiguous external messages, thus reducing the amount of necessary user interaction.

### Acceptance Criteria

A new boolean field `automaticProcessingPossible` has been added to ExternalMessageDto. It is NOT necessary to add this field to the entity or database.

**Comment by carina29** [comment]
I'm reopening this ticket in order to fix a Demis bug(https://github.com/SORMAS-Foundation/sormas-demis-adapter/issues/89) caused by this change.
