### ISSUE TITLE
Saving changes after archive is not possible

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12574]
### Bug Description

After making an archive for an entity and trying  then a saving for a change it will not be possible.

The problem appears only on **Case** and **Event**.

**Precond**: The edit is possible after making an archive(feature config EDIT_ARCHIVED_ENTITIES is on true)

### Reproduction Steps

1. Open a case or other entity
2. Select archive case
3. Remain on the case edit form
4. Don't make any refresh on the case after making archive
5. Try to change some field
6. Make a save -> at this point the saving will not be possible because of a warning message

### Expected Behavior

Saving should work

### Affected Area(s)

Web app

### SORMAS Version

1.89.0-snapshot

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by sergiupacurariu** [comment]
@abrudanancuta 
The above-described behavior is related to "Feature configuration". If the feature type "EDIT_ARCHIVED_ENTITIES" is false then the above-described behavior happens. If this feature is switched to true then an archived entity can be changed and saved.

**Comment by abrudanancuta** [comment]
I updated the steps to reproduce, that the feature config EDIT_ARCHIVED_ENTITIES is set to true

**Comment by adinaflorea9** [comment]
Verified ticket n the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(f18d58e).
