### ISSUE TITLE
Add an automatic processing logic to external messages [8]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12573]
### Feature Description

External messages from eSanté are supposed to be, under the right circumstances, automatically processed. This process is supposed to be implemented in this issue.

External messages are automatically processed if one of the following is true:
- A national health ID is specified in the external message (and an automaticSampleAssignmentThreshold is specified in the disease configuration) and there is no person with a similar national health ID in the system
- A national health ID is specified in the external message and the person details in the message match those of an existing person with the same national health ID
- No national health ID is specified in the external message and the database does not contain a similar person

Additionally, the `automaticProcessingPossible` field added in #12571 always needs to be true; otherwise, the conditions above are ignored and the message can not be automatically processed under any circumstances (i.e. the external message is just saved as usual).

### Added Value/Benefit

Automatically processing messages will reduce the amount of necessary user input.

### Acceptance Criteria
- [x] A new Integer property automaticSampleAssignmentThreshold has been added to disease configurations (DTO, entity, database)
- [x] When saving an external message, the conditions specified above are checked; if `automaticProcessingPossible` is true and one of the other two conditions applies, the external message is automatically processed
  - When the external message contains a national health ID (and `automaticProcessingPossible` is true), the database is checked for an existing person with the same health ID; if none exists, automatic processing is possible; if one exists, automatic processing is only possible if the person details of the existing person match those in the external message
  - When the external message does not contain a national health ID, the database is checked for an existing similar person using the existing similarity detection logic
- [x] Always set the "Verified by lab supervisor" field value to "Yes" for all pathogen tests created through eSanté, no matter whether they're automatically processed or not
- [x] Always set the sample material and pathogen test type to "OTHER" and add a dummy text to the details field ("Automatically processed"); this will be changed in the future, but requires additional work to be done
- [ ] The new logic added in this issue is only executed on Luxembourg instances (i.e. check the server locale)

**If a national health ID is specified:**
- [x] The database is checked for a person with the same national health ID; if none exists, the person, case, sample, and pathogen test are automatically created based on the external message, and the external message status is set to processed
- [x] If such a person exists, the following fields are checked for consistency - i.e. if they're specified in both the person and the external message, they have to exactly match; if at least one field doesn't match, automatic processing is not possible; fields may only be filled on one end without preventing automatic processing:
  - First name
  - Last name
  - Birth date
  - Street
  - City
  - Postal code
- [x] If a person with the same national health ID exists and its details mach those in the external message, the database is checked for a case that has a) the same disease, and b) is within the threshold of the `automaticSampleAssignmentThreshold` field of the corresponding disease configuration; if such a case exists, the sample and pathogen test are added to that case and the external message is set to processed
  - If a case is found and `automaticSampleAssignmentThreshold` is not defined for this disease, automatic processing is not possible
  - The reference date to determine whether the threshold is met is the sample date time of the EARLIEST existing sample in that case; if no sample exists, we fall back to the case report date
- [x] If a person with the same national health ID exists and its details mach those in the external message, but there is no matching case, the case, sample, and pathogen test are automatically created and attached to the person, and the external message is set to processed

**If no national health ID is specified:**
- [x] The database is checked for a similar person according to the usual similarity criteria; if none exists, the person, case, sample, and pathogen test are automatically created based on the external message, and the external message status is set to processed
  - If a similar person exists, automatic processing is not possible

### Additional Information

**Comment by abrudanancuta** [comment]
Validated together with @MateStrysewske on his local machine
