### ISSUE TITLE
Make region, district and GPS coordinates of environments mandatory [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12578]
### Problem Description

Environments need GPS coordinates in order to properly localize them. While the GPS coordinates of environment samples are required already, those of environments aren't.

### Proposed Change

Make the GPS coordinates of environments required in the web and mobile app.

### Added Value/Benefit

Data completeness

### Acceptance Criteria

- [ ] Region, district and GPS coordinates are required and properly validated in the mobile app
- [ ] Region, district and GPS coordinates are required and properly validated in the web app

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(d037203).
