### ISSUE TITLE
Automatically select the place of stay for cases created through eSanté [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12579]
### Feature Description

Right now, the place of stay of cases created through external messages coming from eSanté is not pre-selected, requiring manual user interaction. An automatic selection based on the content of the message needs to be introduced.

### Added Value/Benefit

This is one of the steps required in order to allow automatic processing of external messages.

### Acceptance Criteria

When a case DTO is created as a result of processing an external message (either automatically, see #12573, or manually through the UI):
- [x] When a person facility is specified in the external message AND the corresponding facility type is an accommodation, set the place of stay to "Facility" and fill in the specified facility
- [x] In any other case, set the place of stay to "Home"

**Comment by abrudanancuta** [comment]
When an external message comes with an address that is not mapped in the Sormas system as Facility, then "Home" should be selected. This case is not happening at the processing of the message. This is the reason that the ticket is being re-opened
