### ISSUE TITLE
Add search functions on the event directory in the mobile app [2]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#12603]
### Feature Description

-  The event directory on the web app has search functions that are missing in the mobile app. Mobile app users would like to have the possibility to search for events using key attributes like  name (title, part of the text should work), date range (or epi week), disease

### Added Value/Benefit

- Mobile users would be able to easily search for specific events.

### Acceptance Criteria

- [x] A filter component has been added to the event list fragment
- [x] The following filters have been implemented:
  - [x] Text input searching events by UUID, title, description (placeholder for this field: "ID, title, description")
  - [x] Disease filter
  - [x] Epi week range filter

### Implementation Details

See the case list fragment filters for reference; all of these filters have already been implemented there.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(684a608).
