### ISSUE TITLE
Rename persons involved to event participants in mobile app [1]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#12605]
### Problem Description

Event participants are called "persons involved "in the mobile app.

### Proposed Change

To rename all instances or persons involved to event participants or vice versa.

### Added Value/Benefit

Users will not get confused with namings when they use mobile and web apps at the same time 

### Acceptance Criteria

- [ ] All occurrences of "Person involved" has been renamed to "Event participant"
- [ ] All occurrences of "Persons involved" has been renamed to "Event participants"

**Comment by carina29** [comment]
Hello @bernardsilenou :)
I've checked the code and "Persons involved" appears in captions and other places not just for event participants but for event persons too. 

We have a distinction in code between event persons and event participants. 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/17b12740-53ad-4001-a8ee-2094a9ccf400)

The "Persons involved" naming should be changed when appears for event persons too or just for event participants?
Thank you very much! :)

**Comment by carina29** [comment]
We've agreed with @MateStrysewske that also all the eventPersons occurrences will be renamed to Event Participant in the labels and code.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.91.0-SNAPSHOT(f2aed0d).
