### ISSUE TITLE
Hospital Informant user and Surveillance Officer have permission issue on Tasks section

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12612]
### Problem Description

After logging into the test-auto environment, the users Hospital Informant and Surveillance Officer have a problem with permission to view Tasks. When entering the Tasks directory an error appears.

### Reproduction Steps

1.Go to https://test-auto.sormas.netzlink.com/
2.Login as HospInf or SurvOff 
3.Click on Tasks button from navbar
Actual behavior: An error appears.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/f8261fc5-a054-40d1-88f6-d3d3f58fe0f8)

### Expected Behavior

No error should appear when the users try to navigate to the Tasks directory.

### Affected Area(s)

Web app

### SORMAS Version

1.92.0-SNAPSHOT (e09c71b); 1.90.0

### Android version/Browser

Google Chrome

### User Role(s)

Surveillance Officer, Hospital Informant

### Server URL

https://test-auto.sormas.netzlink.com

### Additional Information

Logs from test-auto:
[log test-auto.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/13448127/log.test-auto.txt)

**Comment by leventegal-she** [comment]
Looks to be an infrastructure issue:
ERROR: could not resize shared memory segment "/PostgreSQL.1179847086" to 33554432 bytes: No space left on device

**Comment by mk-sgent** [comment]
Still issue:

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/afe52b86-6ffb-4493-bcd8-10f9dee09dad)
