### ISSUE TITLE
Edit Sample button in Edit Contact Page or in Edit Case Page don't redirect to chosen Sample

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12620]
### Problem Description

Edit sample button don't redirect to Edit sample After the new contact or case are created 

### Reproduction Steps

1.Go to the Contact directory on the Navbar
2.Click on NEW CONTACT button
3.Fill all mandatory fields
4.Click on SAVE button
5.Click on NEW SAMPLE button
6.Fill all mandatory fields
7.Click on SAVE button
8.Click on EDIT SAMPLE Button

### Expected Behavior

After clicked on EDIT SAMPLE button the user should be redirected to chosen SAMPLE 

<img width="670" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/8f7bcf66-ecf8-495a-a3e4-1676e170493b">

### Affected Area(s)

Web app

### SORMAS Version

1.89.0

### Android version/Browser

Google Chrome

### User Role(s)

National User

### Server URL

https://release-international.sormas.netzlink.com/

**Comment by mk-sgent** [comment]
[Sample._logs.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12846192/Sample._logs.txt)

**Comment by MateStrysewske** [comment]
Probably the same issue as #12616
