### ISSUE TITLE
The caption after successful deleted or archived cases in bulk mode is empty

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12627]
### Problem Description

The caption after successful deleted or archived cases in bulk mode is empty 

### Reproduction Steps

1.Go to the https://release-international.sormas.netzlink.com/  
2.Log into as Automation Admin user
3.Click on the Cases button in navbar
4.Click on MORE button
5.Click on ENTER BULD EDIT MODE button
6.Click  YES in Enter bulk edit mode 
7.Chose two cases(click into two boxes)
8.Click on Bulk Actions button
9.Click on Delete button 
10.Chose some REASON FOR DELETION
11.Confirm selection by click on YES button

### Expected Behavior

The caption should have this message: "All selected eligible cases have been deleted" for EN or "Alle ausgewählten Einreisen wurden gelöscht" for DE

<img width="694" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/bfdf6188-e650-4795-80ec-671fce221c24">

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.89.0

### Android version/Browser

Google Chrome

### User Role(s)

Automation Admin

### Server URL

https://release-international.sormas.netzlink.com/

**Comment by abrudanancuta** [comment]
was fixed by https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12616
