### ISSUE TITLE
Case cannot be created if Place of stay is selected Facility

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12649]
### Bug Description

As User when creating a case with Place of stay Facility, an error appears an the case is not created even if all mandatory fields are completed

<img width="1430" alt="Screenshot 2023-10-16 at 10 14 19" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91872179/e4da436c-b33d-4c5e-8372-140f2eab6a6c">

Logs: 
[FacilityError.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12913919/FacilityError.txt)

### Reproduction Steps

1. As Admin+NatUser create a case by completing all mandatory fields
2. Select Place of stay Facility
3. Complete also all mandatory fields related to facility
4. Try to save the case

### Affected Area(s)

Web app

### SORMAS Version

1.90.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - .191.0-SNAPSHOT(f2aed0d).

**Comment by mk-sgent** [comment]
The issue is still actual. I'm verified again locally and globally this issue on and after this commit https://github.com/SORMAS-Foundation/SORMAS-Project/commit/f2aed0d7d384299749f54f31ef7ea7308848e6c1 

Results:
<img width="397" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/96273583-bbea-4008-b36c-55b2ea50d613">

Version: 1.90.0-SNAPSHOT (8f0432d)

**Comment by adinaflorea9** [comment]
@mk-sgent sorry, what was the problem with the issue? I got an email but I see just that the ticket was reopened and closed again.

**Comment by mk-sgent** [comment]
@adinaflorea9  sorry it was my fault.  I saw changes on the git repository but I don't noticed information that the fixes will work on 1.91.0

**Comment by adinaflorea9** [comment]
@mk-sgent  no worries! 😄 I just asked in case something was still wrong because for me it had tested ok on the local server.
