### ISSUE TITLE
Users can create cases through contacts and event participants if the CASE_SURVEILANCE feature is disabled

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12643]
### Bug Description

Have the Feature config **CASE_SURVEILANCE** set on **False**. When creating a Contact/Event Participant with a positive Sample, user will be asked if he wants to create a case based on the positive sample. From here user will create a case even if the feature config is not available for the system.
Also in the User Role config the rights for Case are available to select.

### Reproduction Steps
I: Contacts:
1. Login with an Admin+NatUser that have a system with CASE_SURVEILANCE set on false
2. Create a Contact with a Sample having Positive result
3. A confirmation pop-up appears asking if a case is wanted to be created
4. Select Yes and continue creating the new Case

II: Event Participants:
1. Log in with a default Admin+NatUser;
2. Disable the 'CASE SURVEILLANCE' feature from the featureconfiguration in the DB;
3. Create an event with an event participant;
4. Add a positive sample with positive pathogen test to the event participant;
Actual behavior: After saving the sample with positive pathogen test, the user is asked whether they want to create a resulting case. Confirming opens the 'Create new case' form and the user can successfully create a case even though the feature for cases is not available from the feature configuration and the 'Cases' directory is not visible.

### Expected Behavior

User should not be able to create a case if the feature is not available for his system.

### Affected Area(s)

Web app

### SORMAS Version

1.89.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.91.0-SNAPSHOT(f2aed0d).
