### ISSUE TITLE
Checkbox trees don't trigger unsaved changes warning and can't be discarded

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12661]
### Bug Description

Changes made to the checkboxes for 'Weather conditions at time of sampling' are not considered for the triggering of the 'Confirm navigation' pop-up and are not discarded when the user clicks 'Discard' at the bottom of the page.

### Reproduction Steps

I - 'Confirm navigation' pop-up not triggered:
1. Log in with an Environmental Surveillance User;
2. Open an existing environment sample;
3. Check some of the checkboxes from 'Weather conditions at time of sampling';
4. Click to navigate to any other page in the app.
**Actual behavior:** The confirm navigation pop-up is not triggered by unsaved changes made to the checkboxes.

II - Changes made are not discarded:
1. Log in with an Environmental Surveillance User;
2. Open an existing environment sample;
3. Check some of the checkboxes from 'Weather conditions at time of sampling';
4. Click 'Discard' at the bottom of the page.
**Actual behavior:** The changes made to the checkboxes are not discarded.

### Expected Behavior

Expected behavior for scenario I: Any unsaved change on the environment sample page, including to the checkboxes, should trigger the 'Confirm navigation' pop-up when the user tries to navigate to another page of the app.

Expected behavior for scenario II: Any unsaved changes at the time when the user clicks 'Discard' should be discarded.

### Affected Area(s)

Web app

### SORMAS Version

1.90.0, 1.89.0

### Android version/Browser

Chrome

### User Role(s)

Environmental Surveillance User

### Server URL

local machine

**Comment by MateStrysewske** [comment]
This issue also exists in the environment form, event form, and case form for the checkbox trees used there (i.e. for all checkbox trees we're using right now).
