### ISSUE TITLE
Synchronize environments of environment samples in the user's jurisdiction

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12669]
### Bug Description

It seems like for environment samples inside the user's jurisdiction that belong to environments outside their jurisdiction, while the environment samples are synchronized to the mobile app, their environments are not. This leads to issues e.g. when changing the comment on those environment samples and then trying to synchronize.

### Reproduction Steps

1. Log in the mobile app with a Default Environmental Surveillance User restricted to Region1 District1;
2. In the web app, with an Admin+NatUser create an environment in Region2 District2;
3. Then create a sample for the environment from step 2, but set the sample in Region1 District1;
4. Trigger a synchronization in the mobile app;
5. Open the sample from step 3 in the mobile app and click on the pecil icon to enter edit mode;
6. Edit the comment, save the sample, and try to synchronize; synchronization fails

### Expected Behavior

The environments of environment samples that are in the user's jurisdiction are synchronized to the mobile app, users can change the comment of the environment samples, and the synchronization afterwards succeeds.

This is a similar pattern as for events and event participants; i.e. the user filter of environments needs to be extended - see the event user filter on how to do this.

### Affected Area(s)

Android app

### SORMAS Version

1.90.0

### Android version/Browser

Unknown

### User Role(s)

Environmental Surveillance Officer

### Server URL

localhost

### Additional Information

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/aba5d285-221c-4a2e-841f-471b9340a54c)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(a3a2284).
