### ISSUE TITLE
Assign case(s) to a User and allow them to see the data of only the assigned case(s) in the system [8]

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#12697]
### Feature Description

As a system administrator in SORMAS I want to assign a user a role/right so that the user can only view and manage/edit the case(s) and associated data of the case(s) (for example contacts, samples, person, etc.) that are assigned to them.  This should be possible irrespective of jurisdiction, facility, or disease type of both the case and assigned user.

### Added Value/Benefit

This approach is particularly useful during outbreak investigations where temporary, external specialists are brought in to assist a team/country.  They should not see data from other cases/contacts/event participants in the system per Data Protection Officer (DPO) requirements.

For example, a temporary employee can only view (in the Case Directory) and edit the 5 cases which are assigned (through Tasks) to them.

### Acceptance Criteria

- [ ] A new boolean `restrictAccessToAssignedEntities` field has been added to the UserRole entity
  - Caption: "Restrict access to assigned entities"
  - Description: "User can only see entities (e.g. cases, contacts) they have been assigned to as the responsible user. Other entities will not be visible to them, even if they are in their jurisdiction."
- [ ] The new field has been added as a checkbox below the "Port health user" checkbox in the user role edit form
- [ ] A checkbox filter has been added to the user roles directory that, if checked, only shows user roles for which this field is enabled ("Only show user roles with access restricted to assigned entities")
- [ ] A similar filter has been added to the user management directory ("Only show users with access restricted to assigned entities")
- [ ] All user filters and jurisdiction logic has been extended to take into account the new field
  - Entities that a user can be assigned to as responsible user include cases (surveillanceOfficer or caseOfficer), events, environments and contacts (contactOfficer); please check if something's missing from this list
  - The expected outcome is that users with this access restriction ONLY see entities they have been assigned to as the responsible user, INCLUDING all associated entities; e.g. a user who has been assigned as the surveillance officer to a case would see all contacts, tasks, samples, etc. of this case as long as the normal jurisdiction filter allows it (or they have been assigned to the child entity, e.g. the contact, as well)
  - The user still sees entities they have created (i.e. they are the reporting user of)
- [ ] It's verified that the synchronization of data to the mobile device adheres to this new logic

### Additional Information

Possibly related to:
https://github.com/SORMAS-Foundation/SORMAS-Project/issues/5579
https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11330
https://github.com/SORMAS-Foundation/SORMAS-Project/issues/898
https://github.com/SORMAS-Foundation/SORMAS-Security/issues/7

**Comment by MateStrysewske** [comment]
Reopening as there's still work needed to be done here.

**Comment by adinaflorea9** [comment]
As discussed with @sergiupacurariu I did a general regression/smoke test of the major happy flows in the web and mobile app - they are ok. Leaving the ticket opened and not marked as verified as the functionality itself that was implemented is currently hidden and could not be verified.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(6374a28).

The following constraints apply and should be considered:
1. if the featuretype CASE_SURVEILLANCE - property - {"AUTOMATIC_RESPONSIBILITY_ASSIGNMENT": true} - the behavior of SORMAS  is not as per ticket - the user that is restricted by jurisdiction 1 (but has the checkbox 'Restrict access to assigned entities' set) is assigned as responsible for a case that is in jurisdiction 2 - upon saving any change the user will lose access to the entity as it is not within their jurisdiction and the automatic assignment will assign a user from the entity's jurisdiction;

 2. currently, only users that are already within the entity's jurisdiction can be assigned as responsible (national level ones can not be assigned) - a hack to test this is to have at first both the entity and the user in the same jurisdiction, and the update with an admin one of them to have a different jurisdiction;
 
 3. the disease based restriction does not consider whether the checkbox 'Restrict access to assigned entities' is checked or not - at all times, if a user is restricted by a disease they will only see and have access to entities of that disease (unless they are the reporter of the entity);
 
 4. if the user has more then 1 user role, but the checkbox 'Restrict access to assigned entities' is checked only for 1 of those user roles, then the checkbox is not applied for that user. The checkbox is applied only if all the roles assigned to the user have the checkbox checked.
