### ISSUE TITLE
Import entity line in error report files leads to a re-import error

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12736]
### Bug Description

The entity line in error report files is shifted to the left, i.e. the error description column has an entity, but the last actual field column does not. This leads to an error when re-importing the file.

### Reproduction Steps

1. Upload e.g. an environment import file with errors
2. Download the error report file, fix the errors and try to-reimport the file

### Expected Behavior

The entity line should have a proper alignment.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.91.0-SNAPSHOT

### Android version/Browser

Chrome

### User Role(s)

Admin and National User/Environment Surveillance User

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.91.0-SNAPSHOT(7fabeaa).
