### ISSUE TITLE
Remove the "strict" birth date and national health ID matching when getting duplicate persons

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12750]
### Problem Description

When retrieving potentially duplicate persons from the database, there's a difference when getting the information whether there are ANY potential dupliates (checkMatchingNameInDatabase) and actually retrieving the potentially duplicate persons. For the latter query, `matchMissingInfo` is true, while for the former, it isn't. This leads to a person create or select window appearing with an empty grid if there is exactly one match found.

### Proposed Change

Get rid of the `matchMissingInfo` property in `PersonSimilarityCriteria`.

### Added Value/Benefit

Consistency.

### Acceptance Criteria

- [ ] The `matchMissingInfo` property has been removed from PersonSimilarityCriteria
- [ ] Logic has been updated to always behave like this would be set to false

**Comment by abrudanancuta** [comment]
Validated on test-sormas and test-de2 with the version 1.92.0-SNAPSHOT (58cea39)
The scenarios tested:
1. One person case existing in system with no birthdate set, created the same person case but with birthdate => **no** duplicate detected 
2. One person case existing in system with a birthday set, created the same person case but with different birthdate => duplicate detected
3. One person case existing in system with Nation health id set, created the same person but with no national health id  => duplicate detected
4. One person case existing in system with Nation health id set, created the same person but with different national health id **no** duplicate detected 
5. One person case existing in system with Nation health id set, and birthdate; created the same person with the same Nation health id but no birthdate set => duplicate detected
6. One person case existing in system with birthdate set ; created the same person with the Nation health id but no birthdate set => duplicate detected

The scenarios were applied also to contact, event participant, immunization
