### ISSUE TITLE
Grant users special access to specific cases' personal data for a limited time [8]

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#12758]
### Feature Description

As a system administrator in SORMAS I want to allow another user special access to view the personal data of a particular case, for a predetermined time, so that they may support with investigations during outbreaks.  Once this time has elapsed, the user should not see the personal data any longer.

I should be able to bulk-assign this special access to multiple cases, for multiple users, to save time during outbreak situations.

### Added Value/Benefit

This approach is particularly useful during outbreak investigations where temporary, external specialists are brought in to assist a team/country. They should not see the personal data from all cases in the system (only a specially assigned few) and their access to the personal data of the special access cases should automatically be revoked after the set timeframe, per Data Protection Officer (DPO) requirements.

For example: Epidemiologists have access to sensitive data, but not personal data. However, in cases while investigating an epidemic, it would be helpful to have the option to grant specific epidemiologists access to certain cases' personal data for a specific timeframe.

### Acceptance Criteria

- [x] A new user right `GRANT_SPECIAL_CASE_ACCESS` has been added to the case user right group (caption: "Grant special case access"); added to the default Admin user in the code and via database script
- [x] A new `SpecialCaseAccess` entity extending AbstractDomainObject has been created with the following fields:
  - Case `caze` - caption: "Case"
  - User `assignedTo` - caption: "Assigned to"
  - User `assignedBy` - caption: "Assigned by"
  - Date `endDateTime` - caption: "End date"
  - Date `assignmentDate` - caption: "Assignment date"
- [x] The facade for this new entity contains a method `getByCase` that returns all special accesses to the case in question with end date >= the current timestamp
- [x] A cronjob has been added that, once per night, deletes all entries from the new table whose end dates have expired
- [x] A new "Special access" side component has been added for cases that lists all special accesses for this case by using the method introduced above; see mockup below, but remove the "VIEW ALL CASE DATA" and replace it with the name of the assigned user in bold (+ remove the now redundant "assigned to" line); only visible for users with the new user right
- [x] An edit form (also used as create form) has been added that can be used to create new/edit existing SpecialCaseAccess entities (see mockup below; add assignment date next to the "assigned by" field)
  - The create form does not contain the "assigned by" and "assignment date" fields
  - The "case" field is always read-only
  - The "assigned to" field contains all users in the system that have the "CASE_VIEW" user right
- [x] A bulk action "Grant special access" has been introduced that brings up the create form and, when saved, creates special access entities for the selected user for all selected cases
  - If the user already has access to a selected case, when saving, a warning message is presented to the user: "The selected user already has special access to at least one of the selected cases. Saving will overwrite the existing special access. Do you want to continue?" - when the user continues, the existing special access entity for the case in question is removed before the new entities are saved
-  [x] A user that has special access to a case can see all personal and sensitive details of the case and its associated entities (e.g. contacts, samples, tasks); whether or not they can edit the case depends on the user right and jurisdiction (i.e. this new feature doesn't inherently grant them edit rights)

### Mockups

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/2bce7bd3-1c17-45ad-bb63-41413310f933)

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the bulk action grant special access should not be visible in the grids with soft deleted entities among the possible bulk actions.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0- SNAPSHOT(c1f2245).
