### ISSUE TITLE
Add a create/edit form for AEFI in the web app

### ISSUE THREAD

**Issue by obinna-h-n** [SORMAS-Foundation/SORMAS-Project#12769]
### Feature Description
After an ```AefiReport``` entity has been created in #12728 as part of epic #12634, create and edit forms for this entity are now required for the web application.

### Added Value/Benefit
Users will be able to create and edit Adverse event reports for further usage in the system.

### Acceptance Criteria
- [x] A creation form for adverse events has been added with the following fields:
  - AEFI report ID number (required)
  - Report date (required)
  - Pregnant (required)
  - Trimester (required if pregnant is YES)
  - Lactating (required if pregnant is YES)
  - Age at onset (required)
  - Suspect vaccinations (required)
  - Adverse events (required)
  - Date and time AEFI started (required)
  - Describe AEFI - Signs and Symptoms)
  - AEFI type (required)
  - Reason for serious (required if AEFI type is SERIOUS)
  - Outcome (required)
  - Date of death (required if outcome is DIED)
  - Autopsy done (required if outcome is DIED)
  - Past medical history
  - Investigation needed (required)
  - Investigation date
  - Date received at national level
  - Worldwide ID
  - Comments (National level comment)
- [x] Sidebars for Immunization and Person information summary has been added to the creation form
- [x] An edit form for adverse event has been added with all the fields and sidebars from the creation form
- [x] A sidebar for Adverse Events has been added to the existing Immunization edit form with the following features: 
  - A "New Adverse Event" button that takes the user to the creation form to enter a new adverse event
  - A summary list of adverse events related to the Immunization.
    - Each summary has an edit button that takes the user to the edit form of the adverse event 
- [x] A column with an edit button has been added to the adverse events directory in #12767, which takes the user to a dedicated page for the adverse event, displaying the edit form
- [x] The edit form has functional buttons to delete and archive the adverse event if the user has the respective user rights
- [x] The unsaved changes warning appears as expected for both the create and edit form
- [x] The sub-navigation at the top when inside the adverse event edit page contains a backlink that takes the user back to the associated immunization edit form

### Implementation Details
_No Response_

### Mockups
**Adverse event reporting form**

![reporting-form](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/55580796/40840b32-24ea-4648-91b5-7e36d71ff9c5)

**Adverse event sidebar for Immunization edit form**

![immunization-aefi-sidebar](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/55580796/d8bdd2cc-b634-44ba-8bb3-5113d6e75f00)

### Additional Information
_No Response_

**Comment by bernardsilenou** [comment]
@obinna-h-n 
If there are many adverse events (e.g on day 1, day 3, day 7) after the first vaccination (day 0), is it possible to document each event, just like the "followup visits" for contacts?
