### ISSUE TITLE
Accessing the Dashboard view is not possible and exceptions are thrown

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12781]
### Bug Description

The accessing of the Dashboard is not possible in different scenarios when the redirection is targeting the Dashboard view.

### Reproduction Steps

Logged in with National User ( is reproducible with other users too)

Scenario 1: 
1. When the webapp starts the URL is /sormas-ui/ and the Dashboard View should appear but instead of this an error message appears in the UI and an exception in the logs:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/1c133fa0-35db-4d43-ba15-1dc7f6d33eea)

[LogsWhenApplicationStarts.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/13448737/LogsWhenApplicationStarts.txt)

Scenario 2:
1 If we want to navigate from /sormas-ui URL to another page (example Messages and we use the Browser's "Back" button we should be navigated to Dashboard view.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/de38a3a5-1eef-4c3e-a82b-f5f17e2d0950)
[Logs2.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/13448781/Logs2.txt)

In the DB, in featureconfigurations table all the feature types related to the Dashboard are enabled:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/8d123f69-9fd5-4160-9ffe-884af737f0d4)

The logged in National user has the rights to access the Dashboard:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/ed756ba9-faaa-4daa-9f30-da4e4926eb9a)

### Expected Behavior

The accessing of the Dashboard view should be possible without any error messages on the UI or in the logs.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.91.0

### Android version/Browser

Chrome

### User Role(s)

National User

### Server URL

Local

**Comment by leventegal-she** [comment]
Couldn't reproduce locally nor on test-de2.

Both errors say:
Caused by: javax.naming.NamingException: Lookup failed for 'java:global/sormas-ear/sormas-backend/GeoShapeProvider' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}


Probably a `mvn clean install` and restarting the payara server fixes the issue

**Comment by MateStrysewske** [comment]
@carina29 Does this still happen on your system?

**Comment by carina29** [comment]
@MateStrysewske I've retested again a few minutes ago this ticket. 
I could not reproduce anymore on development or on any branch (last time I've tested 3 weeks ago when was still reproducible).
I'll close this ticket.

**Comment by adinaflorea9** [comment]
Tried to reproduce the issue locally with the latest version of SORMAS from the development branch - 1.93.0-SNAPSHOT(b893fb4) but it is no longer reproducible under the steps described. I am therefore discarding the ticket.
