### ISSUE TITLE
Add support for the hide jurisdiction fields feature to event participants [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12808]
### Feature Description

The option to hide jurisdiction fields introduced in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12550 needs to be applied to event participants as well.

### Added Value/Benefit

Countries that don't use jurisdictions will be able to use event participants.

### Acceptance Criteria

- [ ] If the `HIDE_JURISDICTION` feature is enabled, hide all jurisdiction fields and automatically fill the region and district fields with the respective default options by using the getDefaultInfrastructure method (see CaseCreateForm and CaseDataForm)
- [ ] If the feature is enabled, the jurisdiction filters and columns in the event directory are hidden

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(75fa116).
