### ISSUE TITLE
Add an "active" field to customizable enum values [5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12804]
### Feature Description

Customizable enum values currently can't be deleted, archived or anything like that. However, deletion would imply a lot of potential issues (e.g. the need to manually query all tables where the customizable enum in question is in use in order to determine whether it is used somewhere, which is code that needs to be maintained).

Because of that, the purpose of this issue is to add an "active" field to customizable enum values, similar to the one we have for jurisdictions.

### Added Value/Benefit

Customizable enum values that have been created accidentally or that are no longer in use can be removed from selection fields in order to prevent users from selecting them/seeing too many options.

### Acceptance Criteria

- [ ] A boolean `active` field has been added to customizable enum values - defaults to true
- [ ] The edit form for customizable enum values has been extended with a checkbox for the new field (caption: "Active")
- [ ] The customizable enum values grid has been extended with an "Active" column (would be great to have a renderer that renders true as a checkmark and false as an empty string, otherwise just use our boolean renderer)
- [ ] An "Active/Inactive" dropdown filter has been added (right-aligned) that allows to toggle between active and inactive customizable enum values
- [ ] The customizable enum values grid has been extended with a filter for the new field (dropdown with the selection options "Active" and "Inactive")
- [ ] All code that populates fields with customizable enum values (both in the web and mobile app) has been extended to only show active values of the respective data type; if the currently selected value is an inactive value, it still needs to be shown and added to the field (like we e.g. do it for diseases)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(9270c3d).
