### ISSUE TITLE
Add support for the hide jurisdiction fields feature to immunizations [3]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12806]
### Feature Description

The option to hide jurisdiction fields introduced in #12550 needs to be applied to the immunization module as well.

### Added Value/Benefit

Countries that don't use jurisdictions will be able to use the immunization module.

### Acceptance Criteria

- [x] The `HIDE_JURISDICTION_FIELDS` feature type property has been removed from the `CASE_SURVEILANCE` feature type and moved to its own dedicated feature type in the "Feature extensions" section
  - A database migration script has been added that applies this change to existing databases
- [x] If the feature is enabled, hide all jurisdiction fields up to facility and automatically fill the region, district, and community fields with the respective default options by using the getDefaultInfrastructure method; health facility fields will remain visible (see CaseCreateForm and CaseDataForm)
- [ ] If the feature is enabled, jurisdiction filters and columns in the immunization directory are hidden except for facility-related information; make sure that the facility-related filters are enabled and filled based on the default jurisdictions

**Comment by carina29** [comment]
@adinaflorea9  @MateStrysewske I've tested one of my tickets today and I think that I found a bug if is reproducible on your side too.
I've tried to create a new event with a Surveilance Officer with HIDE_JURISDICTION_FIELDS feature configuration enabled.
In this case the "District" field will not appear in the form but when I've tried to save the new Event I'm prompted that should be filled ( is a mandatory field when the feature configuration is not enabled and is appearing in the form).
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/156ca104-7c35-4d16-81ea-2dcab58da028)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/a95f3d39-f33a-47d0-8cbb-4128367be17e)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/f283c592-ee5a-40e7-acb3-a68cff516fb6)

**Comment by MateStrysewske** [comment]
@carina29 Have you defined a default district on your system?

**Comment by carina29** [comment]
@MateStrysewske I've tested with default district ( without default region), default region and default district ( all the combinations). With or without selected default region/district the warning for mandatory fields will appear.
Based on the combinations the warning message can contain the region field too: 

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/4c01eaee-610e-4f83-abe6-3272600b7e27)

**Comment by MateStrysewske** [comment]
@carina29 You need to specify a country in the `sormas.properties` file - this is basically necessary for SORMAS to operate properly. Once you've done that, you should be able to create events as long as you don't leave the country dropdown empty, but if you have a country set, this will be auto-populated anyway.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(1c5762c).
