### ISSUE TITLE
Add support for the hide jurisdiction fields feature to contacts [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12807]
### Feature Description

The option to hide jurisdiction fields introduced in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12550 needs to be applied to the contact module as well.

### Added Value/Benefit

Countries that don't use jurisdictions will be able to use the contact module.

### Acceptance Criteria

- [x] If the `HIDE_JURISDICTION` feature is enabled, hide all jurisdiction fields and automatically fill the region, district, and community fields with the respective default options by using the getDefaultInfrastructure method (see CaseCreateForm and CaseDataForm)
- [x] Apply this to contact line listing as well
- [x] If the feature is enabled, the jurisdiction filters and columns in the contact directories are hidden

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(dfc3af7).
