### ISSUE TITLE
Hide jurisdiction-related filters and columns if the HIDE_JURISDICTION_FIELDS feature is enabled [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12810]
### Feature Description

Some filters and columns that are still shown even if the option to hide jurisdiction fields introduced in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12550 is enabled need to be hidden.

### Added Value/Benefit

Consistency; users would get confused if jurisdiction-related filters and columns are still shown.

### Acceptance Criteria

If the `HIDE_JURISDICTION_FIELDS` feature is enabled:

- [x] Hide the jurisdiction-related filters and columns from the case directory except facilities; ensure that the facility-related filters are enabled and filled based on the default jurisdictions
- [x] Hide the jurisdiction-related filters and columns from the sample directory (except laboratory) - for both human and environment samples
- [x] Hide the jurisdiction-related filters and columns from the environment directory
- [x] Hide the jurisdiction-related filters and columns from the person directory
- [x] Hide the jurisdiction-related filters and columns from the task directory
- [x] Hide the jurisdiction-related filters from all four dashboards and the "last reported district" and "outbreak districts" elements from the surveillance dashboard
- [x] Hide the region, district and community fields from the case line listing feature

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(75fa116).
