### ISSUE TITLE
Add dedicated user rights for environment sample pathogen tests [3]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12836]
### Problem Description

Environment users have access to environment samples and their associated pathogen tests. However, in order to grant them the user right to create/edit/delete pathogen tests, they also need to be granted access to human samples because the pathogen test rights have dependencies to the sample view/edit rights. 

This means that it's currently not possible to create a user that has ONLY access to environment samples, but not to human samples.

### Proposed Change

Add dedicated user rights related to pathogen tests associated with environment samples. This is a bit hacky because technically, both types of pathogen tests are identical (i.e. they're the same entity), but the alternative would be to significantly overhaul the way dependencies between user rights work, and that would be a lot more complicated.

### Added Value/Benefit

Environment users won't be required to have access to human samples anymore.

### Acceptance Criteria

- [x] New user rights have been added: `ENVIRONMENT_PATHOGEN_TEST_CREATE`, `ENVIRONMENT_PATHOGEN_TEST_EDIT` and `ENVIRONMENT_PATHOGEN_TEST_DELETE`
- [x] The new user rights have captions (e.g. "Create environment pathogen tests")
- [x] The new user rights are sorted in the environment user right group
- [x] The dependencies mirror those of the respective pathogen test rights for human samples
  - Create and delete depend von ENVIRONMENT_SAMPLE_VIEW, edit depends on ENVIRONMENT_SAMPLE_EDIT
- [x] The `PathogenTestFacadeEjb.deletePathogenTest` method's `RightsAllowed` annotation is extended with the new environment pathogen test delete right
- [x] All code that currently checks pathogen test rights related to environment samples now instead uses the new user rights - including the mobile app
- [x] The default environmental surveillance user no longer has the sample view and pathogen test rights (i.e. they don't have any right in the samples user right group), but instead the new create and edit rights (not the delete right); this needs to be done both in the code as well as with a database migration - this also needs to be applied to the mobile app

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the Default Environmental Surveillance Officer should not have the right to 'Delete environments samples **pathogen tests**'.

**Comment by adinaflorea9** [comment]
Closing ticket as it was determined that deletion rights over pathogen tests associated with environment samples is necessary.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the synchronization from the mobile app to the web app is not working when a user that has no rights over human samples tries to sync new or edited environment samples/ environment samples pathogen tests.

The sync is possible only if the user is given at least the following rights over human samples also:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/306d5a90-4ffe-4fbe-b435-8073635c80c1)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(dfc3af7).
