### ISSUE TITLE
Line ending issue in external email facade test

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#12833]
### Bug Description

There are some tests failing dou to line break encoding unix vs win

### Reproduction Steps

1.Run the test in `ExternalEmailFacadeEjbTest`

`testSendEmailToCasePerson` and `testSendEmailToContactPerson` fails

### Expected Behavior

Test should not fail

### Affected Area(s)

Web app

### SORMAS Version

1.93.0-SNAPSHOT

### Android version/Browser

Test Runner

### User Role(s)

Any user

### Additional Information

See comment: https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12828#discussion_r1426662899

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(1c5762c) - the tests are passing now on Windows machine.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/e44aea46-771f-451d-8ad9-ecfcf95f31c6)
