### ISSUE TITLE
Add validation to the national health ID field [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12841]
### Feature Description

Sending external emails to persons utilises their national health ID to add password protection. However, this requires the national health ID to be correct; otherwise, a password is generated and sent to the user via SMS. In order to make it less probable that an invalid national health ID is in use, the same validation that is already in use should be applied to the field in the person form as well.

### Added Value/Benefit

More reliably correct national health ID.

### Acceptance Criteria

- [x] The same logic that is used in order to identify a correct national health ID when sending external emails is applied to the national health ID field in the person create and edit forms
- [x] If an invalid national health ID is entered, display a warning: "This does not seem to be a correct national health ID" - saving the form should still be possible
- [x] This new logic is only applied to Luxembourg servers

**Comment by MateStrysewske** [comment]
Error message below the field is always shown on non-Luxembourg systems

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - .194.0-SNAPSHOT(6374a28).
