### ISSUE TITLE
Demis - Error has occurred when User click on the download message button 

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12846]
### Problem Description

When user try download message from demis the error has occurred

Screenshot:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/d68a6f48-9e38-47f4-968b-96e62f6c7293)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/778979f0-9c60-4b09-ba51-4438ba5448fd)

### Reproduction Steps

1.Go to https://test-de2.sormas.netzlink.com/
2.Click on Messages button from Navbar
3.Click on download messages button(sometimes twice) for chosen message
4.The error has occurred 

### Expected Behavior

File has downloaded successful, no error message

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.93.0-SNAPSHOT (805282f)

### Android version/Browser

Google Chrome

### User Role(s)

Automation admin, S2S 

### Server URL

https://test-de2.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
@mk-sgent Can you provide log files for this error please?

**Comment by mk-sgent** [comment]
Sure, I added logs in attachment 
[log.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/13858349/log.txt)

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version 1.94.0-SNAPSHOT(dfc3af7).
