### ISSUE TITLE
Environment samples are not restored with the environment, but they are deleted with the environment

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12855]
### Bug Description

When a case that has a sample is soft deleted and then restored, the sample is deleted and restored with the case. When an environment that has a sample is soft deleted and then restored, the sample is deleted with the environment, but not restored with it. 

The behavior should be consistent between the major entities.

### Reproduction Steps

1. Log in as an Admin+National User;
2. Create an environment with a sample (and pathogen test);
3. Delete the environment.
-> the sample and pathogen test are deleted with the environment;
4. Restore the environment;
Actual behavior: only the environment is restored.

### Expected Behavior

To have the behavior consistent with the other major entities, when the environment is deleted and restored, the sample and pathogen test should also be restored with it, if they are soft deleted with it.

### Affected Area(s)

Web app

### SORMAS Version

1.94.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NationalUser

### Server URL

local machine

**Comment by MateStrysewske** [comment]
Fixed by #12853

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(1c5762c).
