### ISSUE TITLE
Synchronization count for environment, environment samples and pathogen tests is broken 

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12856]
### Bug Description

The synchronization count when synchronizing from the web app into the mobile app new entities is broken for environments and their associated samples and pathogen tests.

### Reproduction Steps

1. In the web app, log in with an Admin+NationalUser and in the mobile app with a Default Surveillance Officer who was given all of the rights for environments (and whose jurisdiction is in Region1 District 1);
2. In the web app, with the Admin+NationalUser create the following entities in Region1 District 1: 1 environment, 1 sample associated with that environment, 2 pathogen tests for that sample;
2. In the mobile app, trigger a regular synchronization and observe the entities count.
Actual behavior: the synchronization count says that 0 environments were synced, 2 environment samples, 1 pathogen test and 1 human sample. 

### Expected Behavior

The synchronization count in the above scenario should say 1 environment, 1 environment sample and 2 pathogen tests were synchronized. **Please also take into account the count for the 'Re-synchronize data' type of synchronization and the synchronization both from the web app into the mobile app, and from the mobile app into the web app.**

### Affected Area(s)

Web app, Android app

### SORMAS Version

1.94.0

### Android version/Browser

Android Studio, Chrome

### User Role(s)

Admin+NationalUser, Default Surveillance Officer with rights for Environments

### Server URL

local machine

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behavior:

1. In the mobile app, logged in with a Surveillance Officer that has rights over Environments, trigger a synchronization (to make sure that there are no un-synchronized entities to and from the mobile app);
2. Create a new environment, with an environment sample and pathogen test in the mobile app;
3. Trigger a synchronization;
4. Observe the count at step 1 'Sending new data' and at step 4 'Synchronizing data'.
Actual behavior:
At step 4 the environment, sample and pathogen test are counted in the pulled column even though there are no new entities being pulled from the web app, but only new entities being pushed from the mobile app into the web app.

Expected behavior: If there are no new entities being pulled from the web app, then none should be counted when entities are only being pushed from the mobile app into the web app.

[incorrect count.webm](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/72a05df2-fbb0-4a74-995f-c09524cd8154)

**Comment by MateStrysewske** [comment]
@adinaflorea9 This is expected behaviour that you can also observe when you create e.g. cases in the mobile app. The data is pushed to the server, saved there, and potentially updated (with automated logic), and then the updated data is pushed back to the mobile app (i.e. pulled there). Everything's fine here :)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(1c5762c).
