### ISSUE TITLE
Adjusting of elementIDs to enable bots to use specific elements [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#12865]
### Problem Description

On the Sormas page when creating a new sample, there are the buttons "Cancel" and "Discard" at the bottom.
 
These elements have the same ID "discard" in JavaScript (see screenshots).
As IDs should be unique, we should change it as this leads to problems when used in conjunction with a software robot.

![neue Probe 1](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/62540178/a1ca20f8-74b7-478c-898c-f599c20a4820)
![neue Probe 2](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/62540178/6f9d8479-6ef0-4b73-bbf1-58b7b29e3417)

### Proposed Change

- [] Rename the Cancel ("Abbrechen") to "cancel" 

### Added Value/Benefit

Bots can identify and work with the elements on the screen

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

### Additional Information

- [ ] Check automated tests to still succeed

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(e455ff9).
