### ISSUE TITLE
Hide the jurisdiction related fields from the 'Edit cases' form in bulk edit mode [1]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12902]
### Problem Description

When the featuretype 'HIDE_JURISDICTION_FIELDS' in enabled we do not show in edit and creation forms the fields related to the jurisdiction - responsible region, district, community. But in bulk edit mode, in the cases directory, we still show them.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/5c2b54a2-2851-4fd1-adc8-0725cb48eb8e)

After the edit is done (select a different region, district than those that are set as default) - if the user goes to the regular edit pages of cases they can now see in the 'Place of stay section' the fields for region, district and community that were previously hidden.

### Proposed Change

Hide the responsible region, district and community fields from the 'Edit cases' form in bulk edit mode.

### Added Value/Benefit

Consistency.

### Acceptance Criteria

- [x] hide the fields region, district and community from the 'Edit cases' form in bulk edit mode when the hide jurisdiction fields feature is enabled;
- [x] consider instead the default values set for region, district and community;
- [x] the user should still be able to change the place of stay - the option for home still present, the option for facility still present - but only facilities from the default jurisdiction being possible to be selected (just as in the regular edit forms of cases);

**Comment by carina29** [comment]
I've found some bugs/findings meanwhile I've worked on this ticket and also discussed with @MateStrysewske about the findings.
I've created these tickets: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12917
https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12918

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(dfc3af7).
