### ISSUE TITLE
Change default text for mSERS menu item to "Aggregate"

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#12908]
### Problem Description

As a public health worker I would like to capture Aggregate data in SORMAS.

The current menu item mSERS stands for "Mobile Strengthening Epidemic Response System".  It is primarily used in the languages en-ng and en-gh.  For the languages en-us, it would make sense to have the text as "Aggregate" to not confuse users from other regions of the world.

### Proposed Change

Change the menu item (variable) mSERS to "Aggregate" when displayed in en-us (default).

The translation for mSERS should still be mSERS when the SORMAS language selected is en-ng or en-gh - this can be adjusted in CrowdIn.

### Added Value/Benefit

Displaying "Aggregate" as a menu item is universally easier to understand for global users as opposed to the current region-specific "mSERS".  Regional users should still see "mSERS".

### Acceptance Criteria

- [ ] "Aggregate" menu item is visible by default (en-us language/variable)
- [ ] "mSERS" menu item translation is visible for en-ng and en-gh (translations need to be done in Crowd-In for new variable)
- [ ] All references to "mSERS" are updated to "Aggregate" on the related GitHub wiki pages

**Comment by adinaflorea9** [comment]
Reopening the ticket as the change needs to be done on android app as well.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.96.0-SNAPSHOT(b627e9b).

**Comment by leventegal-she** [comment]
Keeping  "mSERS" for en-ng and en-gh is the resposibility of Crowdin
