### ISSUE TITLE
Hide jurisdiction related fields in the 'Search person' and duplicate detection forms [2]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12900]
### Problem Description

When the featuretype 'HIDE_JURISDICTION_FIELDS' is set to true, we can still see the jurisdiction related fields in the forms of 'Search person' (that can be accessed from any creation form via the 'magnifying glass' icon) and in the 'Duplicate persons' and 'Duplicate detection' for cases, contacts any other entity that we have a duplicate detection for.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/e89a84ae-3863-4c59-a814-a6f65eaa50ff)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/fd170b69-20b8-4e12-acfb-344601d8ef59)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/ce0252dd-9ea6-485c-b051-806edfe8eda6)

### Proposed Change

Hide jurisdiction related fields when the 'HIDE_JURISDICTION_FIELDS' is set to true in duplicate detection forms and search person form.

### Added Value/Benefit

Consistency.

### Acceptance Criteria

- [ ] if featuretype  'HIDE_JURISDICTION_FIELDS' is set to true, hide jurisdiction related fields, columns from the following forms: Search person form, duplicate detection for persons, duplicate detection for cases, contacts, any other entity for which we have duplicate detection enabled;
- [ ] use the saved default jurisdiction values configured on the respective environment instead.

**Comment by adinaflorea9** [comment]
Extend the behavior to:
In the contact create form or in the contact edit form, when the user uses the button 'Choose source case' in that grid we still display the districts of the cases and we also display cases that are not from the default jurisdiction set -> hide the cases that are not from the default jurisdiction and also hide the column responsible district.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/a1116f9c-5014-43cd-ba4e-3fb008bbddcc)

**Comment by MateStrysewske** [comment]
@adinaflorea9 Field is hidden in the PR associated with this issue. Concerning cases from other jurisdictions being shown, I've decided that's fine. On a properly configured system, this won't happen in the first place; and if it does, I don't really see a reason against it.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(428fd6e).
