### ISSUE TITLE
Error when accessing the configuration menu without outbreak or region access

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12914]
### Bug Description

When trying to access the configuration screen without access to the Outbreaks and Regions view, e.g. with a user that can only configure line listings, errors are displayed because the system tries to navigate to the Regions view by default, which the user is unable to access.

### Reproduction Steps

1. Configure a user role to only have access to the line listings configuration among all the configuration screens
2. Log in with that user and open the configurations screen
3. Observe the error messages; you can click on the "Line listing" view to actually properly access it after dismissing the errors

### Expected Behavior

The user should be redirected to a screen they can actually access.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.94.0-SNAPSHOT

### Android version/Browser

Chrome

### User Role(s)

Any user role

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(bc47e1d).
