### ISSUE TITLE
NPE will be thrown when the jurisdiction of cases is changed from bulk edit mode

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12917]
### Bug Description

Set HIDE_JURISDICTION feature configuration to false and try to change the Region, District and Community in bulk edit mode for a case/some cases

=> NPE will be thrown

### Reproduction Steps

1.Set HIDE_JURISDICTION feature configuration to false 
2. Enter bulk edit mode from Cases directory
3. Select a case and try to edit it
5. In the Edit cases form change at first the place of stay to "Home" and after that change the Region, District, Community and Save it ( it's important to change on the mentioned order the "Place of stay" to "Home" at first)
Screenshot after editing: 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/51304117-4ac0-4337-b2bc-2b2b36433da9)
6.  Click Edit Data or Transfer cases from the pop -up (the same NPE will be thrown for both actions)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/d751b9cd-9ba7-4485-bab1-c616b53f24a7)
8. NPE will be thrown
...
[Logs_NPE_TransferCases.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14054625/Logs_NPE_TransferCases.txt)

**NOTE:** The bug is not reproducible for every case.

### Expected Behavior

NPE should not be thrown.

### Affected Area(s)

Web app

### SORMAS Version

1.93, 1.94

### Android version/Browser

Chrome

### User Role(s)

National User

**Comment by MateStrysewske** [comment]
@carina29 Can't reproduce this; I'll assign you so that you can fix it ;)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(bc47e1d).
