### ISSUE TITLE
Don't disable feature configurations that are already disabled

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12930]
### Bug Description

During server startup, SORMAS is checking whether there's any feature configuration in the database that has a disabled dependent feature configuration. If such a configuration is found, it is disabled.

However, this will be repeated on every startup because the code is not checking whether the depending feature configuration is already disabled. This a) slows startup time and b) potentially interferes with read-only instances.

### Reproduction Steps

1. Disable a feature configuration that has depending feature configurations, e.g. case surveillance
2. Disable one of the depending feature configurations, e.g. contact tracing
3. Put a breakpoint in FeatureConfigurationService line 190
4. Observe that the contact tracing feature configuration is saved even though it has not changed (since it was already disabled before)

### Expected Behavior

Feature configurations that are already disabled should be excluded from this logic.

### Affected Area(s)

Web app

### SORMAS Version

1.95.0-SNAPSHOT

### Android version/Browser

Any browser

### User Role(s)

Doesn't matter

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(428fd6e).
