### ISSUE TITLE
Exposure data tab has error when edit/save form

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12983]
### Problem Description

When the exposure form has filled after click on DONE button the error has occurred. 

Logs from the local machine at the time of the error:
[error exposures.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14329623/error.exposures.txt)

### Reproduction Steps

1.Go to the :https://test-auto.sormas.netzlink.com/
2.Log as National User or Admin User
3.Click on Cases from navbar
4.Create a new Case
5.Go to EPIDEMIOLOGICAL DATA tab in edit Case directory
6.Mark YES option for "EXPOSURE DETAILS KNOWN"
7.Click on New entry
8.Fill all mandatory fields, check all exposure Details checkboxes to NO option
9.Click on DONE button
Actual behavior: The error message has occurred

### Expected Behavior

No error should appear.

Screenshot:

<img width="530" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/0e319d32-d650-417a-9332-8366a53e86e1">

<img width="754" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/5b6b9113-0b8f-48d4-9dee-a575b28c0e07">

[Exposure_logs.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14329464/Exposure_logs.txt)

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.95.0-SNAPSHOT (17f685f)

### Android version/Browser

Google Chrome

### User Role(s)

Automation Admin, National User, 

### Server URL

https://test-auto.sormas.netzlink.com/  ,  https://test-de.sormas.netzlink.com/

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(d5a2fe2).
