### ISSUE TITLE
ERROR: permission denied for table featureconfiguration (when CASE_SURVEILANCE is set to false)

### ISSUE THREAD

**Issue by tnako-sg** [SORMAS-Foundation/SORMAS-Project#12982]
### Bug Description

Getting:
ERROR: permission denied for table featureconfiguration

### Reproduction Steps

1. CASE_SURVEILANCE is set to false
2. db_read_only is set to true
3. restart docker and Sormas fails to come-up with ERROR: permission denied for table featureconfiguration

### Affected Area(s)

Web app

### SORMAS Version

1.93.0

### Android version/Browser

any

### User Role(s)

any

**Comment by MateStrysewske** [comment]
A fix for this will come in the upcoming version (1.95.0). Closing this issue as duplicate of #12930
