### ISSUE TITLE
Change automatic case classification rules for Covid-19 for Luxembourg

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#13000]
### Problem Description

The automatic case classification rules for Covid-19 don't apply to the way cases should be handled in SORMAS in Luxembourg.

### Proposed Change

Since cases are mainly created through lab reports coming in via eSanté, and no symptoms are transferred to SORMAS this way, a positive lab result has to be sufficient in order to automatically classify a case as positive. In addition, the existence of a negative lab result has to lead to an automatical classification as "Not a case".

### Added Value/Benefit

Cases will be automatically set to a correct classification after lab messages from eSanté are automatically processed.

### Acceptance Criteria

These changes only apply to Luxembourg systems (i.e. systems with the locale LU); all other systems still need to use the existing classification rules.

- [ ] For the `confirmed` classification, only a positive test result for CORONAVIRUS is required, irrespective of the test type used
- [ ] Add a new `notACase` classification rule that is applied when NO positive test result is present, but a negative result is present
- [ ] Add tests that verify this behaviour

The expected outcome on Luxembourg systems is that cases with at least one positive lab result are always classified as confirmed, even if there are negative results, and that cases that have ONLY negative results are automatically classified as not a case. The suspect and probable classifications can stay as they are.

**Comment by sergiupacurariu** [comment]
Case clssification description for Luxembourg users:  
- there are 2 fields where the case classification value is stored
         - systemCaseClassification
         - caseClassification (this value is seen in UI by the user)

On case save:     
- if the Automatic CaseClassification featureConfiguration is true then
  - automatic classification is executed
  - if the automatic case classification differs from the existing systemCaseClassification value
    - then the value is changed and also the caseClassification is changed which is seen in the UI by the user no matter what the user sets in the caseClassification field
   - if the automatic case classification returns the same value as the one already existing on the systemCaseClassification field then 
     - the new value set by the user in the case classification field is the one that is saved
                
    - so in case the other changes made on the case trigger changes in case classification, then it does not matter what the user sets manually on the case classification field, the system will always save the automatic classification value
    - if the user is not satisfied with the automatic case classification value, then can go and change it manually but only if no other changes that would trigger changes in classification are made. In this case the manual set will be saved.

**Comment by XavCol** [comment]
Note that when a case is classified as confirmed with a positive laboratory result, if a negative result is received, the case should remain as confirmed. Conversely, if a case is defined as not a case by a negative result, and a positive test is received, the classification should change to confirmed.

**Comment by richardbartha** [comment]
Tested on local setup version 1.96.0-SNAPSHOT ([93d6439](https://github.com/sormas-foundation/SORMAS-Project/commits/93d6439e42f5955f31cb43246979b340ff50cf26)).
