### ISSUE TITLE
Create extended documentation for Audit logs

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13028]
### Problem Description

There is documentation available at:
https://github.com/SORMAS-Foundation/SORMAS-Project/wiki/Auditing-&-Data-History

This is not sufficient as it's not clearly described:
a.) What is logged 
b.) How can the log be accessed and read 

### Proposed Solution

Extend the documentation with a complete list of what is logged and how to access the log to be able to read and process it if needed

**Comment by leventegal-she** [comment]
The wiki page can be extended by getting more details form the epic https://github.com/SORMAS-Foundation/SORMAS-Project/issues/7904
