### ISSUE TITLE
Bulk action - send emails with uploaded attached documents [5]

### ISSUE THREAD

**Issue by sergiupacurariu** [SORMAS-Foundation/SORMAS-Project#13043]
### Feature Description

Sormas system will be able to send emails with an attached document to multiple recipients of the entities selected in "Bulk edit mode". These recipients are the persons behind the cases, contacts, event participants, and travel entries. The user also wants to know which are the UUIDs of the entities for which this task could not be performed due to various reasons. The attachment should be saved once for all emails sent with the same document attached.

### Added Value/Benefit

The Sormas user will be more efficient in handling operations involving multiple entities. Also will be able to easily check which entities did not work properly.

### Acceptance Criteria

- [x] Grids involved - Cases, Contacts, Event participants, Travel Entries
- [x] Add button to bulk action
- [x] In order for the bulk action button to be active the user must have the following rights:  PERFORM_BULK_OPERATIONS and EXTERNAL_EMAIL_SEND
- [x] Emails to persons who lack the information needed for manual email sending will be skipped and the user will be informed at the end of the bulk process (Errorhandling: UUIDs plus reason (grouping: not eligible, server connection problems, other))
- [x] Treat each unexpected error during the bulk process to avoid blocking it
- [x] Save the uploaded document and link the entities of successful emails to the document
- [x] Restrict the type (docx, pdf, jpg, png,gif) of uploaded documents to ones allowed to be attached to manual email.

### Additional Information

Open questions:
1) Will the entity be linked to the document if the email was not sent?
- linking only on successful sending
2) How many documents could be uploaded separately?
- can be configured in the properties: Default 5 max

**Comment by richardbartha** [comment]
Tested on web local setup version 1.96.0-SNAPSHOT ([93d6439](https://github.com/sormas-foundation/SORMAS-Project/commits/93d6439e42f5955f31cb43246979b340ff50cf26)).
