### ISSUE TITLE
Add feature configuration for Self Reporting

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13065]
### Feature Description

For the new module of Self-Reporting we would need a feature configuration.
By default the Self-Reporting module is disabled and needs to be enabled explicitly.

### Added Value/Benefit

With the feature configuration SORMAS users can decide whether they want to enable Self-Reporting or not.
As we do not have yet a third party which automatically delivers data and the only way how Self-Reporting data will go into the system, it's important that it's disabled by default

### Acceptance Criteria

- [x] Feature configuration to enable/disable Self-Reporting

**Comment by carina29** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.96.0-SNAPSHOT ([1d1eb96](https://github.com/sormas-foundation/SORMAS-Project/commits/1d1eb9b022c351162989e1c35f6dfe75bb2bf151))
