### ISSUE TITLE
Add a self Reporting directory (UI) [3]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13068]
### Feature Description

To be able to use the Self-Reporting module we have to introduce a Self-Reporting directory when the feature is enabled.
There will be another menu item "Self-Reports".
The directory allows filters and searches as we are used to do in the other directories
The following data fields and colums will be needed:
- Type (Contact, Case)
- Case Reference for Contacts (new Field)
- Disease
- Disease Variant (optional) => (not in Grid)
- Test Results (optional)
- Last Name
- First Name
- Contact Details (E-Mail, Phone, Adress)
- NationalHealthID
- ReportDate
- Status (including the deleted status)
- Comment (not in Grid)

@markusmann-vg these 2 button probably should go into other tickets related to Self-reporting:
Additionally we will have buttons in the gris that allow users to process the self-reported message
- Process ( should go into to the ticket which will be created for the processing of Self Reporting)
- Delete (could be included here https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13085)

### Added Value/Benefit

With the UI the users with the corresponding rights can view, search, filter Self-reported messages as well as process 
them.

### Acceptance Criteria

- [x] Directory is shown
- [x] #13069
- [x] When Self-Reporting is enabled the menu item is shown and active

**Comment by richardbartha** [comment]
Tested on web local setup version 1.96.0-SNAPSHOT ([93d6439](https://github.com/sormas-foundation/SORMAS-Project/commits/93d6439e42f5955f31cb43246979b340ff50cf26)).
