### ISSUE TITLE
Extend the contacts with Case Reference Number & add case reference number to cases

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13067]
### Feature Description

To be able to add a case-reference number to risk contacts and cases we have to add it 
- in the database
- in the Create & Update Forms
- Display it in the grid
- Add it to the search, like we did for the [Search by NationalID is not consistently working in all locations](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13029) 

### Added Value/Benefit

With the case reference people who self-declare themselves as Risk Contacts can link themselves to a case without knowing more about the case or having to know more about the case.

### Acceptance Criteria

- [x] Case Reference is available in all relevant create and update forms
- [x] Case Reference is shown in the grids
- [x] Case Reference is searchable
- [x] Case Reference is included in the exports and imports
- [x] Case Reference is part of the data dictionary and data protection dictionary
- [ ] Case Reference is only shown when self reporting feature is enabled

**Comment by richardbartha** [comment]
Tested on web local setup version 1.97.0-SNAPSHOT ([2807299](https://github.com/sormas-foundation/SORMAS-Project/commits/280729977047d850e3319ba1a867e001a8f4c7b5)).
