### ISSUE TITLE
Add user rights for self Reporting processing

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13066]
### Feature Description

To be able to process Self-Reporting messages we need different rights.
Some of them might not be applicable right now but may be needed in the future.

- [x] View and fetch self-reported messages
- [ ] Import & Export self-reported messages
- [x] Delete self-reported messages
- [x] Add the new rights to the user-role and user-rights documentation

### Added Value/Benefit

Not every user should have the same rights and therefore this new module needs some rights that can be added to other roles or be part of a new role.

### Acceptance Criteria

- [ ] Users with the rights should be able to view and fetch self-reported messages
- [ ] Users with the rights should be able to import & Export self-reported messages
- [ ] Users with the rights should be able to delete self-reported messages
- [ ] The new rights of to the user-role and user-rights are added to the documentation

**Comment by markusmann-vg** [comment]
User rights will be covered with the implementation of CRUD and Import/Export for Self-Reporting

**Comment by richardbartha** [comment]
Tested on web local setup version 1.97.0-SNAPSHOT ([2807299](https://github.com/sormas-foundation/SORMAS-Project/commits/96556782678d06c0ed75497e8ce36a5320c4d741)).
