### ISSUE TITLE
Error when creating cases with user role including `Has optional health facility`

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#13077]
### Bug Description

When creating a new user role (Users > User Roles > Create new user role) and assigning the `Has optional health facility`, an error occurs when a user with this user role tries to create a new case.

### Reproduction Steps

1. Create new user with user role `Has optional health facility` defined.
2. Login as this user.
3. Navigate to Cases > New Case
4. Error appears.
...

### Expected Behavior

No error appears.

### Affected Area(s)

Web app

### SORMAS Version

1.95.1

### Android version/Browser

Chrome

### User Role(s)

Hospital Informant (default role with Facility attached to it)

### Additional Information

Error log by @obinna-h-n : [hosp-info-casecreate-error-sormas-log.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/15012464/hosp-info-casecreate-error-sormas-log.txt)

**Comment by richardbartha** [comment]
Issue is not fixed! Error is still happening when a hospital informant wants to create a case!
[log.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/15244874/log.txt)

**Comment by obinna-h-n** [comment]
@richardbartha , this fix is expected to be available in the next release. what version did you test on. can you test with the dev branch to confirm your findings again.

**Comment by obinna-h-n** [comment]
thanks for this update. I will check this again today.

**Comment by obinna-h-n** [comment]
Hi @richardbartha ,
I have just tested this again with the development branch as of this moment.
This error is not coming up.

Can you share the details of the user you have used to test, your error maybe related to another problem not what has been reported in this issue.

I will ask @Candice-Louw to check from her side as well.

**Comment by obinna-h-n** [comment]
I will mark this issue as closed. thank you @Candice-Louw.

**Comment by richardbartha** [comment]
Retested on latest development branch together with @obinna-h-n the issue is still there or at least a part of it. 
Reopening the ticket in order to solve the remaining part of the issue!

**Comment by obinna-h-n** [comment]
Hi @richardbartha, as a follow up and after further testing, the case we discussed last is not related to this issue, but with how "Default" the infrastructure records are configured. It will be better to create a new issue to resolve that case. happy to discuss about this.
