### ISSUE TITLE
Add an Export (basic & detailed) and Import to Self Reporting [3]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13070]
### Feature Description

With the new Module Self-Reporting the users with the needed rights can also export Self-reported messages and import self-reported messags.
The export can be done as basic or detailed export

### Added Value/Benefit

As it's currently the only way how self-reported messages can enter the system, the import is essential.
The export is a basic functionality which we offer for every entity

### Acceptance Criteria

- [x] Import is possible, an import template can be provided, error handling for failed imports is available (as we do it for other imports
- [x] Basic Export is possible 
The basic export will contain all the fields which are displayed in the grid:
- Uuid
- Report date
- Type
- Disease
- First name
- Last name
- Birth date
- Sex
- District
- Address
- Phone number
- Email
- Responsible user
- Processing status
- Reason for deletion ( only when the "Deleted self reports" are selected from the grid)

- [x] Detailed Export is possible
  The detailed export will contain the following fields:
   - Uuid
   - Type
   - Report date
   - Case reference
   - Disease
   - Disease details
   - Disease Variant
   - Disease variant details
   - Firstname
   - Lastname
   - Sex
   - District
   - Street
   - House number
   - Postal Code
   - City
   - Birth date
   - National health id
   - Email
   - Phone number
   - Date of test
   - Date of symptoms
   - Workplace
   - Date of workplace
   - Isolation date
   - Contact date
   - Comment
   - Responsible user
   - Investigation status
   - Processing status
   - Deletion reason
   - Other deletion reason
 
- [x] Add user rights for Import/Export

### Implementation Details

Here is the structure of the file received when a self-report is made
 
The import template will contain the following fields: 
   - Type
   - Report date
   - Case reference
   - Disease
   - Disease details
   - Disease Variant
   - Disease variant details
   - Firstname
   - Lastname
   - Sex
   - Day of birth
   - Month of birth
   - Year of birth
   - National health id
   - Email
   - Phone Number
   - LocationDto address fields:
             - Continent
             - Subcontinent
             - Country
             - Region
             - District
             - Community
             - Community contact person
             - City
             - Area type
             - GPS latitude
             - GPS longitude
             - GPS accuracy in m
             - Postal code
             - Street
             - House number
             - Additional information
             - Address type
             - Address name/description
             - Facility type
             - Facility
             - Facility name & description
             - Contact person first name
             - Contact person last name
             - Contact person phone number
  - Date of test
  - Date of symptoms
  - Workplaces
  - Date workplace
  - Date of isolation
  - Date of contact
  -  Comment
 
The file is processed by an ETL job in the "Care+" section.

**Comment by richardbartha** [comment]
Tested on web local setup version 1.97.0-SNAPSHOT ([6b4e5c7](https://github.com/sormas-foundation/SORMAS-Project/commits/6b4e5c7713f53837e751852c269b51c2146cfe02)).
