### ISSUE TITLE
Relevance status filter is not working in Environments grid

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#13074]
### Bug Description

Try to change the filter value from Active to Archived, Active and archived, Deleted and check that the filter will not work and the grid will not be refreshed with the new values.  Also a flickering (slightly moving of the elements to right and back to left) of the screen with be visible
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/0c73ea01-9c39-4212-b3b7-10939e9a59c3)

### Reproduction Steps

1. Try to change the filter value from Active to Archived, Active and archived, Deleted.

### Expected Behavior

The filter should work properly: based on the relevance status the grid should be refreshed with new values and the screen should not flicker ( component should not move to right and back to left)

### Affected Area(s)

Web app

### SORMAS Version

1.96.0-SNAPSHOT

### Android version/Browser

Chrome

### User Role(s)

Configured user

**Comment by richardbartha** [comment]
Tested on web local setup version 1.96.0-SNAPSHOT ([93d6439](https://github.com/sormas-foundation/SORMAS-Project/commits/93d6439e42f5955f31cb43246979b340ff50cf26)).
