### ISSUE TITLE
Linked SelfReporting message should be shown as side component in UI [2]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13084]
### Feature Description

Link the processed SelfReporting message to the according entity / entities and show in UI

### Added Value/Benefit

Link the processed SelfReporting message to the according entity / entities and show in UI

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

**Comment by richardbartha** [comment]
Tested on web local setup version 1.97.0-SNAPSHOT ([6b4e5c7](https://github.com/sormas-foundation/SORMAS-Project/commits/6b4e5c7713f53837e751852c269b51c2146cfe02)).
