### ISSUE TITLE
Change "Monkeypox" to "Mpox"

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#13082]
### Problem Description

The name "Monkeypox" is being phased out in the international health context and replaced with "Mpox" instead.  This is based on an announcement by the WHO on 28.11.2022 here: https://www.who.int/news/item/28-11-2022-who-recommends-new-name-for-monkeypox-disease.

### Proposed Change

Change "Monkeypox" to "Mpox" throughout SORMAS, including the
- [x] UI
- [x] Data Dictionary
- [x] Export/Import files
- [x] Aggregate forms

### Added Value/Benefit

International stipulations from the WHO.

### Acceptance Criteria

- [x] "Monkeypox" is replaced by "Mpox" throughout all of SORMAS ui module.
- [ ] "MONKEYPOX" is replaced by "MPOX" throughout all of SORMAS backend.

### Mockups

Case/Contact/EP information:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/8c357812-7f54-44d8-b8e4-00c53063df0f)
Aggregate Reports:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/17756c99-f414-4301-843c-e102fe2c9c27)
Data Dictionary:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/bc3efc4d-2b45-4f16-8ce8-0d71c28a86ce)

### Additional Information

The module was first introduced to SORMAS here: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/366

**Comment by obinna-h-n** [comment]
Hi @Candice-Louw , for now we will change the caption only to reflect this change at the user interface level.
The enum value change at the backend will require careful review before implementing.
