### ISSUE TITLE
Add an edit/delete/archive functionality for Self Reporting messages (UI) [3]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13085]
### Feature Description

Backend is already available
=> Edit form needs to be added

### Added Value/Benefit

To be able to edit/archive-dearchive/delete-restore self reported messages

### Acceptance Criteria

- [x] corresponding rights are added 
- [ ]
- [ ]

**Comment by richardbartha** [comment]
Tested on web local setup version 1.97.0-SNAPSHOT ([2807299](https://github.com/sormas-foundation/SORMAS-Project/commits/96556782678d06c0ed75497e8ce36a5320c4d741)).
