### ISSUE TITLE
Update Data Protection for certain Data Fields [5]

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#13093]
### Problem Description

In order to be inline with data protection regulations in Luxembourg, certain data fields have to be updated.  Some are applicable to SORMAS overall, while others are applicable only to Luxembourg (see details below).

### Proposed Change

Tabs from the data dictionary:

<hr/>

### Person

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Person.birthdateMM | birthdateMM | Number | - |

Proposed (for all servers and instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Person.birthdateMM | birthdateMM | Number | Personal |

(Apply to all servers).

<hr/>

### Location

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Location.city | city | Text | personal |

Proposed (only for Luxembourg instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Location.city | city | Text | - |

(Apply removal of data protection restrictions for this field, but only if the server locale is set to Luxembourg)

<hr/>

### Case

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| CaseData.healthConditions | healthConditions | HealthConditions | - |
| CaseData.postpartum | postpartum | YesNoUnknown | - |
| CaseData.trimester | trimester | Trimester | - |

Proposed (for all servers and instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| CaseData.healthConditions | healthConditions | HealthConditions | sensitive |
| CaseData.postpartum | postpartum | YesNoUnknown | sensitive |
| CaseData.trimester | trimester | Trimester | sensitive |

(Apply to all servers).

<hr/>

### Task

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Task.creatorComment | creatorComment | Text | - |
| Task.assigneeReply | assigneeReply | Text | - |

Proposed (for all servers and instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Task.creatorComment | creatorComment | Text | -  : Add GDPR notice (pop-up) |
| Task.assigneeReply | assigneeReply | Text | -  : Add GDPR notice (pop-up) |

(Apply to all servers).

<hr/>

### Event

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Event.srcFirstName | scrFirstName | Text | - |
| Event.srcLastName | scrLastName | Text | - |
| Event.srcTelNo | scrTelNo | Text | - |
| Event.srcEmail | scrEmail | Text | - |

Proposed (for all servers and instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Event.srcFirstName | scrFirstName | Text | sensitive |
| Event.srcLastName | scrLastName | Text | sensitive |
| Event.srcTelNo | scrTelNo | Text | sensitive |
| Event.srcEmail | scrEmail | Text | sensitive |

(Apply to all servers).

<hr/>

### Action

<hr/>

Current:
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Action.description | description | Text | - |

Proposed (for all servers and instances):
| Field ID | Field | Type | Data protection |
|---|---|---|---|
| Action.description | description | Text | - : Add GDPR notice (pop-up) |
| Action.description | Comments on execution| Text | - : Add GDPR notice (pop-up) |

(Apply to all servers).

<hr/>

### Added Value/Benefit

Enhanced data protection and compliance.

### Acceptance Criteria

- [ ] All fields (listed above) have new data protection attributes applied.

**Comment by sergiupacurariu** [comment]
@markusmann-vg @xavier-calland Regarding the request to remove "Personal" data protection from  the Location.city field. The same field is also marked as "Sensitive". This would also trigger the hiding of this field. Should we also remove the "Sensitive" data protection from Location.city in case of Luxemburg servers?

**Comment by sergiupacurariu** [comment]
Regarding the proposed changes for Location.city field. If the "Sensitive " annotation remains the result will as well be 
 the pseudonymization of this field. If we want to have this field visible in any case then I think we should also treat the "Sensitive" annotation in the same way like "Personal" annotation.

**Comment by markusmann-vg** [comment]
yes, we can remove it

**Comment by sergiupacurariu** [comment]
Additional task emerging from the changes in this ticket: Data Protection Dictionary and Data Dictionary generation flow will be updated to include in the Description the servers where @Personal or @Sensitive do not apply.

**Comment by sergiupacurariu** [comment]
@markusmann-vg  Regarding the Action.description field, an extensive investigation into the Vaadin components revealed that the component behind the Action.description which is a RichTextArea field does not have a connector to support a Focus listener. That means that the user will not be able to see the GDPR notice when they click on the field the same way it was implemented in the Task form. Having this situation two variants have been identified:
- keep the same component and show the GDPR notice after the user finishes the comments and exists the field
- change the RichTextArea component to a simple TextArea component where it is possible to show the GDPR message when the user focuses on the field. 
The difference between these two components is that on RichTextArea component it is possible to format the text.
Given the above situation please let me know which variant it is suitable to choose?
