### ISSUE TITLE
[INCOMPLETE] Add mapping to the E-Santé Adapter

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13143]
### Feature Description

    - Add date of result

### Added Value/Benefit

another value that is automatically prefilled and does not have to be added manually

### Acceptance Criteria

- [ ] Map "date of result" to the according SORMAS value 
- [ ]
- [ ]

**Comment by XavCol** [comment]
Hi, 
For the "Date of result": in the metadata excel file sheet SARS it is mentioned as Diagnostic date:
_Diagnostic date ("when the biologist validates the result"): as the identification of the disease is done at the section level, we propose to add this date on the section, via the author (but without repeating the information about the author). For XSD validation reasons, we have to keep the tags even if they are empty

**Comment by XavCol** [comment]
I have this sentence too:
_Diagnostic date: mandatory, but if not present, the diagnostic date is approximated by the document date (ClinicalDocument/effectiveTime) = the result date_

**Comment by leventegal-she** [comment]
@xavier-calland 
For the *Diagnostic date* value we need information about how to parse from a CDA xml: tag path, code etc.

What does **approximated** mean in your above sentence: * the diagnostic date is approximated by the document date*?
Should we set the result date as diagnostic date or it should have a some days difference?

**Comment by XavCol** [comment]
@leventegal-she 
For Covid, Diagnostic date = the result date
this date is the time value on the section, via author : 
If not present, then use the clinicalDocument/effectiveTime
```
 <author>
                        <time value="20190302"/>
                        <assignedAuthor>
                                   <id/>
                        </assignedAuthor> 
            </author>
            <entry>………..
```

**Comment by leventegal-she** [comment]
@XavCol 

Do we need a another called *Diagnostic date* in SORMAS or we just need to map this date from the CDA xml into the *Date of result* field of the pathogen test?

**Comment by XavCol** [comment]
> @XavCol
> 
> Do we need a another called _Diagnostic date_ in SORMAS or we just need to map this date from the CDA xml into the _Date of result_ field of the pathogen test?

@leventegal-she we can simply map it to Date of result

**Comment by markusmann-vg** [comment]
covered with https://github.com/SORMAS-Foundation/SORMAS-Luxembourg/issues/2

**Comment by richardbartha** [comment]
Tested on localhost version 1.99.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/0c557021cc987a83391e4d054f44f55ede18e358)
