### ISSUE TITLE
Restore User Synchronization Button and Ensure Proper Keycloak Synchronization Configuration

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13140]
### Problem Description

As a system administrator, I want to restore the missing user synchronization button and ensure proper synchronization with Keycloak through correct configuration, so that user management can be handled efficiently within the SORMAS system.

### Proposed Change

Please refer to the SORMAS-Keycloak Integration Documentation for guidance on how to check and configure the synchronization settings.
Ensure that the steps for manually adding the synchronization button are clearly outlined in the configuration documentation.

### Added Value/Benefit

Restoring existing functionality

### Acceptance Criteria

1. The user synchronization button should be visible in the UI.
2. Clear documentation should be provided, pointing to the specific section that explains how to configure and restore the button if it disappears.
3. The system administrator should be able to manually add the button through configuration.
4. Keycloak synchronization should be verified as functioning correctly after the button is restored.
5. The documentation should highlight where to check the configuration in case synchronization issues persist.

**Comment by richardbartha** [comment]
Tested on localhost 
https://github.com/SORMAS-Foundation/SORMAS-Project/commits/50bf45e89377f298251eb98552844e66ecca33ed
