### ISSUE TITLE
Phone Number Validation for E-Santé Reports – Remove and Store Non-Numeric Text

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13147]
### Feature Description

When importing an E-Santé report, some laboratories mistakenly include text in the phone number field, such as "(Mother)" after the phone number. Since we validate phone numbers and need them for SMS communication, this issue prevents proper validation.

### Added Value/Benefit

Ensure phone numbers are formatted correctly for validation and further use (such as SMS sending).
Retain any additional information provided in the phone number field in the comment section, so no information is lost.

### Acceptance Criteria

**Phone Number Validation:**

- The phone number field must be validated to ensure it only contains numeric values, with optional accepted characters (e.g., "+" for international numbers).
- Any non-numeric text (such as words or phrases in parentheses) must be identified and removed from the phone number field.

**Preservation of Removed Text:**

- if the phone number field does not contain a valid phone number then the **whole field** must be appended to the general comment field.
- The text must be prefixed with: (automatically removed from Phone-Nr): [removed text].
- A line break must separate the newly appended information from any existing content in the comment field.
- Existing content in the comment field must remain intact; no overwriting should occur.

**Successful SMS Sending:**

- After validation and text removal, the phone number must be in a format that can be successfully used for SMS sending.

**General Comment Field Updates:**

- If there is no comment field present, one should be created and populated with the removed text.
- If a comment field already exists, the removed text must be appended, maintaining the integrity of the original comments.

### Implementation Details

- Implement validation for the phone number field to ensure it only contains valid numeric values.
- If the field contains non-numeric text (e.g., text in parentheses), automatically remove the text that does not belong to the phone number.
- Preserve the removed text by appending it to the general comment field of the report.
- Ensure that the existing comment field is not overwritten but updated by adding the new information with a line break.
- Example of how the comment field should be updated:
  "(automatically removed from Phone-Nr): Mother"

**Comment by richardbartha** [comment]
Tested on localhost version 1.99.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/0c557021cc987a83391e4d054f44f55ede18e358)
