### ISSUE TITLE
Enable/Disable Automatic/Manual Case Classification Customization Per Disease [2]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13150]
### Feature Description

Currently, it is not possible to configure the "Case Classification" and "Automatic Case Classification" options individually for each disease in SORMAS.
Implement the option to individually configure the "Case Classification" and "Automatic Case Classification" for each disease in SORMAS.
Allow the configuration to be managed through the SORMAS Properties settings file.
The following should be the default values:

- Manual Case Classification Calculation: Enabled
- Automatic Case Classification: Enabled

### Added Value/Benefit

Introducing this functionality would greatly improve the workflows of public health authorities by allowing more flexibility in managing case classifications based on specific disease needs.
This feature will enable health departments to adjust case classification workflows according to the specific requirements of different diseases, increasing flexibility and efficiency in case management.

### Acceptance Criteria

- [x] A configurable setting to enable/disable for all diseases at once:
- [x] A configurable setting for each disease in the SORMAS Properties to enable/disable:

Automatic Case Classification
Manual Case Classification Calculation

- [x] Defaults should be:

Manual Case Classification Calculation: Enabled
Automatic Case Classification: Enabled

- [x] SORMAS Admins should be able to customize these settings without any further technical intervention.

**Comment by leventegal-she** [comment]
Added configuration properties:
`caseClassification.ALL`
`caseClassification.{Disease}`: eg. *caseClassification.CORONAVIRUS*, *caseClassification.CHOLERA*, etc.

Possible values:
`DISABLED`, `MANUAL`, `AUTOMATIC`, `MANUAL_AND_AUTOMATIC`

**Comment by XavCol** [comment]
The customization per disease should include the archive period and deletion period too.

**Comment by markusmann-vg** [comment]
@xavier-calland 
This cannot be included in this ticket as it is far more complex and this feature would imply huge impact on the whole SORMAS system regarding data protection and deletion concept. If this is needed, we should create an epic "Disease Management" where this configuration option is one task to do. 
This should also be discussed with the SORMAS Foundation and it could also be prepared by the SF.

**Comment by richardbartha** [comment]
Tested on localhost version 1.99.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/0c557021cc987a83391e4d054f44f55ede18e358)

There are edge cases however that should be handled somehow in the future
 ex: a case having multiple pathogen tests that whould trigger automatic case clasification, if you change the case disease the clasification and manual calculation does not work correctly it always resets to default not yet classified
