### ISSUE TITLE
Hide Case Classification for RSV and Automatically Set Default Values [1]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13156]
### Problem Description

For RSV cases, the case classification process should be hidden, as every entered case is automatically considered a confirmed case. Additionally, certain default values should be automatically set in the background to streamline case entry.

### Proposed Change

- [x] Hide Case Classification: The "Case Classification" field should not be displayed for RSV cases.

**Automatically set the following values in the background for each RSV case:**
- [x] Classification: Set as "Confirmed case" in the database for every entered case.
- [x] Date of Classification: Set equal to the "Report Date."
- [x] Classifying User: Set as the "Reporting User."

### Added Value/Benefit

**Streamlined Case Management:**
By automatically classifying every RSV case as "Confirmed" and hiding the case classification field, the data entry process becomes much simpler and quicker for users. This reduces the administrative burden on health authorities and speeds up the workflow.
 **Reduced Human Error:**
Automatically setting the classification date to the report date and assigning the classifying user to the reporting user ensures consistency in the data. This minimizes the risk of human error, as users won’t need to manually enter or select these values.

### Acceptance Criteria

- [x] The "Case Classification" field should not appear in the UI for RSV cases.

In the background, every RSV case should be:
- [x] Automatically classified as "Confirmed" and saved in the database as such.
- [x] The "Date of Classification" should be equal to the "Report Date."
- [x] The "Classifying User" should be the same as the "Reporting User."

- [x] These changes should apply only to RSV cases without affecting other diseases.

**Comment by richardbartha** [comment]
Tested on localhost version 1.99.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/0c557021cc987a83391e4d054f44f55ede18e358)
