### ISSUE TITLE
Configure and Restrict Sample Types and Pathogen Test Types for RSV [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13158]
### Problem Description

For RSV cases, only specific Sample Types and Pathogen Test Types should be displayed and utilized based on the provided information. All other types that are not relevant for RSV should be hidden and unavailable for selection.

### Proposed Change

Adopt Relevant Sample and Pathogen Test Types:
- [ ] The relevant Sample Types and Pathogen Test Types for RSV should be integrated into the system, based on the information provided to us.
Restrict Unwanted Types:
- [ ] Sample Types and Pathogen Test Types that are not applicable to RSV should not be displayed in the system when managing RSV cases.

Pending Information:
- [ ] As we currently do not have the specific details regarding which types should be included or excluded for RSV, this issue is pending until that information is available.

### Added Value/Benefit

**Improved Data Accuracy:**
By only showing the relevant Sample Types and Pathogen Test Types for RSV, users can ensure that the correct information is entered. This reduces the risk of errors and ensures the data collected is specific and applicable to RSV case management.

### Acceptance Criteria

- [ ] Only the specified Sample Types and Pathogen Test Types relevant to RSV should be visible in the system for RSV cases.
- [ ] Any Sample Types and Pathogen Test Types not required for RSV should be hidden and unavailable for selection.
- [ ] Once the necessary information is received, the system should be updated accordingly.

**Comment by XavCol** [comment]
Hello , I don't see any point in masking the other tests, as this information is automatically captured by the lab message processing.
The pathogen test is PCR or antigen test , and we don't receive yet the information on the sampling methode : Nasal swab, Throat swab, Nasopharyngeal aspirate.

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/66df1460cdfb83f412efc6c90c4d2b3ccf26cfaa)

For RSV sample types we have:
![Image](https://github.com/user-attachments/assets/788c94ed-d315-497b-b634-82f56aa97b7f)

For RSV pathogen test types we have :
![Image](https://github.com/user-attachments/assets/18c09960-b343-49fd-9274-7bb8a02f89ca)
