### ISSUE TITLE
[Automatic lab message processing] Create new case if the existing one is too old

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#13154]
### Problem Description

The automatic processing stops when there is a case that's too old to assign the sample to

### Proposed Change

If the case is too old, create a new one

### Added Value/Benefit

More lab messages are processed automatically

### Acceptance Criteria

- [x] Create a new case if the existing one is too old

**Comment by richardbartha** [comment]
Tested on localhost version 1.99.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/0c557021cc987a83391e4d054f44f55ede18e358)

_NOTE: Change automaticsampleassignmentthreshold for the givem disease in the diseaseconfiguration table to how many days you consider a case old enough in order for a new case to be created. If automaticsampleassignmentthreshold is null it will not work!_
