### ISSUE TITLE
Disable Contact Management for RSV Cases [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13157]
### Problem Description

For RSV, contact tracing is not required, and therefore, the contact management functionality should be disabled. The system should ensure that no contacts can be linked, displayed, or added for RSV cases in any part of the system. This behavior should be governed by the "follow up enabled" parameter, which should be set to false for RSV in the disease configuration.

### Proposed Change

Disable Contact Linking for RSV:
- [ ] It should not be possible to link a case managed as RSV via the "Contacts" section.
Remove Contact Management in Case Person View:
- [ ] In the "Case Person" tab, users should not be able to add contacts when viewing an RSV case.
- [ ] The right-side navigation should not display any contact-related information for RSV cases.
System-wide Check:
- [ ] Review and ensure that in every part of the system where a contact can be added or linked, the option is disabled or hidden for RSV cases.
"Follow Up Enabled" Parameter:
- [ ] The "follow up enabled" parameter should be set to false for RSV in the disease configuration, which controls the contact management functionality.

### Added Value/Benefit

**Increased Workflow Efficiency:**
By removing unnecessary contact management options for RSV, users can focus solely on the relevant aspects of case management. This streamlines the workflow, eliminating the distraction of unrelated tasks.

**Reduced User Confusion:**
Since contact tracing is not required for RSV, disabling this feature simplifies the user interface. Users won’t need to navigate or worry about contact tracing elements, making the system easier to use and reducing potential errors or misinterpretations.

### Acceptance Criteria

- [ ] The "Contacts" section should not allow linking to RSV cases.
- [ ] In the "Case Person" view, contacts should not be able to be added or displayed when the case is RSV.
- [ ] The right-side navigation in the "Case Person" view should not display contacts for RSV cases.
- [ ] Ensure that across the system, no contact can be created, linked, or displayed for RSV cases.
- [ ] The "follow up enabled" parameter should be set to false for RSV, ensuring that contact management is disabled for RSV cases.

**Comment by leventegal-she** [comment]
Case person view must have the contact section because a person that is a covid contact can have also RSV case without duplicating the person.
Person view is not hard linked to case, the same person can have any number of cases and contacts with any disease.

@markusmann-vg Wouldn't be better to just don't allow creating contacts with a disease that doesn't have followup enabled?

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/66df1460cdfb83f412efc6c90c4d2b3ccf26cfaa)
