### ISSUE TITLE
Add "Disease" Attribute to Document Templates for Filtering [3]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13160]
### Feature Description

It is requested to add the "Disease" attribute to the Document Templates functionality. This will allow users to assign a disease to a Document Template when creating or editing templates, enabling disease-specific filtering when selecting Document Templates.

### Added Value/Benefit

Improved Efficiency:
Filtering Document Templates by disease allows users to quickly find the relevant templates for a specific disease, such as COVID-19 or RSV. This reduces the time spent searching through irrelevant templates, making the process more efficient.

### Acceptance Criteria

- [ ] When creating or editing Document Templates, the user must be able to assign a Disease from the list of diseases in the system.
- [ ] The selection of Document Templates should allow filtering by Disease, showing only templates that are associated with the selected disease.
- [ ] This feature should apply to all areas where Document Templates are used or selected in the system.

### Implementation Details

Add Disease Attribute to Document Templates:
- [ ] Modify the Document Template creation and editing process to include a "Disease" attribute.
- [ ] The attribute should allow users to select from the list of diseases managed in the system (e.g., COVID-19, RSV).
- [ ] The attribute is optional 
- [ ] Check all locations (Cases, Contacts, Event Participants, Travel Entries) and Configuration

Enable Filtering by Disease:
- [ ] When users are selecting a Document Template, they should have the ability to filter templates based on the Disease attribute.
- [ ] An option can also be "all"
- [ ] Only templates relevant to the selected disease (e.g., COVID-19 or RSV) should be displayed.

**Comment by markusmann-vg** [comment]
@leventegal-she 
Additional requirement after discussion 21.10.2024:
- When entering the document templates section from the case page, the filter and the list of document templates should be pre-selected with the disease of the case

Example:
Case-ID: R367C7
Disease: Covid-19

When clicking Document templates, the filter dropdown should show the preselected "Covid-19" and the the document template dropdown should contain all document templates with the disease of the case

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/66df1460cdfb83f412efc6c90c4d2b3ccf26cfaa)
