### ISSUE TITLE
Birthdate month does not show "Empty" instead of "confidential" when restrictions apply

### ISSUE THREAD

**Issue by sergiupacurariu** [SORMAS-Foundation/SORMAS-Project#13179]
### Bug Description

When Data protection right "See personal data" is removed from an user all the fields designed to hide the data should show "Confidential". The field "Birthdate month" shows "empty string" instead. It should show "Confidential" the same way as the other fields.

### Reproduction Steps

1. Remove from the user role you intend to access Sormas with the Data protection right - "See personal data in jurisdiction"
2. Go to Persons and open a person which has birthday added.
3. The fields birthdate month shows "Empty string" and birthdate day shows "Confidential"

### Expected Behavior

Both fields birthdate month and birthdate day should show "Confidential".

### Affected Area(s)

Web app

### SORMAS Version

Sormas 1.99.0

### Android version/Browser

Edge

### User Role(s)

National User

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/66df1460cdfb83f412efc6c90c4d2b3ccf26cfaa)
