### ISSUE TITLE
Integrate Mandatory Influenza Disease info mapping in E-Santé Adapter

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13187]
### Feature Description

Add mandatory disease-specifics  in SORMAS for influenza cases, with code-based inputs to capture laboratory methods and types of influenza identified.

### Added Value/Benefit

Capturing specific laboratory method details and influenza types as mandatory fields will improve data granularity, essential for accurate surveillance and epidemiological insights.

### Acceptance Criteria

Map the following info to the external message:

- [ ] GRIP-1: Virus isolation method, pathogen test set to "CULTURE."
- [ ] GRIP-2: Nucleic acid detection, pathogen test set to "RT/PCR."
- [ ] GRIP-3: Antigen detection by immunofluorescence, pathogen test set to "Direct Fluorescence Antibody."
- [ ] GRIP-4: Antibody formation detection, pathogen test set to "Antibody detection."
- [ ] GRIP-5: Influenza type (A, B, A+B, NA) displayed in pathogen tests box.
- [ ] GRIP-6: Influenza A subtype (Hx).

### Implementation Details
Further details needed. Possible that should be transformed in a ticket for E-Sante adapter.

### Additional Information
**Sample xml file would be needed**

_No response_

**Comment by leventegal-she** [comment]
This issue requires only adapter changes so [Parse and map GRIP messages #8](https://github.com/SORMAS-Foundation/SORMAS-Luxembourg/issues/8) has been created.
This one can be closed after [#8](https://github.com/SORMAS-Foundation/SORMAS-Luxembourg/issues/8) is closed.
