### ISSUE TITLE
Automate Case Details and Fields Preselection for Influenza Cases [1]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13184]
### Feature Description

Automate certain fields for influenza cases upon creation to improve data entry efficiency and accuracy. This includes pre-selecting certain case details (e.g., case classification, investigation status) and facility address population when available.

### Added Value/Benefit

This automation will reduce manual data entry, ensuring standardized case details and decreasing the chance of user error.

### Acceptance Criteria

- [ ] Automatically select "CONFIRMED CASE" for case classification, "PENDING" for investigation status, and "NO OUTCOME YET" for outcome.
- [ ] Pre-select "Home" for "Place of Stay" 
- [ ] ~Hide the “CASE DEFINITION” info button for influenza.~

### Implementation Details
- Which are the desired case classification available for Influenza? => all, as described in the document (Page 3 1st bulletpoint (all visible)
- 

### Additional Information

- Pre-select "Home" for "Place of Stay" unless the address matches a known facility, in which case the facility should be filled automatically. - **further clarification details needed** => When we do have an address in the lab messages, that can be checked against the existing facilities, we create another ticket for it

_No response_

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/7602439e99e8df20432d27f5bc4ebdc0931617cd)
