### ISSUE TITLE
Add New Influenza Disease Types and Modify Display for SORMAS-Luxembourg [2]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13183]
### Feature Description

Create a new disease classification in SORMAS for "Influenza," which consolidates "Influenza A" and "Influenza B" under this umbrella. Enable "Influenza (new subtype)" for flu management. Integrate the subtype variants to be displayed in the cases directory using the ‘variant’ feature, similar to the Covid implementation.

### Added Value/Benefit

This change will streamline influenza case management by consolidating influenza-related disease types, enhancing clarity for healthcare workers, and enabling a better overview of disease variants.

### Acceptance Criteria

- [ ] Add a new disease "Influenza" and hide "Influenza A" and "Influenza B" in SORMAS.
- [ ] Ensure "Influenza (new subtype)" remains visible and enabled for avian flu.
- [ ] Enable subtype display for Type A (Hx) and Type B in the case directory, displayed in the "variant" section.

### Implementation Details
- add new Influenta disease in Disease enum (active & primary by default, no follow-up)
- change active flag for existing Influenta A and B on Disease enum
- insert Influenta A and B type as disease variant to Customizable Enum table with migration script

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/66df1460cdfb83f412efc6c90c4d2b3ccf26cfaa)
