### ISSUE TITLE
Enhance National Health ID Search Functionality Across Modules and Address Duplication Issues [3]

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13181]
### Problem Description

This issue is related to [Search by NationalID is not consistently working in all locations · Issue #13029](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13029).

Problem Summary:
Duplication Issue: Occasionally, two different individuals associated with the same National Health ID are created. It was observed this while manually processing a lab message. The duplication may stem from variations in the first and last names of these individuals.

Search Limitation in Person Module: When attempting to merge these records in the Person module, you cannot search by the National Health ID. Instead, the search results display a completely different individual, which suggests that the National Health ID search functionality may not have been included in the scope of issue #13029.

### Proposed Change

1. Enable Comprehensive National Health ID Search Across Modules:

Implement a search feature extension allowing users to search by National Health ID across the Case, Person, Contacts Sample, and Message modules. This would allow consistent and accurate retrieval of records associated with a particular National Health ID.
In the Person module, specifically, enhance the search functionality to prioritize National Health ID results, reducing confusion when merging records.

2. Prevent Duplicate Record Creation Based on National Health ID:

Implement validation logic to check for existing National Health ID entries when processing new records (e.g., lab messages) to prevent duplicate entries due to minor name variations.
Display a warning or notification if a duplicate National Health ID is detected, prompting users to review and confirm before creating a new record.

### Added Value/Benefit

- Enhanced Usability and User Confidence
- Reduced Risk of Data Duplication Issues in Reporting and Analysis
- Improved Data Accuracy and Consistency

### Acceptance Criteria

Enhanced National Health ID Search Functionality Across Modules

- [ ]  Users can search by National Health ID across the Case (exists), Person, Contacts(exists), Sample, and Message modules.
- [ ]  The search returns only relevant records associated with the specified National Health ID, reducing mismatched search results.
- [ ] In the Person module, the search prioritizes results based on the National Health ID when merging records.
- [ ] Display a warning or notification if a duplicate National Health ID is detected

**Comment by richardbartha** [comment]
The popup window that informs the user of National Health ID duplicate detectection is a bit confusing since we have a "Done" button that hoverd over displayes "Save" but we do not do any action here its just a notification a better button would be 
( OK , Acknowledged, Accept, Noted etc. ) something similar.  And on hover over do not display save since there is no action saved nothing is modified its just an notification.
![Image](https://github.com/user-attachments/assets/6d352ac5-4746-4418-9a93-63c778c8902b)

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/996f110c4f179bc2b1622494c6bffd2b220929f2)
![Image](https://github.com/user-attachments/assets/f30ebe82-5c6d-4d23-b33a-810b7607c1f1)
