### ISSUE TITLE
Add date range filter for birthdate (from-to) to Persons, Cases, and Contacts

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13190]
### Feature Description

In SORMAS, the user should be able to apply an additional filter for the birthdate across various sections where filters are already used (e.g., Persons, Cases, Contacts). The filter should allow the user to specify a date range (from-to), ensuring that all individuals born within the specified date range are included in the results.

### Added Value/Benefit

The filter ensures that users can quickly access relevant records for cohort studies, epidemiological analysis, or specific age group evaluations, helping to streamline workflows in health data management.

Users can now easily retrieve individuals born within a given period, enhancing their ability to analyze or report on specific cohorts, such as those born in a particular era (e.g., between 1975 and 1999)

### Acceptance Criteria

**Filter UI:**

New input fields should be added in the filter section for selecting a birthdate range.
The user can select a start date ("From") and an end date ("To").
The filter should include individuals born on the selected start and end dates (inclusive).

**Filtering Logic:**

The system should filter persons, cases, and contacts based on the selected date range for birthdate.
The filter should be applied consistently across all sections where applicable: Persons, Cases, Contacts.

**Edge Cases:**

If no start or end date is selected, the filter should act as a non-restrictive search.
If a start date is provided but no end date, the filter should include individuals born on or after the specified start date.
If an end date is provided but no start date, the filter should include individuals born on or before the specified end date.

**Error Handling:**
If the "From" (start date) is later than the "To" (end date), the system should display an error message:
"The start date cannot be later than the end date. Please adjust the date range."

### Implementation Details

**Example:**
If the user selects a range from "01.01.1975" to "31.12.1999", the result should include all persons, cases, and contacts born on or between these dates, including those born on the boundary dates themselves.

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/7602439e99e8df20432d27f5bc4ebdc0931617cd)
