### ISSUE TITLE
Additional lab message fields

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#13203]
### Problem Description

External messages must have fields for vaccination status and hospitalization status of cases

### Proposed Change

- [ ] Add `vaccinationStatus` and `admittedToHealthFacility` fields to external message
- [ ] Map those fields to case when processing a message
- [ ] Show vaccination status field on the UI for RSV cases
- [ ] Set result verified by lab supervisor to "yes"
### Added Value/Benefit

Luxembourg system will be able to transfer all important data related to cases from their eSante sytem

### Acceptance Criteria

- [ ] `vaccinationStatus` and `admittedToHealthFacility` fields are added on external message
- [ ] `vaccinationStatus` and `admittedToHealthFacility` are set when processing a message into a case
- [ ] vaccinationStatus is visible for RSV cases
- [ ] result verified by lab supervisor set to "yes"

**Comment by XavCol** [comment]
Now, we don't receive useful information with this fields, 
So I propose to just add the code ( RSV-4 /RSV-5) and the value to the test result details.
About the vaccinationStatus it should definitely be visible
I will check with our epidemiologist and come back to you as soon as possible.

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/7602439e99e8df20432d27f5bc4ebdc0931617cd)
