### ISSUE TITLE
RSV disease variants

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#13204]
### Problem Description

RSV has disease variants that must be used in SORMAS

### Proposed Change

- [x] change RSV to allow disease variants
- [x] add the default variants: A, B, A+B

### Added Value/Benefit

--

### Acceptance Criteria

- [ ] The user can select a disease variant after selecting RSV when creating cases
- [ ] A, B, A+B variants are present in the system

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/7602439e99e8df20432d27f5bc4ebdc0931617cd)
