### ISSUE TITLE
[Automatic message processing] Check sample assignment threshold against sample data instead of current date

### ISSUE THREAD

**Issue by leventegal-she** [SORMAS-Foundation/SORMAS-Project#13217]
When automatically processing messages check sample assignment threshold against sample data instead of current date

**Comment by richardbartha** [comment]
Tested on localhost version 1.100.0 - SNAPSHOT (https://github.com/SORMAS-Foundation/SORMAS-Project/commits/b757fb9ee9f82206a8020a4140c84ad022d87964)
