### ISSUE TITLE
Refactoring of CurrentUser

### ISSUE THREAD

**Issue by HolgerReiseVSys** [SORMAS-Foundation/SORMAS-Project#1810]
In #1579 `CurrentUser` has been introduced to centralize and cache access to the User entrity of the current user.
Oftentimes the caller is not interested in the entity itself, but its roles, rights, or uuid etc.

Proposed changes:
- `AbstractAdoService::getCurrentUser` should be protected and return `CurrentUser` instead of `User`
- `CurrentUser` should have methods for common use cases: check the roles, rights, etc.
- Facades should not rely on `UserService::getCurrentUser`, but have `Instance<CurrentUser>` injected; Unfortunately there is no common base class.
- Within each method the CurrentUser should be retrieved only once via CDI.
- `CurrentUser` should be an interface, so `@CurrentUserQualifier` whould not be needed

**Comment by JonasCir** [comment]
Ah nice, see also this ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/10844

**Comment by StefanKock** [comment]
A cache was implemented with #7813
