### ISSUE TITLE
Case and Contacts data are completely empty and hospitalization and epi data tabs display an error message.

### ISSUE THREAD

**Issue by raghupola-vg** [SORMAS-Foundation/SORMAS-Project#3235]
### Bug Description
When a case or a contact is accessed, no data is displayed and only a white screen can be seen on Case data and Contact data.
Accessing Epi data tab or hospitalization tab throws an error

### Steps to Reproduce
1. Login to Sormas and Click on Cases
2. Select any case and see if the data for this case is displayed.
3. Select hospitalization tab and see if the page is fully loaded and data displayed.
4. Do the same for contacts, pick a contact and see if contact data is displayed.
5. Clcik on Epi data tab and see if the data is clearly displayed without any error message.

### Expected Behavior
Case and Contat data must be shown and There should be no error message displayed while accessing epi data, hospitalization tab and the respective data has to be shown clearly.

### Screenshots
![no data displyed for contact](https://user-images.githubusercontent.com/62763628/96608463-b3585780-12f9-11eb-99ca-c526f9aa992f.PNG)
![error_accessing hospitalization tab](https://user-images.githubusercontent.com/62763628/96608466-b3f0ee00-12f9-11eb-9110-1ccad741e7c5.PNG)

### System Details
* Device:
* SORMAS version: 1.51.0- snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: https://test.sormas.netzlink.com/
* User Role: SurvSup or ContSup

**Comment by MateStrysewske** [comment]
@raghupola-vg Please ask Netzlink for error logs

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
It seems to not be reproducible.
