### ISSUE TITLE
Create validation for GPS coordinate fields

### ISSUE THREAD

**Issue by BasilKaburi** [SORMAS-Foundation/SORMAS-Project#4387]
### Feature Description
The fields for GPS coordinates and reporting accuracy require validation.
### Problem Description
1.  The fields for latitude and longitudes accept all integers of any magnitude (please see screenshot)
2. The fields for latitude, longitudes, and reporting accuracy do not accept decimals (not good for ensuring precision).
3. The field of reporting accuracy accepts negative numbers
 ### Proposed Change
1. The field for latitude should accept values from -90 to 90  (I suggest a precision of 3 decimal places: -90.000 to 90.000)
2. The field for longitude should accept values from -180 to 180  (I suggest a precision of 3 decimal places: -180.000 to 180.000)
3. The field of  reporting accuracy should accept only positive values (I suggest a precision to 2 decimal places)
### Additional Information
![Screenshot 2021-02-15 at 10 09 12 AM](https://user-images.githubusercontent.com/71414361/107928841-1f319080-6f79-11eb-8ce7-dba1b25fdc5c.JPG)

**Comment by MateStrysewske** [comment]
Already implemented.
