### ISSUE TITLE
[Climedo Integration] Contacts & Cases > Bulk Action for Registration in Symptom Diary

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#4481]
### Situation Description
Public Health offices requested to batch enroll imported lists of persons (contacts and soon cases) into the Symptomtagebuch to avoid enrolling every single one manually.

### Feature Description
Include a bulk action to allow multiple user registration of contacts and cases at the same time for the configured symptom diary.

![image](https://user-images.githubusercontent.com/65529128/108535977-30adcc00-72dc-11eb-8fa0-513a6b7fe22d.png)

**Comment by FredrikSchaeferVitagroup** [comment]
Persons have to meet certain criteria before they can be registered in some symptom journals. For example, a person needs to have a valid email adress and/or a valid phone number, before account registration in climedo is possible.  Also, regristration may fail for other (e.g. technical) reasons. This has to be taken into account here.

**Comment by Candice-Louw** [comment]
Closing as integration is no longer necessary.
