### ISSUE TITLE
Only show entities in the users jurisdiction by default on the mobile app [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#4837]
### Problem Description
On the web app, there are filters like: Include cases from other jurisdiction. This is missing on the mobile app, causing much data that the user do not need being presented to the user.
### Possible Alternatives
None
### Development Specifications
* Don't show cases/contacts in the mobile app by default that are not inside the user's jurisdiction (same logic as in the web app https://github.com/hzi-braunschweig/SORMAS-Project/issues/2137); only do this for the main lists (not for case contacts)
* Add checkbox filters to the case and contact lists ("Include cases/contacts from other jurisdictions") in the mobile app that work similar to those in the web app and that will disable the restriction mentioned above (i.e. checking these filters will include entries from other jurisdictions); default unchecked
* It will be necessary to create a new `FilterCheckboxField` component for this; please try to style it in a way that fits the other filter components

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(a3a2284).

**Comment by leventegal-she** [comment]
Causes. issue no 1. from [#12780](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12780)
