### ISSUE TITLE
Change DiseaseConfigurationFacadeEjb and CustomizableEnumFacadeEjb to use static cache fields [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#5298]
### Feature Description

The disease configurations and customizable enum values contained in the database (or defined by the defaults in the disease enum) are stored and cached in DiseaseConfigurationFacadeEjb and CustomizableEnumFacadeEjb to allow the system to access them without using the database.

### Problem Description

The collections that are used as caches are not static, which means that each cache is created once for each instantiated EJB (several can exist per class), which results in multiple caches being created which could differ over time.

### Proposed Change

Turn the fields that contain the caches into static fields to make sure that only one cache exists at a time.

**Comment by StefanKock** [comment]
To consider: 
- When can this configuration change? Currently you need to restart the payara domain (or redeploy the sormas-ear) to refresh the cache(s).
- Are there other caches with this pattern that may need to be changed?

**Comment by leventegal-she** [comment]
Testing should be done by E2E tests running in parallel

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(0799a1f). E2E team will notify if test are failing due to this (that if the functionality is covered by any test).
