### ISSUE TITLE
Alphabetical sorting should not consider capitalization [3]

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#6024]
### Bug Description

When columns are sorted alphabetically, the column displays capitalized entries alphabetically first and then starts again with lower case text which in the end disrupts the alphabetical order.
### Steps to Reproduce

1. Enter e.g. cases with first names differing in capitalization and first letter
2. Sort the first name column and check the sorted list

### Expected Behavior

All alphabetically sorted columns should disregard capitalization for alphabetical sorting.
### Screenshots

<img width="193" alt="sortingAlphabetically" src="https://user-images.githubusercontent.com/70317594/124092902-a169af80-da57-11eb-9330-57405ca41f43.PNG">

### System Details

* Device:
* SORMAS version: 1.61.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Developer Specifications

**Prerequisite:** #10249

Make sure IndexLists use case-insensitive ordering where necessary:

- instead of using e.g. `ORDER BY name`, use `ORDER BY lower(name)`. As mentioned below, it might be necessary to use `ORDER BY lower(name), name` to prevent certain problems regarding `DISTINCT`
- Do this for every `indexList` which involves freetext-fields which are later displayed in sortable tables/grids
  - This sorting is only necessary for the freetext fields; Predefined fields (e.g. enums) should not be affected, as each value inside of an enum should use the same capitalization
- Investigate potential performance impact. Make sure no tables are initially sorted by any of the freetext fields
- Write some unit tests for sorting (?)

**Comment by DavidBaldsiefen** [comment]
Due to the way the backend works (lazy loading from the database), this is not or barely possible, because sql sorts by the byte-value of characters by default.

@MartinWahnschaffe Maybe you have another idea. The options I found were:

- Using something like `SELECT name FROM person ORDER BY lower(name) DESC`, which lead to problems with `DISTINCT` and may also have a bad performance impact
- Using a `COLLATION`. However the collations supplied by default do not seem to support case insensitive comparisons

**Comment by MartinWahnschaffe** [comment]
Collations only come with support for case insensitivity with PostgreSQL 12 (see https://www.postgresql.org/docs/12/collation.html 23.2.2.4. Nondeterministic Collations), so this is currently not an option for us.

So it looks like our only options is `lower`. You can workaround the distinct problem by doing `ORDER BY lower(name), name` - it sorts case insensitive first and then again case sensitive for the "equal" values.

For performance we have to make sure that sorting by name is not active by default, when opening a view. Where needed we could create an index for `lower(name)`, but I guess this is not necessary.

PS: Also found the citext extension, but it also just does a lower, so it doesn't seem to be beneficial to use that: https://www.postgresql.org/docs/current/citext.html

**Comment by DavidBaldsiefen** [comment]
Considering this problem affects _all_ alphanumerical data, what is the scope of this issue? Only Person names? Maybe Addresses?

Are there languages where the first letter of names is not usually capitalized? If not, would it be an option to always just automatically capitalize the first letter of each name, and provide a script to update existing names?

@MartinWahnschaffe @kwa20

**Comment by kwa20** [comment]
@DavidBaldsiefen I think this would include any free text fields which are displayed in any column outside of their respective forms. To allow flexible use of free text fields, I would probably refrain from automatically capitalizing them. It might make sense for some languages but I couldn't speak for all.

**Comment by DavidBaldsiefen** [comment]
In that case I think we should classify this as a feature/change & evaluate in the next planning, as it will be quite some work to implement and the performance impact should be carefully examined. @StefanKock

**Comment by StefanKock** [comment]
Next step: Check if change to PostgreSQL 12+ would automatically help us with the current collation settings or if we need to implement breaking changes that would force everyone to upgrade to minimal PostgreSQL 12.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(75fa116).
