### ISSUE TITLE
[Climedo] Cases & Contacts > Transfer of additional "no" responses for symptoms

### ISSUE THREAD

**Issue by Candice-Louw** [SORMAS-Foundation/SORMAS-Project#6590]
### Bug Description

When transferring from Climedo to SORMAS, the questions: 
a) Do you have any of the following symptoms? and 
b) Do you have any of the following other symptoms? 
the respective answer: 
No, I do not have any of the symptoms mentioned and 
No, I have no other symptoms
are not transmitted to SORMAS.

If the answer was no, no further symptoms, it would be expected that in SORMAS the symptoms falling under the respective question would be marked with NO. However, there is no marking, so that without looking directly into Climedo you cannot see whether these questions have been answered.

The correct transmission is requested, otherwise in SORMAS the suspicion is aroused in every person that these questions were not answered and therefore a manual callback has to be made. However, since the majority of the people answered these questions in the diary, this leads to unnecessary extra work in the health department and confusion for the people concerned.

### Steps to Reproduce

1. Answer questionnaire in Climedo with "No, I do not have any of the symptoms mentioned" or "No, I have no other symptoms"
2. Navigate to affected case/contact
3. View answers for a specific day's follow-up > Answers missing

### Expected Behavior

For question a), if NO in Climedo, then in SORMAS the symptoms: runny nose, sore throat, cough, rapid breathing, difficulty breathing would have to be set to NO.

For question b), if NO in Climedo in SORMAS, the symptoms: chilliness, severe illness, headache, muscle pain, diarrhea, loss of smell, loss of taste, increased heart rate, nausea, chills or sweating and other clinical symptoms would have to be set to NO.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/131837022-b7292acd-94f6-4452-aa28-913b97947855.png)
![image](https://user-images.githubusercontent.com/65529128/131838522-d258e4d5-df20-4ed8-987f-dac86b291832.png)

### System Details

* Device: PC
* SORMAS version: 1.63
* Android version/Browser: Firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin

### Additional Information

Not sure if a bug, or rather a change @FredrikSchaeferVitagroup ?  Please feel free to update as necessary.

Source (SORMASDE-11376)

**Comment by Candice-Louw** [comment]
Informing @LeonHasselberg-Climedo of the report.

**Comment by FredrikSchaeferVitagroup** [comment]
THe situation most probably is the following: SORMAS depends on what is transmitted by climedo. There is nothing to be done on SORMAS side.

That's why I will move this ticket to waiting, until @LeonHasselberg-Climedo contradicts or reports adaptions on climedo side. Then this ticket can be moved to testing.

**Comment by Candice-Louw** [comment]
@leonhasselberg-climedo - are there any updates on this from Climedo's side, please?

**Comment by Candice-Louw** [comment]
No feedback from Climedo - closing issue as it is stale.
