### ISSUE TITLE
Display the primary telephone number and email of reporting  and responsible user beside the users name [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#6667]
### Feature Description

As a lab officer or surveillance officer, I would like to contact the reporting user or responsible user of parent entities (case, contact, immunization, environment, etc) by phone or email to either get more information, clarify errors in their report or ask them to do something else. Only admins can see the tel and email of reporting users, thus one surveillance officer can not contact another surveillance officer if there is an urgent task to be done.

### Acceptance Criteria

- [x] Add a phone icon button next to the following reporting and responsible user fields in the read and edit forms of the web app:
  - Case, Contact, Event, Event Participant, Immunization, Sample, Environment, Environment Sample
- [x] Clicking on the button brings up a popup window with the user's phone number and email address as labels, and a "Close" button; Use the notSpecified caption when a field is empty
- [x] Add a phone icon button next to the same fields in the read and edit fragments of the mobile app
- [x] Clicking on the button in the mobile app brings up a similar popup

**Comment by kwa20** [comment]
@bernardsilenou if the adding of data becomes too cluttered, what about adding an eye icon next to the reporting user field that displays further user information in a pop-up upon clicking. It can work similarly to what we have when viewing GPS data in addresses. non-editable of course.
<img width="631" alt="Screen Shot 2021-09-08 at 10 12 08 PM" src="https://user-images.githubusercontent.com/70317594/132578685-0643e5c1-b73d-4bb2-8f44-e343e8843e78.png">

**Comment by bernardsilenou** [comment]
@kwa20 
- I think this is a better idea https://github.com/hzi-braunschweig/SORMAS-Project/issues/6667#issuecomment-915537964
- We can then show bot email and tel in the popup information + activation to send email or call when user click on any of them.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- I think the alternative solution would be more appropriate because users would prefer to be contacted by email in some countries
- Possible options I can think of are:

1. show tel + email icon (+ pop up) beside
2. Show only one contact icon and when the user clicks on it, open email and tel in the popup
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/12996724/fabaeb1a-7b3a-4c57-8cad-393b5b97d64f)

- Can this design also work for the mobile app?

**Comment by adinaflorea9** [comment]
I am reopening the ticket after a discussion with @sergiupacurariu for the following:

- [ ] remove hover information 'testUser';
- [ ] add eye icon for Travel Entries reporting user which was not mentioned in requirements but this is a core entity and would like to have it for consistency;
- [ ] add eye icon for Vaccination reporting user (on vaccination cards when the Immunization module is full and reduced) for consistency;
- [ ] hyperlink as discussed in the internal demo for the e-mail to click and be directed to your e-mail provider;
- [ ] regard the changes both on web and mobile.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.91.0-SNAPSHOT(ccaae06).
