### ISSUE TITLE
All archived entities should be deleted from mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#6844]
### Bug Description

Archived entities (case, contacts, events, etc) with duration (current date -report date) less than the archive duration (90 days) specified on server are not deleted from mobile app db.

### Steps to Reproduce

1. create a case with report date yesterday
2. sync the case with server to be sure all is fine
3. archive the case from the web app end
4. sync the tablet with server again, archived case remain on mobile app

### Expected Behavior

- All archived entities should be deleted on mobile app db
### System Details

* Device: Samsung tab A, A11
* SORMAS version: 1.63.2
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role:  National user + admin

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Is this issue valid since archived entities are deleted only the next day?

**Comment by MateStrysewske** [comment]
@bernardsilenou It's probably not valid, correct, because archived entities are only removed from the mobile app once per day. I'm gonna close it!
