### ISSUE TITLE
[Immunizations] Number of doses is missing from the initial immunization load, even if it is present in the immunization creation form

### ISSUE THREAD

**Issue by roxanamlendea** [SORMAS-Foundation/SORMAS-Project#6897]
### Bug Description
When creating a new immunization, if "vaccination" is selected as Means of immunization, in the creation form the user has a field where he can fill in the Number of doses. After the immunization is created, that specific field doesn't appear anymore, and the number of doses can no longer be changed

### Steps to Reproduce

1. Create a new immunization and fill in the requested fields (select Vaccination as Means of immunization, fill in 2 in the Number of doses field")
2. Save

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/136201822-a98ac33e-c734-49ce-bee9-a4c983acbe59.png)
![immunizations](https://user-images.githubusercontent.com/89522688/136202085-05231e83-2d12-4cf0-8896-70c9f684e5fb.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role:

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the local environment with Sormas Version 1.64.1-snapshot using the Hotfix branch
