### ISSUE TITLE
Adding different global values for quarantine period of infected persons/contact persons

### ISSUE THREAD

**Issue by ghost** [SORMAS-Foundation/SORMAS-Project#6905]
### Situation Description
Based on the information provided by the RKI on quarantine periods, we order a five-day quarantine for contact persons, subject to a "free test after 5 days by PCR test".
Unfortunately, 14 days are always set automatically, so that our case handlers have to set the start and end deadline for contact persons manually.
In my opinion, this behavior causes avoidable additional work. In addition, the automatic calculation of the deadline results in clerical errors that have to be corrected.

### Feature Description
I would like to have the possibility, as an administrator, to set different global values for the deadlines, both for infected persons and for contact persons.

**Comment by MateStrysewske** [comment]
@tgell I think you're talking about the follow-up period, right? Because afaik, there's no validation concerning the minimum duration of quarantine in SORMAS. #6862 would allow you to also reduce the follow-up period once it's implemented.
