### ISSUE TITLE
[S2S] Add contacts to handed over cases returns them automatically 

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#6941]
### Bug Description

When contacts are added to a case that Sormas A has handed over to Sormas B, it is automatically returned
### Steps to Reproduce

1. Share a case in Sormas A with Sormas B and hand over the ownership
2. Accept the share request in Sormas B
3. Add a contact to that case in Sormas A
4. Check who is the owner of the case

### Expected Behavior

Case should stay uneditable in Sormas A and Sormas B should remain the owner. Further, contacts should normally be added by Sormas A and editable unless shared separately
### Screenshots

Sormas A
![sharingCasesWithContacts](https://user-images.githubusercontent.com/70317594/136813967-64d1fbbf-d5cc-47a3-be5e-4747eb55f9f3.PNG)

Sormas B
![sharingCasesWithContacts2](https://user-images.githubusercontent.com/70317594/136813981-c94a910b-05cf-4a0f-8a0e-dc7444628295.PNG)

Adding contact in Sormas A
![sharingCasesWithContacts4](https://user-images.githubusercontent.com/70317594/136813944-dff7ddb9-d65f-4650-8511-254dfadca71d.PNG)

Sormas B case information
![sharingCasesWithContacts3](https://user-images.githubusercontent.com/70317594/136814000-2af58180-36be-4c38-afa8-a14a858eaf5b.PNG)

### System Details

* Device:
* SORMAS version: 1.63.2
* Android version/Browser: chrome
* Server URL: https://s2s-rhein-sieg-kreis.sormas.netzlink.com/ , https://s2s-giessen.sormas.netzlink.com/
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.64.1-snapshot from the development branch.
