### ISSUE TITLE
[S2S] Cases can be put into limbo by adding contacts

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#6943]
### Bug Description

When Sormas A shares a case (viewing only) with Sormas B and Sormas B adds a contact to that case, the case gets disabled in both instances.
### Steps to Reproduce

1. Create a case in Sormas A and share (viewing only) with Sormas B with contacts
2. Accept the share request in Sormas B
3. Add a contact to the case in Sormas B
4. Check the ownership in Sormas A for the shared case
5. Check the ownership in Sormas B for the shared case

### Expected Behavior

Case should stay view only in Sormas B and editable with ownership in Sormas A. Basically, editing/creating contacts should not have an influence on the shared case
### Screenshots

Sharing in Sormas A with Sormas B
![sharingCasesWithContactsLimbo](https://user-images.githubusercontent.com/70317594/136819010-95c65a09-f37b-47a4-9a3b-04296bca8e97.PNG)

After share in Sormas A
![sharingCasesWithContactsLimbo2](https://user-images.githubusercontent.com/70317594/136819023-68e5c061-ebc6-42b3-b031-fb0a1c41591c.PNG)

Sormas A: after Sormas B added contact
![sharingCasesWithContactsLimbo3](https://user-images.githubusercontent.com/70317594/136819027-129cb627-0051-4cf0-bf0e-2e54c8b857ad.PNG)

Sormas B: after Sormas B added contact
![sharingCasesWithContactsLimbo4](https://user-images.githubusercontent.com/70317594/136819035-782613cd-6064-4a2a-806e-278c1298ecaa.PNG)
ails

### System Details

* Device:
* SORMAS version: 1.63.2
* Android version/Browser: chrome
* Server URL: https://s2s-rhein-sieg-kreis.sormas.netzlink.com/ , https://s2s-giessen.sormas.netzlink.com/
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
