### ISSUE TITLE
Remove wrong info "creating a new sample will discard all unsaved changes made to this case" [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [SORMAS-Foundation/SORMAS-Project#7350]
### Feature Description
The main view of a case currently displays this info below the sample list.
![grafik](https://user-images.githubusercontent.com/23217632/143061286-eaf284ab-ca52-429a-8a87-7d48aaa750d9.png)

### Problem Description
When creating a new sample here, the system will automatically open the created sample, but before it does so, the system checks for unsaved changes made to the case and asks the user whether to save, discard or cancel.
Thus the info is no longer correct and needed.

### Proposed Change
- [ ] Remove the info in the case and contact view

@kwa20 Please double check whether I'm missing something here.

**Comment by kwa20** [comment]
@MartinWahnschaffe Good idea, I agree that the info message is obsolete and removing it also makes the right column look nicer. I just tried it and a problem I encountered is similar to what is described here https://github.com/hzi-braunschweig/SORMAS-Project/issues/6746.

The unsaved changes problem gets triggered but saving does not work. This seems to only happen in cases but works for contacts and event participants

<img width="346" alt="sampleCreationUnsavedChanges" src="https://user-images.githubusercontent.com/70317594/143072319-5eb1e937-bd42-444c-8d41-fb036a49fff1.PNG">

I think we should make sure that the unsaved changes prompt gets triggered correctly. It might also be confusing that it appears after the sample has been saved. I think we should go with the following flow:

1. User enters data on the (case) form without saving
2. User clicks on "New Sample"
3. Unsaved changes prompt appears
4.1 When user presses 'save', data gets saved and the sample creation form opened
4.2 When user presses 'discard', data does not get saved and the sample creation form opens
4.3 When user presses 'cancel navigation', the pop-up closes but nothing gets changed

**Comment by kwa20** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/issues/7350#issuecomment-976902813 This issue might be addressed in PR #7441 already and is mentioned in https://github.com/hzi-braunschweig/SORMAS-Project/issues/7425#issuecomment-986089010

**Comment by AndyBakcsy-she** [comment]
The issue with the unsaved changes prompt that gets triggered after the sample is created has been fixed on the last 1.66.1 branch.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SBAPSHOT(0799a1f).
