### ISSUE TITLE
History of all data changes

### ISSUE THREAD

**Issue by MartinWahnschaffe** [SORMAS-Foundation/SORMAS-Project#7402]
### Situation Description & Motivation

SORMAS already uses history tables based on the postgres temporal tables plugin to keep track of all data changes. Some needed parts are missing though, e.g. including which user did the change. The goal of this epic is to make sure that all requirements for this topic are covered.

#### Use cases

* A user observes incorrect data in a few cases. To understand how exactly this came to be it should be possible to extract the change history of the cases, including what exactly changed, at what point in time and by which user the change was made.

### High-Level Explanation

We need to be able to:

1. Provide the information when and by whom a change was made
2. Provide what was changed / what the data looked like before and after the change

For now it's sufficient to provide this information on database level

#### Out of scope

* Implementing a user interface that allows to list the change history directly from with a date entry view.

### Timeline

TBD

### Tasks

- [x] #7323
- [x] #7113
- [x] #6822

### Further tasks
- [x] #8027

### Alternatives
* Use the sormas audit DB log, to keep track of these changes. This does only cover changes made via the JPA calls. It does not cover native SQL queries and directly executed SQL. In addition it's not easily possible to query what an entity looked like at a certain point in time.

### Risks
* We depend on the temporal tables postgres plugin which is currently no longer maintained, but open source https://github.com/arkhipov/temporal_tables

**Comment by JonasCir** [comment]
It would be beneficial to merge PRs for #7113 and #6822 before #7323.

**Comment by JonasCir** [comment]
@MartinWahnschaffe I think we came a long way here, only thing left to be done is to remove the legacy audit mechanism? Would be quite cool as we then could also ditch the audit DB in postgres I think...
