### ISSUE TITLE
Enable automatic dependabot PRs [1]

### ISSUE THREAD

**Issue by JonasCir** [SORMAS-Foundation/SORMAS-Project#7507]
### Problem Description

Right now, we are managing our dependencies manually which is slow, error prone, and bears unnecessary risks. 

### Proposed Solution

 - Provide `dependabot.yml` to configure automated updates.
 - Define artifacts to ignore: vaadin dependencies

### Possible Alternatives

Keep clustering dependency updates in bigger tickets and lesser steps to keep stack tested at that point.

### Additional Information

Wait for #11032 and #10499 to be merged to have a clean baseline.

**Comment by JonasCir** [comment]
Dependabot for gradle is more work, this will be a dedicated issue.

**Comment by StefanKock** [comment]
Document in [CONTRIBUTING.md](https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/CONTRIBUTING.md) that such automatic updates are to be merged at the start of an iteration (after the release of the previous version) and that the PRs are to "Rebase and Merge" to avoid blown up git history on the development branch.

**Comment by MartinWahnschaffe** [comment]
See https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12243
