### ISSUE TITLE
New followup until date not initially saved when adding positive samples with earlier collection date

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#7926]
### Bug Description

When a positive sample  with an earlier sample collection date compared to the report date is entered for either cases or contacts, the expected follow-up date is initially adjusted but not the actual follow-up until date. If the case or contact is simply saved after, the date gets adjusted to the date it is now based on. 
### Steps to Reproduce

1. Create a case and set the report date to today
2. Add a positive sample with a collection date one day prior to the report date
3. Check the follow-up until date
4. Simply save the case again and check the dates again.
5. Repeat the process for contacts
6. When prompt to convert the contact, create a case for the person and check both dates

### Expected Behavior

The new date should get saved initially without having to re-save the case or contact. When a contact is converted in the process, it should be done for both since the date is based on the adopted sample as well.
### Screenshots

Initial dates after creation:
![followUpUntilError](https://user-images.githubusercontent.com/70317594/152995271-19855f83-2f52-4a6d-8b33-afe5f0fa74c8.PNG)

Adding a sample with an earlier collection date than the report date:
![followUpUntilError2](https://user-images.githubusercontent.com/70317594/152995270-8a5cf5e4-374d-44a7-9791-fea48f855cfb.PNG)

Initial dates:
![followUpUntilError3](https://user-images.githubusercontent.com/70317594/152995264-d9d152a5-88ea-43ff-903a-ac86f5ccb04d.PNG)

After re-saving cases or contacts:
![followUpUntilError4](https://user-images.githubusercontent.com/70317594/152995274-f2e3439f-c860-49fa-ac96-ac912dda22ab.PNG)

### System Details

* Device:
* SORMAS version: 1.67.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT (0b8c595) from the development branch.
