### ISSUE TITLE
Immunization synchronization does not work

### ISSUE THREAD

**Issue by sergiupacurariu** [SORMAS-Foundation/SORMAS-Project#7980]
### Bug Description
The immunization added to a case on web app does not synchronize with Android app.

### Steps to Reproduce

1. Turn on the Immunization full feature
2. Create an immunization on a case in the web app
3. Synchronize the Android app
4. The immunization is not synchronized

### Expected Behavior

 The newly created immunization should be seen in the immunization section of the case.

### System Details

* Device:
* SORMAS version: 1.67.0+
* Android version/Browser:
* Server URL:Surveillance Officer
* User Role:

**Comment by AndyBakcsy-she** [comment]
Tested is impeded by nightly deploys on test.sormas.netzlink.com
