### ISSUE TITLE
Dates are (displayed) different in SORMAS UI and Mobile App

### ISSUE THREAD

**Issue by FredrikSchaefer** [SORMAS-Foundation/SORMAS-Project#8503]
### Bug Description

The screenshot below shows the same person in Vaadin UI and mobile app. The data is synchronized. You can see that the death date differs by one day.

<img width="947" alt="Different_Dates" src="https://user-images.githubusercontent.com/67001822/159676149-99c00bb3-9045-4920-a840-ff614f58abfb.PNG">

Checking the app database, the date seems to be stored correctly as 1647990000000, which is
Tue Mar 22 2022 23:00:00 in UTC, and Wed Mar 23 2022 00:00:00 in local time (Germany).
I have tried setting the Location of the app emulator to Berlin, but that did not help.

### Steps to Reproduce

1. Compare any date in Vaadin UI and app (except for dates stored as DD/MM/YYYY in the db).

### Expected Behavior

Even though there may be reasons to keep the current behaviour, I would argue that the expected behaviour is that the dates are displayed equally in Vaadin UI and app. Otherwise, there may be weird stuff happening with date validation:
I found out about the current behaviour when reviewing changes to the validation of the death date, wich [shall be validated against the birth date](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8052) (stored as DD/MM/YYYY). Referring to the screenshot, the person was saved with valid dates in Vaadin, but is invalid in the app. I know, that is a weird edge case, but there may be other, less unprobable, scenarios.

### System Details

* Device: Local dev system
* SORMAS version: 1.70-SNAPSHOT
* Android version/Browser: Android studio app emulator/Chrome
* Server URL:
* User Role: National User

**Comment by leventegal-she** [comment]
Could not reproduce in version 1.89.0-SNAPSHOT

Tested with Date of death using the value given in the description and changed report date and classification date set to current date at 23:00 and also using Mar 22 2022 at 23:00

**Comment by adinaflorea9** [comment]
Could also not reproduce the issue on SORMAS version - 1.89.0-SNAPSHOT(a0cc3be). Closing the ticket as discarded.
