### ISSUE TITLE
UnsupportedOperationException: TaskEditActivity.buildRootEntity

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#865]
`UnsupportedOperationException - Root cause: java.lang.UnsupportedOperationException - Stack trace: de.symeda.sormas.app.task.edit.TaskEditActivity:buildRootEntity:51 -> de.symeda.sormas.app.task.edit.TaskEditActivity:buildRootEntity:27 -> de.symeda.sormas.app.BaseEditActivity$3:doInBackground:126 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - Root cause stack trace: de.symeda.sormas.app.task.edit.TaskEditActivity:buildRootEntity:51 -> de.symeda.sormas.app.task.edit.TaskEditActivity:buildRootEntity:27 -> de.symeda.sormas.app.BaseEditActivity$3:doInBackground:126 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - User: RW355A-NLAROT-Y2Q6E4-BOGMCNII - System: https://sormas.org.ng/sormas-rest/`

**Comment by MateStrysewskeSym** [comment]
- [ ] check whether TaskEditActivity is called with a UUID that is associated with a different entity, not a task
- [ ] remove the following code block and replace it with code to finish the current activity:

´if (result == null) {
  result = buildRootEntity();
}´

**Comment by MateStrysewskeSym** [comment]
There's no occurrence of TaskEditActivity being called with the UUID of another entity. Possible scenario why this might've happened: User got assigned a task, notification on Android appeared, task got re-assigned to another user which lead to the original user losing access to it, notification stayed on the phone though and got clicked, redirected the user to the task edit view with a UUID that wasn't on the system anymore because there was a sync in the meantime.

**Comment by MateStrysewskeSym** [comment]
- [ ] In addition to finishing the activity, display a notification: "Entry no longer exists on your device".
