### ISSUE TITLE
Improve slow query for pathogen test result counts in dashboard [2]

### ISSUE THREAD

**Issue by carolinverset** [SORMAS-Foundation/SORMAS-Project#8704]
### Bug Description
In the presence of a large database, access to the dashboard is very problematic or impossible. 
In the production environment, as soon as a user calls the dashboard, the request(s) are launched as expected but run so long that they cause a time out and an interruption of the server connection. It is therefore mandatory to restart the server. To clarify, the map is disabled by default and only a user action (clicking on a button on the map) displays the points on the map. 
On the test environment with a low volume, no access problem. 
On the test environment hosting the dump of the production database, the display of the dashboard was completed after 26 seconds (precision: only one user on this server)

### Steps to Reproduce

1. Use the provided dump (ask @MartinWahnschaffe)
2. Set PerformanceLoggingInterceptor to TRACE
3. Open the reported function: Log in and open the dashboard
4. Use PerformanceLogAnalysisGenerator to analyse the logfile
5. Deliverable: Point out hotspots where a lot of time is lost

### System Details

* Device:
* SORMAS version: 1.67
* Android version/Browser: chrome
* Server URL:
* User Role:admin+national user OR contact supervisor + surveillance supervisor

### Additional Information
@OlivierLeuci @MartinWahnschaffe @MateStrysewske @StefanKock @bernardsilenou

**Comment by MartinWahnschaffe** [comment]
We have access to pseudonymized data that allows to reproduce the very long load times of the dashboard. 
Next step is to take this data and identify the probematic queries & logic.

**Comment by BarnaBartha** [comment]
<img width="1530" alt="Screenshot 2022-04-26 at 13 36 59" src="https://user-images.githubusercontent.com/8166805/165281999-69e98906-2016-4d6c-83d8-b13c38f6ae4b.png">

<img width="1530" alt="Screenshot 2022-04-26 at 13 33 55" src="https://user-images.githubusercontent.com/8166805/165282038-4f75a6be-e611-4e2b-87a5-3e4993ec27c3.png">

**Comment by StefanKock** [comment]
The worst finding seems to be `SampleService.getNewTestResultCountByResultType` that causes the 3000s of execution time (runs a hand written SQL query in batches of 32000 caseIds).

**Comment by BarnaBartha** [comment]
The long running SQL has been rewritten, and some logic moved to Java, the improvement for the specific method is over 1000 times, from ~3000 seconds to ~3 seconds

![Screenshot 2022-04-27 at 12 55 27](https://user-images.githubusercontent.com/8166805/165493408-c2765f78-39b7-491e-b5e1-802e0e39692e.png)

**Comment by StefanKock** [comment]
<details>
<summary>Comparison of SQL before/after</summary>

SQL before:
```sql

-- 1. Get relevant cases: DashboardService.getCases(DashboardCriteria)
SELECT case0_.id AS col_0_0_,
       case0_.uuid AS col_1_0_,
       case0_.reportDate AS col_2_0_,
       case0_.caseClassification AS col_3_0_,
       case0_.disease AS col_4_0_,
       person1_.presentCondition AS col_5_0_,
       person1_.causeOfDeathDisease AS col_6_0_,
       case0_.quarantineFrom AS col_7_0_,
       case0_.quarantineTo AS col_8_0_,
       case0_.caseReferenceDefinition AS col_9_0_
FROM cases case0_
LEFT OUTER JOIN Person person1_ ON case0_.person_id=person1_.id
LEFT OUTER JOIN Region region2_ ON case0_.responsibleRegion_id=region2_.id
LEFT OUTER JOIN District district3_ ON case0_.responsibleDistrict_id=district3_.id
LEFT OUTER JOIN Symptoms symptoms4_ ON case0_.symptoms_id=symptoms4_.id
WHERE case0_.disease=?
  AND region2_.uuid=?
  AND (symptoms4_.onsetDate BETWEEN ? AND ?
       OR (symptoms4_.onsetDate IS NULL)
       AND (case0_.reportDate BETWEEN ? AND ?))
  AND case0_.caseClassification<>?
  AND case0_.deleted=FALSE

-- 2. get sample data: SampleService.getNewTestResultCountByResultType(List<Long> caseIds)
WITH sortedsamples AS
  (SELECT DISTINCT ON (associatedCase_id) associatedCase_id,
                      pathogenTestResult,
                      sampleDateTime
   FROM samples
   WHERE (specimenCondition IS NULL
          OR specimenCondition = 'ADEQUATE')
     AND samples.deleted = FALSE
   ORDER BY associatedCase_id,
            sampleDateTime DESC)
SELECT sortedsamples.pathogenTestResult,
       COUNT(associatedCase_id)
FROM sortedsamples
JOIN cases ON sortedsamples.associatedCase_id = cases.id
WHERE sortedsamples.associatedCase_id IN (?)
GROUP BY sortedsamples.pathogenTestResult

```

SQL After:
```sql
-- DashboardService.getNewTestResultCountByResultType(DashboardCriteria)

SELECT DISTINCT case0_.id AS col_0_0_,
                samples1_.pathogenTestResult AS col_1_0_,
                samples1_.sampleDateTime AS col_2_0_
FROM cases case0_
LEFT OUTER JOIN samples samples1_ ON case0_.id=samples1_.associatedCase_id
LEFT OUTER JOIN Region region2_ ON case0_.responsibleRegion_id=region2_.id
LEFT OUTER JOIN District district3_ ON case0_.responsibleDistrict_id=district3_.id
LEFT OUTER JOIN Symptoms symptoms4_ ON case0_.symptoms_id=symptoms4_.id
WHERE case0_.disease=?
  AND region2_.uuid=?
  AND (case0_.reportDate BETWEEN ? AND ?)
  AND case0_.caseClassification<>?
  AND case0_.deleted=FALSE
  AND samples1_.deleted=FALSE
  AND (samples1_.specimenCondition IS NULL
       OR samples1_.specimenCondition=?)
```

</details>
