### ISSUE TITLE
[User rights] Users without EVENTGROUP_EDIT rights shouldn't be able to edit Event Groups

### ISSUE THREAD

**Issue by roxanamlendea** [SORMAS-Foundation/SORMAS-Project#8922]
### Bug Description
Users that don't have EVENTGROUP_EDIT rights, shouldn't be able to edit the Event Group; it should be read-only.

This is also reproducible for: Hospital Informant; Community Informant, Clinician; Case Officer; Contact Officer; Lab Officer; National Observer; Regional Observer; District Observer; POE Supervisor; 

### Steps to Reproduce

1. Log in with a Contact Supervisor;
2. Navigate to the Events Directory and select the 'Groups' tab;
3. Open an Event Group;
4. Edit the 'Group Name' field and Save;
5. Reload the page;
6. Then try to unlink an Event;

### Actual Behavior
The field can be edited, but after Save the change doesn't persist.
The Event is unlinked.

### Expected Behavior
The Event group should not be editable.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/164476655-7c399e03-cedf-4104-9d8b-8524bcac49c6.png)
![image](https://user-images.githubusercontent.com/89522688/164477789-4542e3b1-6f35-4130-89d9-9eb0df0aee17.png)
![event groups](https://user-images.githubusercontent.com/89522688/164477906-a6bbbbd8-f7e8-486e-ac4c-6d2df85f1fdf.gif)

### System Details

* Device: Windows
* SORMAS version: Sormas 1.71.0-SNAPSHOT (0302732)
* Android version/Browser: 
* Server URL: local server
* User Role: Contact Supervisor; Hospital Informant; Community Informant, Clinician; Case Officer; Contact Officer; Lab Officer; National Observer; Regional Observer; District Observer; POE Supervisor; 

### Additional Information
#8850

**Comment by kwa20** [comment]
Some further findings associated with event groups for version 1.70.3 compared to 1.71.0-SNAPSHOT (f1e438c) as Lab Officer respectively

1.70.3
![eventGroupsView](https://user-images.githubusercontent.com/70317594/166931426-d1a9edfa-03d0-4dbe-8827-be947e5322e5.gif)

1.71.0-SNAPSHOT (f1e438c)
![eventGroupsView2](https://user-images.githubusercontent.com/70317594/166931439-9f795f29-5966-4f4c-aa46-4f9a6bf124ae.gif)

Problems in both cases: The event group view on the directory is empty
1.71.0 problem: navigation through event group cards is disabled

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT from the development branch.
Now all users with EVENTGROUP_EDIT = NO are no longer able to edit the Event Groups.

However, there are still some issues regarding the accessibility rules of the Event Groups, which were discussed with @kwa20 and @dinua and will be refined and fixed in #9101
