### ISSUE TITLE
Add validations for the GPS latitude and longitude fields on the mobile app [1]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#9201]
### Problem Description

Validations for the fields 'GPS Latitude' and 'GPS Longitude' are missing from the mobile app. This leads to connection to server errors, as the synchronization can not be done and the logs show the following error:

![image](https://user-images.githubusercontent.com/96909231/168532841-1091bf71-8e6d-4e99-81fb-bf49168e3d6e.png)

### Proposed Change

Add validations for the GPS related fields similar to those that are currently on the vaadin-app. The maximum value for the 'GPS Latitude' is 90, the minimum -90; and for 'GPS Longitude' it's 180 and -180.

The validations need to be added for the 'GPS Latitude' and 'GPS Longitude' fields from the following pages in the app:

- [x] cases:
  - case person page: 
     - home address section;
     - addresses - new entry;
  - epidemiological data:
    - exposures - new entry;
    - activity as case - new entry;	        
- [x] contacts: 
  - contact person page:
     - home address section;
     - addresses - new entry;
  - epidemiological data - exposure - new entry;
- [x] events:
  - create new event form;
  - event page:
     - event location section;
  - event participant: 
    - person page - home address section;
    - addresses - new entry;
- [x] immunizations:
  - immunization person page
    - home address section 
    - addresses - new entry
- [x] environments
  - create new environment form
  - environment page:
    - environment location section
- [x] environment samples:
  - create new environment sample form
  - environment sample page:
    - environment sample location section

**Comment by BasilKaburi** [comment]
Great! In line with #4387

**Comment by bernardsilenou** [comment]
- Environment entities can be added to the list also.

**Comment by carina29** [comment]
The validation was added to LocationDialog in Android app (used by all the mentioned places) with the implementation of this ticket: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12578 so there is no necessary any other change.

The requested validation is working for all the requested pages.

**Comment by adinaflorea9** [comment]
Closing the ticket as discarded - checked the mobile app and validations are present in the mobile app for the GPS fields.

**Comment by adinaflorea9** [comment]
Closing the ticket as discarded - checked the mobile app and validations are present in the mobile app for the GPS fields.
