### ISSUE TITLE
Samples associated to contacts and event participants are synchronized to the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#9472]
### Bug Description

In the mobile app, if a sample is associated with a contact, whose resulting case was classified as 'Not a case' and not synced to the mobile app, on the sample's page, in the section 'Corresponding person' there is nothing listed, even though the contact associated with that sample is synced and can be found in the mobile app.

The behavior is reproducible for samples associated with event participants, whose resulting case are classified as 'Not a case' and not synced to the mobile app.

### Steps to Reproduce

1. In the vaadin-app, create a contact and add a sample with a positive pathogen test result to it;
2. Click 'Yes' in the pop-up 'Create case from contact with positive test result';
3. In the 'Create new case form', fill in the mandatory fields and save the case;
4. On the case's page, set the 'Case classification' to 'Not a case';
5. In the mobile app, logged in with a Surveillance Officer, trigger a synchronization with the server;
6. Navigate to the 'Samples' directory and look for the sample created at step 1 (it can be recognized based on the UUID);

### Actual Behavior

In the list of samples, it can be observed that under the sample's type, 'Person N/A' is listed. 
On the sample's page, in the section 'Corresponding person' there is nothing listed.

### Expected Behavior

Don't synchronize samples not connected to cases to the mobile app.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/173353142-ef1ad7fb-1714-411e-9a99-6c3087cee2c5.png)

![image](https://user-images.githubusercontent.com/96909231/173353180-abd8792a-a0fc-4951-be5b-14d3a196fb5d.png)

### System Details

* Device: Windows 10 (vaadin-app); Huawei P20 Lite - Android 9 (android-app)
* SORMAS version: 1.73.-SNAPSHOT(c0b0648)
* Android version/Browser: Chrome; Android 9
* Server URL: local machine
* User Role: Admin+NatUser (vaadin-app); Surveillance Officer (android-app)

**Comment by MateStrysewske** [comment]
The actual issue here is that samples related to contacts and event participants are synchronized to the mobile app in the first place, even though they shouldn't (because the sample feature for contacts and event participants is not implemented there). Whether or not there's a resulting case set to "Not a case" doesn't matter, "Person N/A" is always shown for these samples.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(3316ffe).
