### ISSUE TITLE
Immunizations associated with cases created by processing a physician's report are not saved 

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#9654]
### Bug Description

If the user clicks 'Save' after adding an immunization for a case created by processing a physician's report, the immunization information is not saved.

However, if the user clicks 'Save and open case', the immunization information is saved.

Behavior is reproducible both when the full immunization module is enabled, and when it is disabled and only the vaccination card is present.

### Steps to Reproduce

1. In the 'Messages' directory, click to process a physician's report;
2. In the 'Create new case' form, fill in the mandatory information and click 'Save';
3. In the 'Process message' form, navigate to the 'Immunizations' tab, create a vaccine and click 'Done';
4. Click 'Save';
5. Navigate to the 'Cases' directory and open the case created.

### Actual Behavior

The 'Immunizations'/'Vaccination' card is empty.

### Expected Behavior

The 'Immunizations'/'Vaccination' card is filled in with the information inputted at step 3.

### Screenshots

GIF of the steps to reproduce:
![Immunizations](https://user-images.githubusercontent.com/96909231/176178346-563801de-bb6e-4970-a71d-8177f24faa8f.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(c92114e)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by FredrikSchaeferVitagroup** [comment]
This issue is best tested on a local system. You need physician's reports in the database in order to reproduce the steps.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0SNAPSHOT(f27f906).

**Comment by AliciaRaber** [comment]
Test performed on test1402.sormas.netzlink.com 1.74.1 with all features active.
Immunization is in case and can be accessed/edited.
