### ISSUE TITLE
[DEMIS2SORMAS] Converting contacts while processing physician reports can disable source cases in epiData

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#9817]
### Bug Description

When contacts are converted during the case creation while processing physician reports, source case contacts can be disabled via the UI in epiData.
### Steps to Reproduce

1. Prepare by creating at least one confirmed contact for the person to be processed that falls in the incubation period of the case.
2. Start processing the physician report and select the existing person.
3. Create the case so it triggers the "Convert to case" pop-up
4. Select the contact(s) and confirm
5. In the epiData tab in the side by side view, select NO for Contacts with source case known.
6. Finish processing and review the epi data tab in the case

### Expected Behavior

Contacts with source case known should be pre-selected with YES and disabled to not be in conflict with the linked contacts via the conversion.
### Screenshots

![physReportMultConversion](https://user-images.githubusercontent.com/70317594/178511734-2edb7b70-245c-491d-b7db-8f5550e43d11.gif)

### System Details

* Device:
* SORMAS version: 1.73.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
